### ISSUE TITLE
[Feature] Move SelectedTests into TestRunExecutionCreate

### ISSUE THREAD

**Issue by antonio-amjr** [project-chip/certification-tool#100]
### Feature description

Providing the `SelectedTests` to create a new `TestRunExecution` is now mandatory.
So would be convenient to include this information to the `TestRunExecutionCreate` schema, but that would require to also change the TestRunExecution model since the schema is used in the model creation.
This also require to change the way Frontend create JSON Request Data for the endpoint.

Also analyze if this portion of the code [crud_test_run_execution.py#L188-L194](https://github.com/antonio-amjr/certification-tool-backend/blob/4a2af43163aa11b0c9275b91fdcb51a45920701c/app/crud/crud_test_run_execution.py#L188-L194) could be moved to TestRunner or somewhere else.

### Use Cases

[Use Case] Create a TestRunExecution:

- Create a json including all data to `TestRunExecution` plus the `SelectedTests` in Frontend
- Use the create TestRunExecution endpoint of Backend providing the json data

### Additional Information

This is a spin-off issue from [Backend PR#16](https://github.com/project-chip/certification-tool-backend/pull/16).

**Comment by fabiowmm** [comment]
Deprioritized.
