### ISSUE TITLE
[Bug] Backend Container Exited

### ISSUE THREAD

**Issue by Yinxq** [project-chip/certification-tool#108]
### Describe the bug

I'm running TH on a Raspberry Pi 4 (32G). After running continuously for a month, the backend container (chip-certification-tool_backend_1) automatically exited, so I cannot use the WEB GUI on browser. When I run the command: docker start chip-certification-tool_backend_1, it will be up for a short period of time, and then exit again. 
<img width="873" alt="backend container" src="https://github.com/project-chip/certification-tool/assets/56418025/38cff71d-49bb-4a20-bfe0-600ccafa95b1">

### Steps to reproduce the behavior

1. Start Matter TH in Version: matter-th-fall2023
2. docker ps -a
3. docker start chip-certification-tool_backend_1
4. docker ps -a

### Expected behavior

As I don't have the Github account(the one recognized and authorized by Matter), the TH can't be updated. I would expect this problem can be solved without reinstalling TH. 

### Environment

TH version: matter-th-fall2023

**Comment by ccruzagralopes** [comment]
Hi @Yinxq, TH has been migrated from the private repo to this one. So to get the latest version you'll need to clone this new repo or use the latest image. Please be aware that there was a breaking change in the database for this new version so the update process involves reseting it, which will cause you to loose the your data.

To get the latest TH version, you can follow these instructions:
```
rm -Rf <local_copy_of_the_old_repo>
git clone https://github.com/project-chip/certification-tool.git
cd certification-tool
git fetch
git checkout v2.10-beta1.1+spring2024
git submodule update --init
./scripts/ubuntu/auto-update.sh v2.10-beta1.1+spring2024
./scripts/start.sh -b
docker container exec -it certification-tool_backend_1 bash
poetry install
./scripts/reset_db.py
exit
./scripts/stop.sh
./scripts/start.sh
```

**Comment by Yinxq** [comment]
Hi @ccruzagralopes, I followed these steps on another Raspberry Pi 4. When executing the command 
`./scripts/ubuntu/auto-update.sh v2.10-beta1.1+spring2024`
the following error occurred:
![image](https://github.com/project-chip/certification-tool/assets/56418025/ce3091ea-ae48-4e15-b9a5-b600261e3882)

Also I checked the log of the backend as shown below, could this be the cause of the backend container exit?
![image](https://github.com/project-chip/certification-tool/assets/56418025/a9b8a891-7b04-4762-a73f-eeb4eea6f366)

**Comment by ccruzagralopes** [comment]
Hi @Yinxq, the first screenshot reports an `npm` failure. Did this Raspberry Pi have a TH before? If not, you'll have to run the `./scripts/pi-setup/auto-install.sh` script before `auto-update.sh` to install all the dependencies.

Regarding the backend logs, I can't tell the issue from this screenshot, but if you can sand me the whole log I can take a look at it to see if I can find the cause of the problem.

**Comment by ccruzagralopes** [comment]
Hi @Yinxq, I'm glad you were able to run TH.

About the `npm` error: I've never seen it, but maybe there's something different in your environment configuration. Can you please run `./scripts/th/th-doctor.sh --system` and send me the output?

**Comment by Yinxq** [comment]
Hi @ccruzagralopes,  thanks for your reply! I am not able to provide this output now because I have installed the spring2024-TE1 version on this raspberry pi and the yaml files have also been updated.

**Comment by ccruzagralopes** [comment]
@Yinxq great! So I take it that you have a working environment, then? Is there still some problem or can this issue be closed?

**Comment by Yinxq** [comment]
Closing the issue since it has been resolved.

**Comment by Yinxq** [comment]
Closing the issue since it has been resolved.
