### ISSUE TITLE
[TC-OO-2.3] Test case is failing  by throwing an `no close frame received or sent` error After step 24c.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/certification-tool#117]
### Describe the bug

**[TC-OO-2.3]** Test case is failing  by throwing an error  `Test Step Error: Error occurred during execution of test case TC-OO-2.3. no close frame received or sent` error After step 24c.

### Steps to reproduce the behavior

1. Open the UI
2. Upload the PICS
3. Ensure the TC-OO-2.3 test case is selected
4. Executed the below mentioned command to put DUT into a commissionable state, `./chip-all-clusters-app `
5. Click the Start button on Test-Harness user interface.

### Expected behavior

TC-OO-2.3 should execute successfully without error

### Log files

[TC-OO-2.3.log](https://github.com/project-chip/certification-tool/files/13659794/TC-OO-2.3.log)

### PICS file

[On-Off Cluster Test Plan .txt](https://github.com/project-chip/certification-tool/files/13659863/On-Off.Cluster.Test.Plan.txt)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/98016634/6cd9dce3-820e-45b8-973a-25ead1dca706)

### Environment

**TH Version**: main - dev
**Sha**: f17efc4

**Comment by Ashwinigrl** [comment]
TC-OO-2.3 Test case is Still failing in TH `Version: 2.10-beta2.2+spring2024 Sha: 2432a29`.

**Screenshot:**
![image](https://github.com/project-chip/certification-tool/assets/98016634/d65cfdca-1688-4a1a-905c-3ed47987a0e4)

- **DUT**  : All-clusters-app
- **Endpoint** : 1

**Comment by linus2017** [comment]
I PASS this auto-test TC after modifying waiting time 40000ms to 30000ms in step24c of yaml script.  yaml path: /home/ubuntu/ccertification-tool/backend/test_collections/matter/sdk_tests/sdk_checkout/yaml_tests/yaml/sdk/Test_TC_OO_2_3.yaml. 
test log attached
[TC-OO-2.3-TH-Auto-log.log](https://github.com/user-attachments/files/16519257/TC-OO-2.3-TH-Auto-log.log)

**Comment by linus2017** [comment]
screen shoot:
![image](https://github.com/user-attachments/assets/4be43c26-f245-4e9c-9d62-9a1262be16d7)

**Comment by Ashwinigrl** [comment]
All the steps have passed, but at the end of the process, an error occurred with the message: 

> Test Suite Error: Error occurred during cleanup of test suite FirstChipToolSuite. UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> Test Suite Completed [ERROR]: FirstChipToolSuite

**TH Version:** v2.11-beta2+fall2024  Sha: bbeda31
**DUT** : All-clusters-app
**Endpoint** : 1
**PICS file used:** [On-Off Cluster Test Plan.zip](https://github.com/user-attachments/files/16673825/On-Off.Cluster.Test.Plan.zip)
**Reference log:** 
[TC-OO-2.3.log](https://github.com/user-attachments/files/16673878/TC-OO-2.3.log)
**Screen shot:**
![image](https://github.com/user-attachments/assets/5b7e0a16-6f87-4087-83ff-63620f7ce5d2)

**Comment by fabiowmm** [comment]
Fixed.
