### ISSUE TITLE
[Bug] TH accepts invalid dut_config in project configuration, but does not store it

### ISSUE THREAD

**Issue by hiltonlima** [project-chip/certification-tool#119]
### Describe the bug

TH accepts invalid dut_config in project configuration, but does not store it

<img width="1147" alt="image" src="https://github.com/project-chip/certification-tool/assets/116589806/4cdf6af2-c187-4cc1-a31f-560d132f47d4">

We got success when click in update button... 

But when we tried to edit the project again... the "invalid" parameters disappeared.

**Comment by fabiowmm** [comment]
@hiltonlima @rquidute we can close this already, right?
