### ISSUE TITLE
[Bug] UI encounters a 'Test Step Error' during the execution of multiple test cases in a single stretch

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/certification-tool#121]
### Describe the bug

While attempting to validate multiple test cases, the UI encounters a 'Test Step Error' during the execution of multiple test cases in a single stretch.

> 
> - Test Step Error: Error occurred during execution of test case TC-MEDIAINPUT-1.4. sent 1011 (internal error) keepalive ping timeout; no close frame received
> -  - Executing Test Step: Step 2: Read the global attribute: FeatureMap
> - Test Step Not Applicable: Step 2: Read the global attribute: FeatureMap - Test step skipped: Step 2: Read the global attribute: FeatureMap. !MEDIAINPUT.S.F00 == False
> - Executing Test Step: Step 2: Given MEDIAINPUT.S.F00(NU) ensure featuremap has the correct bit set
> - Test Step Error: Error occurred during execution of test case TC-MEDIAINPUT-1.4. sent 1011 (internal error) keepalive ping timeout; no close frame received
> - Test Step Completed [ERROR]: Step 2: Given MEDIAINPUT.S.F00(NU) ensure featuremap has the correct bit set
> - Test Case Completed[ERROR]: TC-MEDIAINPUT-1.4
> - Executing Test Case: TC-MEDIAINPUT-3.10
> - YAML Version: 85a48aabbc4e43c433aa4b2d35b2817d611946de
> - Executing Test Step: Start chip-tool test
> - Using PICS file: /var/tmp/pics
> - Test Step Error: Error occurred during execution of test case TC-MEDIAINPUT-3.10. Connecting to ws://172.18.0.1:9002 failed.
> - Test Step Completed [ERROR]: Start chip-tool test
> - Test Case Completed[ERROR]: TC-MEDIAINPUT-3.10

### Log files

[UI_Test_Run_2023_12_14_16_07_38.log](https://github.com/project-chip/certification-tool/files/13672372/UI_Test_Run_2023_12_14_16_07_38.log)

### PICS file

[Media Cluster Test Plan.txt](https://github.com/project-chip/certification-tool/files/13672303/Media.Cluster.Test.Plan.txt)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/95841834/48acc9c1-bb2d-42ca-826f-cf14eb8099fa)

### Environment

Version: main - dev
Sha: f17efc4

**Comment by Rajashreekalmane** [comment]
https://github.com/project-chip/connectedhomeip/issues/29194

**Comment by fabiowmm** [comment]
Fixed.
