### ISSUE TITLE
[Bug] PICS file for the SDK Python testcases needs to modified in UI

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#122]
### Describe the bug

The SDK python testcases in the UI use the pics file in the path `/var/tmp/pics` But the Testcase is failed because of the mandatory pics is missing.

For eg: drlk-2.3 testcases is failed with the error:`UnlockDoorResponse is a mandatory command response and must be supported in PICS`

This shows that the either the PICS used is wrong or the Pics file not passed to the script

### Log files

[drlk-2-3.log](https://github.com/project-chip/certification-tool/files/13673195/drlk-2-3.log)

### Additional Information

The list of testcases affected by this issue:

- TC_DRLK_2_12
- TC_DRLK_2_2
- TC_DRLK_2_3
- TC_TIMESYNC_2_1

**Comment by ccruzagralopes** [comment]
> This shows that the either the PICS used is wrong or the Pics file not passed to the script

I checked the test scripts and the logs and it seems that the PICS file that was used to run these tests were wrong.

According to the test scripts:
- TC_DRLK_2_2: `DRLK.S.C00.Rsp` needs to be true
- TC_DRLK_2_3: `DRLK.S.C01.Rsp` needs to be true
- TC_DRLK_2_12: `DRLK.S.C27.Rsp` needs to be true
- TC_TIMESYNC_2_1:
   - `TIMESYNC.S.A0000` needs to be true
   - `TIMESYNC.S.A0001` needs to be true
   - if `TIMESYNC.S.A0003` is true, `TIMESYNC.S.F03` also needs to be true
   - if `TIMESYNC.S.A0004` is true, `TIMESYNC.S.F01` also needs to be true
   - if `TIMESYNC.S.A0005` is true, `TIMESYNC.S.F00` also needs to be true
   - if `TIMESYNC.S.A0006` is true, `TIMESYNC.S.F00` also needs to be true
   - if `TIMESYNC.S.A0007"` is true, `TIMESYNC.S.F00` also needs to be true
   - if `TIMESYNC.S.A0008` is true, `TIMESYNC.S.F00` also needs to be true
   - if `TIMESYNC.S.A0009` is true, `TIMESYNC.S.F02` also needs to be true
   - if `TIMESYNC.S.A000A` is true, `TIMESYNC.S.F00` also needs to be true
   - if `TIMESYNC.S.A000B` is true, `TIMESYNC.S.F00` also needs to be true

According to the logs, none of these PICS were set to true

**Comment by Saravana-kr22** [comment]
Yes, This /var/tmp/pics file uses the pics in the xml .Hence this issue is resolved.
