### ISSUE TITLE
[Bug] How to generate NOC chain according to TC-OPCREDS testcases?

### ISSUE THREAD

**Issue by Yinxq** [project-chip/certification-tool#134]
### Describe the bug

According to TC-OPCREDS-3.1, TC-OPCREDS-3.4 and TC-OPCREDS-3.5, TH needs to obtain or generate the NOC chain using the CSR elements from the previous step. How should I get or generate NOC chain?

### Environment

TH version: matter-th-fall2023

**Comment by rquidute** [comment]
Hi @manjunath-grl Can you help on this?

**Comment by cecille** [comment]
This cannot be done manually. These tests are slated to be automated in python by the CSA staff. Are you currently writing automation for these?

**Comment by Yinxq** [comment]
Hi @cecille. I am using Test Harness to test our chip to make it pass certification testing. According to section 2.1.5 of matter spec1.2, Node Operational Credentials cluster is mandatory to test. Feeding the PICS of this cluster into Test Harness shows that the testcases TC-OPCREDS-3.1, TC-OPCREDS-3.4 and TC-OPCREDS-3.5 need to be tested manually, and generating the NOC chain is in the test steps.

If this can't be done manually as you say, could I pass the official certification testing for the Node Operational Credentials cluster?

Also, where should I check which testcases are mandatory to test, thanks a lot if you can tell me!

**Comment by cecille** [comment]
I realize this, but 3.1 at the very least is definitely NOT being run currently. @raju-apple - can you comment on where this might be documented? I assure you that this cannot be done manually. The aim is to have these test cases automated for TE2.of 1.3.
