### ISSUE TITLE
Remove TestRunConfig

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#14]
From chip-certification-tool created by [mikaelhm](https://github.com/mikaelhm): CHIP-Specifications/chip-certification-tool#816  

Once the frontend support the new project format, we can remove the TestRunConfig completely and require TestRunExecutions to be created with selected_tests directly.

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/130402456/b7a5102c-7674-4c20-a7a3-249b764b6d50)
![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/130402456/99368c93-533e-45e4-a577-234258903d5e)

**Comment by raju-apple** [comment]
related issues:
https://github.com/chip-csg/chip-certification-tool-backend/issues/123
https://github.com/chip-csg/chip-certification-tool-backend/issues/124

**Comment by raju-apple** [comment]
@mikaelhm Is this still blocked?

**Comment by raju-apple** [comment]
@mikaelhm: This seems like an old issue (and not applicable anymore), as lot of changes has happened since this was created.
Could you please help in taking further actions on this issue? (Assign v1.X label or close the issue)

**Comment by raju-apple** [comment]
> @raul-marquez-csa, we need an issue for both frontend and backend.
> 
> Can you create 2 sub-issues for 1. and 2. take those, then I can make one for backend.

I created these two

Remove TestRunConfig [Frontend] #887

Remove TestRunConfig [Backend] #888

**Comment by raju-apple** [comment]
Issue on hold

**Comment by fabiowmm** [comment]
Backend PR is approved. Waiting for the front-end PR to be reviewed.

**Comment by mikaelhm** [comment]
I think this one is still related:
https://github.com/project-chip/certification-tool/issues/15#event-10825984608

**Comment by raul-marquez-csa** [comment]
PRs addressing the issue:

**Frontend**: [Updates create and repeat test run execution to match backend changes #13](https://github.com/project-chip/certification-tool-frontend/pull/13)
**Backend**: [[Fix] remove TestRunConfig usage from TH Backend (#581) #6](https://github.com/project-chip/certification-tool-backend/pull/6)
