### ISSUE TITLE
Require Project id in `TestRunExecutionCreate` schema, once UI support project management

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#15]
From chip-certification-tool created by [mikaelhm](https://github.com/mikaelhm): CHIP-Specifications/chip-certification-tool#818  

null

**Comment by raju-apple** [comment]
Waiting to make sure Frontend and CLI can use this.

**Comment by mikaelhm** [comment]
I think it is still applicable:
https://github.com/project-chip/certification-tool-backend/blob/f60cf491ff0b1d19a4c115891bb9a321c97e7b64/app/schemas/test_run_execution.py#L52C1-L52C2
