### ISSUE TITLE
[QUESTION] How to turn on PICS_EVENT_LIST_ENABLED flag?

### ISSUE THREAD

**Issue by Yinxq** [project-chip/certification-tool#150]
### Describe the bug

For TC-BINFO-1.1, I noticed that some steps are skipped, checking the yaml file shows that this is because PICS_EVENT_LIST_ENABLED = False. Are these steps needed to be tested? If they are needed, how should I turn on PICS_EVENT_LIST_ENABLED flag? 

### PICS file

[Basic Information Test Plan.txt](https://github.com/project-chip/certification-tool/files/13987143/Basic.Information.Test.Plan.txt)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/56418025/51323e87-2b03-402d-beaa-23495fbe0555)
![image](https://github.com/project-chip/certification-tool/assets/56418025/00b77b1a-a3af-421b-8376-ef9178b94932)
![image](https://github.com/project-chip/certification-tool/assets/56418025/f8065bc9-2f64-4d3c-af53-83267095179a)

### Environment

TH version: matter-th-fall2023
matter version: v1.2.0.1

**Comment by ccruzagralopes** [comment]
Hey @raju-apple, this seems like a PICS Tool issue. Who should be assigned here?

**Comment by raju-apple** [comment]
Agustin , can you please respond on this ?

**Comment by aperez-csa** [comment]
Matter 1.2 Core Specificaiton Test Plan indicates that for TC-BINFO-1.1 step 5 is not supported.
<img width="632" alt="image" src="https://github.com/project-chip/certification-tool/assets/100227790/8e5fa155-bc78-40d4-913f-92c40d3c8de6">

The PICS_EVENT_LIST_ENABLED appears to be TH variable (not a PICS element)

**Comment by Yinxq** [comment]
Hi @aperez-csa, many thanks for your reply! These steps should be skipped.

I have another question. For TC-CNET-4.12, starting from step 8, in the verification section there is this sentence: Mark as not applicable and proceed to next step. Does this mean that these steps are not currently supported?
![image](https://github.com/project-chip/certification-tool/assets/56418025/4bda400b-80b1-4b43-b94a-f9d0f92083da)

**Comment by cecille** [comment]
Event lists are provisional. They should not be on in a certified product.

**Comment by Minan-Tuyasmart** [comment]
I noticed that  Event list is marked as **M** in the Matter-1.2-Core-Specification, but in the test plan it is marked as skippable, so which document should we use as the test standard when testing?

**Comment by fabiowmm** [comment]
Interest on this seems to have faded out.
