### ISSUE TITLE
[Bug] Unable to run Test Run. Incorrect dut_config attribute cannot be updated

### ISSUE THREAD

**Issue by stingchang** [project-chip/certification-tool#151]
### Describe the bug

After TH application is up and running, when creating new project from GUI the default dut_config has incorrect attribute name.
Based on the screenshot and instruction, **chip_use_paa_certs** should be **chip_tool_use_paa_certs**
However, the GUI tool does not save the parameter name when I click "Create" button. Thus certification tests cannot be run and error message was displayed. @

### Steps to reproduce the behavior

1. Connect to raspberry pi test harness UI interface
2. Add project 
3. Edit Project Config, change **chip_use_paa_certs** to **chip_tool_use_paa_certs**
4. Update and Create
5. Create new Test Run, select test cases and then start 

### Expected behavior

**Test Run** should work and allow DUT to be tested

### Screenshots

<img width="1499" alt="image" src="https://github.com/project-chip/certification-tool/assets/33673360/04eba798-44c9-44c9-97c6-01946aabcff6">

### Environment

- TH version: [2.10-beta2+spring2024]
- Sha: [7682985]
- OS: [Ubuntu 22.04.3 LTS]
- Browser: [firefox, safari, chrome]

### Additional Information

Please see recorded video : [link](https://youtu.be/zBMQdWANgUY)

**Comment by ccruzagralopes** [comment]
@stingchang Can you please update to version `v2.10-beta2.1+spring2024` and verify if this problem still happens?

Update steps:
```
cd certification-tool
./scripts/stop.sh
git fetch
git checkout v2.10-beta2.1+spring2024
git submodule update --init --recursive
./scripts/ubuntu/auto-update.sh v2.10-beta2.1+spring2024
./scripts/start.sh
```

**Comment by stingchang** [comment]
Hi @ccruzagralopes 
I ran these commands but got error saying "cocker-compose command not found" 
<img width="521" alt="Screenshot 2024-01-23 at 9 13 08 PM" src="https://github.com/project-chip/certification-tool/assets/33673360/5f7b97bb-9fba-48d8-829a-580a0e7652ea">

**Comment by ccruzagralopes** [comment]
Please run the following commands:

```
sudo pip3 install docker==6.1.3
sudo pip3 install docker-compose
```

**Comment by stingchang** [comment]
mmm... doesn't seem to work. Any suggestion? 
<img width="773" alt="image" src="https://github.com/project-chip/certification-tool/assets/33673360/c0354264-7c61-499b-82e0-258eb1a13077">

**Comment by ccruzagralopes** [comment]
It usually takes some time for it to load after running the start script.
You can run `docker logs certification-tool_frontend_1` and `docker logs certification-tool_backend_1` to verify if there was any error.

**Comment by stingchang** [comment]
Okay now it's on after waitiing for a bit but there's backend error
```
WARNING: Requirement '/app/test_collections/sdk_tests/sdk_checkout/sdk_runner/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
```

![image](https://github.com/project-chip/certification-tool/assets/33673360/081a9a42-fac3-4137-9b1d-1b232678f83f)

<img width="1002" alt="image" src="https://github.com/project-chip/certification-tool/assets/33673360/32554aa1-bb03-46d5-9cb3-801939ecf92f">

**Comment by ccruzagralopes** [comment]
Oh, it seems that there are some missing files in the backend container. Please run the following commands:

```shell
# in certification-tool repo
./scripts/stop.sh
rm backend/test_collections/sdk_tests/sdk_checkout/.version
docker rmi ghcr.io/project-chip/csa-certification-tool-backend:latest
./backend/scripts/build-docker-image.sh --latest
./scripts/start.sh
```

**Comment by stingchang** [comment]
Hi @ccruzagralopes 
The app can start and run now but unfortunately the original issue is not resolved.
in the Project Config the attribute name is still chip_use_paa_certs by default and cannot be updated after I "Create" the project

**Comment by stingchang** [comment]
I briefly looked at the code change for the version [v2.10-beta2.1+spring2024] but did not see related fix. Can you advise?

**Comment by stingchang** [comment]
Alternatively can you let me know if I can modify the Project Config directly. Maybe through cli tool or use vim to edit it somewhere in the file system on raspberry pi to change chip_use_paa_certs to chip_tool_use_paa_certs as temporary workaround?

**Comment by ccruzagralopes** [comment]
Hi @stingchang the attribute has been renamed to `chip_use_paa_certs`, you don't have to change the Project Config (the user guide needs to be updated, I'll work on that).

What I don't understand is why the execution is producing the error. I was able to run this test case with the default Project Config without any errors. It seems to me like the backend is not properly updated in your environment, so there's some part of the code that still references the old variable `chip_tool_use_paa_certs`.

Did you get any error when running `git submodule update --init --recursive`? can you please run `git submodule status` on the certification-tool repository?

**Comment by stingchang** [comment]
Hi @ccruzagralopes ,

I can finally get the test process run. I am having other issues commissioning physical devices or sample apps provided by connectedhomeip repo. That maybe a separate issue so I'm closing this bug now. Hope I can figure out what's the cause. Thank you very much for the support.
