### ISSUE TITLE
[Bug] Missing Python testcase in UI.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#152]
### Describe the bug

The below mentioned testcase are missing in the SDK python Testcases list

- [ ] TC-DT-1.1
- [ ] TC-IDM-10.1
- [ ] TC-IDM-11.1
- [ ] TC-DESC-2.2

TC-DGGEN-2.4 testcase name is missplled as TC-GEN-2.4 in the latest image :
 ```
Version: 2.10-beta2.1+spring2024
Sha: 549e33f
```

**Comment by rquidute** [comment]
All listed test cases does not exists in the SDK SHA in use: `0ff709f25f6a7af68314c1b0a147a76c30c234f6`
For TC-DGGEN-2.4 test case it should be fixed in SDK repo.

**Comment by rquidute** [comment]
SDK PR to fix the TC-DGGEN-2.4 test case name: https://github.com/project-chip/connectedhomeip/pull/31630

**Comment by Saravana-kr22** [comment]
@rquidute the above listed testcases are available in the TC_DeviceBasicComposition.py

**Comment by Saravana-kr22** [comment]
This issue is resolved in the latest image:`Version: 2.10-beta2.2+spring2024
Sha: 2432a29`
