### ISSUE TITLE
[Bug] Commissioning step is missing for the ACE-2.1 & @ 2.2 Python tetstcases.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#154]
### Describe the bug

For the below mentioned Testcases Commissioning step is missing in the UI and starts the test execution direcltly without commissioning. This affect the testcase execution in the UI.

- [ ]  ACE-2.1 
- [ ]  ACE-2.2

### Expected behavior

Commissioning step needs to be added for this Test-cases like other python testcases 

### Log files

[ace.log](https://github.com/project-chip/certification-tool/files/14038742/ace.log)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/104007654/2b51c484-beb7-4f90-baa0-b75fe8af18a7)

### Environment

Version: 2.10-beta2.1+spring2024
Sha: 549e33f

**Comment by ccruzagralopes** [comment]
Hi @cecille, this is the issue we talked about in last week's meeting.
For TH to identify that a test case expects the DUT to be commissioned, it needs to have the `is_commissioning` parameter set to `True` in the first `TestStep`.

**Comment by cecille** [comment]
https://github.com/project-chip/connectedhomeip/pull/31715

**Comment by fabiowmm** [comment]
@Saravana-kr22 can you verify and close if ok?

**Comment by Saravana-kr22** [comment]
This issiue is resolve the latest Th : `Version: 2.10-beta3+spring2024
Sha: 1fd1429`
