### ISSUE TITLE
Failed to build the new SDK image[Bug] 

### ISSUE THREAD

**Issue by KEEPHEADU** [project-chip/certification-tool#157]
### Describe the bug

I followed the [Matter_TH_User_Guide.pdf](https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.pdf) document to install certification-tool on Ubuntu, but it failed. Below is the failure log.
[log.txt](https://github.com/project-chip/certification-tool/files/14061386/log.txt)

**Comment by ccruzagralopes** [comment]
Hi @KEEPHEADU,
Were you installing on a raspberry pi? Was it connected to the internet?

**Comment by KEEPHEADU** [comment]
> Hi @KEEPHEADU, Were you installing on a raspberry pi? Was it connected to the internet?

Hi @ccruzagralopes  Thank you for your reply. I followed the following section to install on ubuntu.
https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#43-th-installation-without-a-raspberry-pi

I executed the following command separately in the terminal and commented the corresponding line in the Dockerfile
`apt-get install -y libssl-dev libdbus-1-dev libglib2.0-dev libavahi-client-dev avahi-utils iproute2 libcairo2-dev libgirepository1.0-dev python3-pip`

At compile time 21/80, my Ubuntu would restart, and I would need to run the build command again, and then restart again, and repeat

**Comment by ccruzagralopes** [comment]
Did you try to build without caches? You can do that by adding the `--no-cache` flag to the build command.

**Comment by KEEPHEADU** [comment]
> Did you try to build without caches? You can do that by adding the flag to the build command.`--no-cache`

In fact, the previous error was caused by the git buffer being too small. I solved the problem by setting the git buffer.
`git config --global http.postBuffer 2048M`

**Comment by KEEPHEADU** [comment]
Hi @ccruzagralopes , I ran into a new problem when running./scripts/start.sh and Ubuntu told me it was a read-only filesystem.
```
[+] Running 3/4
 ✔ Container certification-tool-db-1        Running                                                                                                                                                   0.0s 
 ✔ Container certification-tool-frontend-1  Running                                                                                                                                                   0.0s 
 ✔ Container certification-tool-proxy-1     Running                                                                                                                                                   0.0s 
 ⠼ Container certification-tool-backend-1   Starting                                                                                                                                                  0.4s 
Error response from daemon: error while creating mount source path '/usr/bin/docker': mkdir /usr/bin/docker: read-only file system
```

**Comment by ccruzagralopes** [comment]
Hi @KEEPHEADU, please run the command `sudo fsck` and try again.

**Comment by KEEPHEADU** [comment]
> Hi @KEEPHEADU, please run the command `sudo fsck` and try again.

I tried this command, but it didn't work.
```
virtual-machine:~/certification-tool$ sudo fsck
fsck from util-linux 2.37.2
e2fsck 1.46.5 (30-Dec-2021)
/dev/sda3 is mounted.
e2fsck: Cannot continue, aborting.
```

I checked my filesystem and it suggested that the root directory was `rw,relatime,errors=remount-ro`
```
virtual-machine:/dev$ mount |grep "/ type"
/dev/sda3 on / type ext4 (rw,relatime,errors=remount-ro)
```

```
virtual-machine:/dev$ sudo fsck -nf
fsck from util-linux 2.37.2
e2fsck 1.46.5 (30-Dec-2021)
Warning!  /dev/sda3 is mounted.
Warning: skipping journal recovery because doing a read-only filesystem check.
Pass 1: Checking inodes, blocks, and sizes
Deleted inode 3670119 has zero dtime.  Fix? no

Inodes that were part of a corrupted orphan linked list found.  Fix? no

Inode 3670432 was part of the orphaned inode list.  IGNORED.
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Block bitmap differences:  -(23653932--23653940)
Fix? no

Free blocks count wrong (4522736, counted=4568644).
Fix? no

Inode bitmap differences:  -3670119 -3670432
Fix? no

Free inodes count wrong (5197484, counted=5197497).
Fix? no


/dev/sda3: ********** WARNING: Filesystem still has errors **********

/dev/sda3: 1323348/6520832 files (0.1% non-contiguous), 21559568/26082304 blocks
```

**Comment by ccruzagralopes** [comment]
That's odd. I'd suggest trying again from the start, with a new VM.

**Comment by KEEPHEADU** [comment]
> That's odd. I'd suggest trying again from the start, with a new VM.

I was misled by the tutorial. TH was ready after running`./scripts/ubuntu/auto-install.sh`, but I continued with tutorial 4.3.3 .

Now it's ready.

![image](https://github.com/project-chip/certification-tool/assets/115463286/7aef1b69-d242-4948-b927-e0bed777fae1)

**Comment by KEEPHEADU** [comment]
Hi @ccruzagralopes , How do I use TH.

**Comment by ccruzagralopes** [comment]
Hi @KEEPHEADU, I believe you can use [this section of the user guide](https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#8-test-configuration) to get started.
Please take a look at the guide and let me know if you have any specific questions.

**Comment by KEEPHEADU** [comment]
> Hi @KEEPHEADU, I believe you can use [this section of the user guide](https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#8-test-configuration) to get started. Please take a look at the guide and let me know if you have any specific questions.

Hi @ccruzagralopes , I don't quite understand the content in this tutorial.  How to Test my own matter device, for example: I have an ESP Matterlight device, how should I use the Test Harness to test it?

And I can't access the PICS file download URL, which requires the authenticated account of CSA alliance members.
https://groups.csa-iot.org/wg/matter-csg/document/26122

**Comment by KEEPHEADU** [comment]
In my attempt, I got a error . `Test Suite Error: Error occurred during setup of test suite.Python Testing suite-legacy`.

This error is in section `TC_ACE_1.3`.

[UI_Test_Run_2024_02_28_16_31_03.log](https://github.com/project-chip/certification-tool/files/14431165/UI_Test_Run_2024_02_28_16_31_03.log)

**Comment by ccruzagralopes** [comment]
About the PICS files: we can't give you access it, you'd have o reach out to the VTM admins and request it.

> (...) how should I use the Test Harness to test it?
You have create a new project, editing the config file to have your network credentials and the information about your device. Then start a new test run, selecting the test cases you wish to run.

The PICS file is important because some test steps are only executed if some PICS are set.

About the error: can you please run the command `./scripts/th/th-doctor.sh --complete` and send me the result?

**Comment by KEEPHEADU** [comment]
> You have create a new project, editing the config file to have your network credentials and the information about your device. Then start a new test run, selecting the test cases you wish to run.

That is to say, I need to use chip-tool to configure the network for my Matter device and operate according to the instructions suggested in TH. TH is only responsible for the log check of chip-tool, am I correct?

Or is TH commissioning the Matter Device and then performing specific test operations?

The problem I am facing now is that TH does not commissioning Matter Device into a fabric.

> About the error: can you please run the command and send me the result?./scripts/th/th-doctor.sh --complete

By the way, my environment is VMware Ubuntu.
[th.log](https://github.com/project-chip/certification-tool/files/14455164/th.log)

thanks

**Comment by ccruzagralopes** [comment]
Hi @KEEPHEADU, so sorry for the late response.

> That is to say, I need to use chip-tool to configure the network for my Matter device and operate according to the instructions suggested in TH. TH is only responsible for the log check of chip-tool, am I correct?
>
> Or is TH commissioning the Matter Device and then performing specific test operations?

I saw from the logs that you executed `TC-IDM-4.2`, which is a manual test. In that case, yes, you'll have to execute the steps manually and upload the logs. That happens for all test cases in the `FirstManualSuite`. For the test in the other test suites, however, TH performs the test steps (with the exception of some manual test steps in the semi-automated test cases) and is the one responsible for the commissioning.

---

Thanks for sending the th log. Can you please run the following command to verify the architecture from the SDK image?

```
docker image inspect --format "{{.RepoTags}} {{.Architecture}}" connectedhomeip/chip-cert-bins:0ff709f25f6a7af68314c1b0a147a76c30c234f6
```

**Comment by KEEPHEADU** [comment]
Hi @ccruzagralopes Thank you for your answer. I see what you mean. I've switched to Raspberry PI now, so we can wrap up our questions about VMware.
