### ISSUE TITLE
[Enhancement] Add a copy button to the manual test pop-up window to simplify manual tests

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#16]
From chip-certification-tool created by [mkardous-silabs](https://github.com/mkardous-silabs): CHIP-Specifications/chip-certification-tool#425  

#### Problem
As of now, to copy a command, the pop-up window needs to be on the edge of the screen for the text selection to register.
This makes it annoying to copy and paste commands durant the manual tests

#### Proposed Solution
Add a copy button in the pop-up window to accelerate test running for manual commands
This would be a great post-SVE1 feature.

**Comment by raju-apple** [comment]
@Xiole-KKE would you be able to look into this issue and provide a fix ? If you can't please let me know and I will re-assign accordingly. Thanks

**Comment by raju-apple** [comment]
I can probably work on this next week, pretty much packed this week.

**Comment by raju-apple** [comment]
Thanks @Xiole-KKE , hopefully you can get to this before Monday 08/15

**Comment by raju-apple** [comment]
Sorry, did not have a chance to reach this issue. Will try get this done by this week.

**Comment by raju-apple** [comment]
https://github.com/CHIP-Specifications/chip-certification-tool-frontend/pull/170

**Comment by fabiowmm** [comment]
This seems to have faded out of interest.
