### ISSUE TITLE
Feature suggestion - Client test cases launch All-Clusters on the Test Harness

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#17]
From chip-certification-tool created by [EF-JANC](https://github.com/EF-JANC): CHIP-Specifications/chip-certification-tool#472  

For DUT as Client test cases, when running the Manual_tests, would it be possible to start the All-Clusters-app as TH in the Test Harness so this can be logged directly with the test case, instead of us having to run 3 separate logging windows (TH + SSH To All-Clusters + SSH to DUT)

**Comment by raju-apple** [comment]
My initial concerns are -

- We need to delete the temp files and run the cluster app between test runs.
- Looks like there are a bunch of custom apps, should we always pick the all-clusters-app?

**Comment by raju-apple** [comment]
Response and design proposal by @mikaelhm:
We might need a custom Test Suite for these so the app is just commisioned once. So we can avoid it for all test cases.
We could make a special "assisted manual test"
- Starts app (agree it should be configurable)
- streams logs without filtering to test engine logger
- Runs normal manual test case prompt flow.

**Comment by raju-apple** [comment]
Visualizing @mikaelhm 's design proposal
<img width="1557" alt="Screen Shot 2022-08-05 at 2 44 55 PM" src="https://user-images.githubusercontent.com/98420997/183219421-6d7d1e71-b107-4f14-b576-23736dbe688c.png">

**Comment by raju-apple** [comment]
@sparampallirajag @mikaelhm Thanks for the feedback!

Please allow me to provide some feedback on the above :)

-Looks like there are a bunch of custom apps, should we always pick the all-clusters-app?
<JC> The testplan 'always' reffers to the All-Clusters-App as the TH so I would say yes as this would contain all clusters and should be the most advanced tool foor client tests.

The above approach of having it as 'manual' tests is fine - I just wanted to **propose** a more user friendly way of working.

And with regards to the deleting the tmp files this is correct, I have made a small script for this to ease the server tests on a SDK ;

```
sudo rm -rf /tmp/chip_* #remove the CHIP Temp files to allow for new commisioning
 
sleep .5 # Wait 0.5 second.
​
./apps/chip-all-clusters-app #Launch ACA
```

**Comment by raju-apple** [comment]
Work in progress. This is not a blocker and will not be ready in a few days. So, removing the v1.x label.

**Comment by fabiowmm** [comment]
@rquidute @ccruzagralopes isso aqui foi realizado pelos commits referenciados acima?

**Comment by ccruzagralopes** [comment]
I believe this mention is a GitHub bug. The mentioned commit is actually from a PR in the backend repo that has the same issue number as this issue: 
- https://github.com/project-chip/certification-tool-backend/pull/17

And just FIY: I believe you didn't notice that you wrote the message in Portuguese 😆
