### ISSUE TITLE
[Bug] Do not attempt ble-wifi commissioning (CNET-4.1, CNET-4.9)

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/certification-tool#174]
### Describe the bug

Run. CNET-4.1 or CNET-4.9
1. Show below Popup message
Precondition: Commission TH and DUT on WiFi network
./chip-tool pairing ble-wifi 0x12344321 <ssid> <password> <setup-pin-code> <discriminator>

But, onnetwork commissioning operates before this popup message.

### Steps to reproduce the behavior

Run. CNET-4.1 or CNET-4.9
1. Show below Popup message
Precondition: Commission TH and DUT on WiFi network
./chip-tool pairing ble-wifi 0x12344321 <ssid> <password> <setup-pin-code> <discriminator>

### Log files

CNET-4.1
TH Log : 
[TH-CNET-4.1.log](https://github.com/project-chip/certification-tool/files/14189457/TH-CNET-4.1.log)

DUT Log : 
[CNET-4.1.txt](https://github.com/project-chip/certification-tool/files/14189455/CNET-4.1.txt)

CNET-4.9
TH Log : 
[TH-CNET-4.9.log](https://github.com/project-chip/certification-tool/files/14189459/TH-CNET-4.9.log)

DUT Log : 
[CNET-4.9.txt](https://github.com/project-chip/certification-tool/files/14189463/CNET-4.9.txt)

**Comment by antonio-amjr** [comment]
Hi @joonhaengHeo,
If I understood correctly, Test Harness is trying a "on network" commissioning by configuration.

Did you try to modify the project's config file for the desired mode:
```
[...]
"dut_config": {
      "discriminator": "3840",
      "setup_code": "20202021",
      "pairing_mode": "ble-wifi",
      "chip_timeout": null,
      "chip_use_paa_certs": false
    },
[...]
```

Let me know if I got the problem right and the results after the configuration.

**Comment by joonhaengHeo** [comment]
@antonio-amjr 
Thanks. BLE commissioning is running after changing this value.

**Comment by antonio-amjr** [comment]
That's great @joonhaengHeo.
No problem.

I'm closing this up then.
