### ISSUE TITLE
[Bug] Failed to commission when trying to run a Python test via UI

### ISSUE THREAD

**Issue by uritustefan** [project-chip/certification-tool#175]
### Describe the bug

When attempting to run a Python test via the harness UI, I get the following errors in the log:
ERROR Failed in verifying 'Attestation Information'  command received from the device: err 101. 
Test Case Error: Error occurred during setup of test case TC_DESC_2_2. Failed to commission DUT

It looks like it's a problem related to the PAA, but I have followed the steps in the test harness user manual and updated the certificates via pdate-paa-certs.sh and pointed towards /var/paa-root-certs/ for the certificates.

I'm attaching DUT logs, TH logs and the test project settings

### Log files

[DESC_2-2_2024_02_07_13_47_42.log](https://github.com/project-chip/certification-tool/files/14194710/DESC_2-2_2024_02_07_13_47_42.log)
[DUT_Log.txt](https://github.com/project-chip/certification-tool/files/14194711/DUT_Log.txt)
[project_settings.txt](https://github.com/project-chip/certification-tool/files/14194724/project_settings.txt)

### Environment

TH Version: 2.10-beta2.2+spring2024Sha: 2432a29

**Comment by rquidute** [comment]
Hi @uritustefan, could you try to update the `paa-trust-store-path` argument from  `/var/paa-root-certs` to `/paa-root-certs`?

**Comment by uritustefan** [comment]
Thank you @rquidute , that did the trick
