### ISSUE TITLE
[Bug] Userguide adoc version has gotten messed up ?

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#183]
### Describe the bug

https://github.com/project-chip/certification-tool/tree/main/docs/Matter_TH_User_Guide

The .adoc version seems to be messed up now , has any PR broken this ?

**Comment by raju-apple** [comment]
Hmm , multiple.adoc files is confusing though, are we making many changes to the user guide though? If not would prefer the older format as most developers use that format

**Comment by fabiowmm** [comment]
@raju-apple you mean confusing for users? They should use the pdf, we always update it when the doc changes.

**Comment by raju-apple** [comment]
PDF they’ll have to download, but what maintenance exactly is troubling that we wanted to break this up? If you click on table of contents it’s an empty page, having everything load is so much better instead

**Comment by fabiowmm** [comment]
ok, then. we'll revert it. @hiltonlima

**Comment by raju-apple** [comment]
Fixed , thanks folks !
