### ISSUE TITLE
[Question] An error occurs in test run

### ISSUE THREAD

**Issue by HirokiOgawa1129** [project-chip/certification-tool#187]
### Describe the bug

An error occurs when I run the test as shown in the screenshot.
I would like to know the solution.

### PICS file

<?xml version="1.0" encoding="utf-8"?><clusterPICS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Generic-PICS-XML-Schema.xsd">
    <name>On/Off Cluster Test Plan</name>
    <clusterId/>
    <picsRoot/>
    <usage>
        <picsItem>
            <itemNumber>OO.S</itemNumber>
            <feature>Does the device implement the on/off cluster as a server?</feature>
            <reference>MATTER</reference>
            <status>O</status>
            <support>true</support>
        </picsItem>
        <picsItem>
            <itemNumber>OO.C</itemNumber>
            <feature>Does the device implement the on/off cluster as a client?</feature>
            <reference>MATTER</reference>
            <status>O</status>
            <support>false</support>
        </picsItem>
    </usage>
    <clusterSide type="server">
        <attributes>
            <picsItem>
                <itemNumber>OO.S.A0000</itemNumber>
                <feature>Does the device implement the OnOff attribute?</feature>
                <reference>Matter_App_Clusters_1.5.6.</reference>
                <status cond="OO.S">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.A4000</itemNumber>
                <feature>Does the device implement the GlobalSceneControl attribute?</feature>
                <reference>Matter_App_Clusters_1.5.6.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.A4001</itemNumber>
                <feature>Does the device implement the OnTime attribute?</feature>
                <reference>Matter_App_Clusters_1.5.6.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.A4002</itemNumber>
                <feature>Does the device implement the OffWaitTime attribute?</feature>
                <reference>Matter_App_Clusters_1.5.6.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.A4003</itemNumber>
                <feature>Does the device implement the StartUpOnOff attribute?</feature>
                <reference>Matter_App_Clusters_1.5.6.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
        </attributes>
        <commandsReceived>
            <picsItem>
                <itemNumber>OO.S.C00.Rsp</itemNumber>
                <feature>Does the device implement receiving the Off command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.C01.Rsp</itemNumber>
                <feature>Does the device implement receiving the On command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.C02.Rsp</itemNumber>
                <feature>Does the device implement receiving the Toggle command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.C40.Rsp</itemNumber>
                <feature>Does the device implement receiving the OffWithEffect command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.C41.Rsp</itemNumber>
                <feature>Does the device implement receiving the OnWithRecallGlobalScene command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.S.C42.Rsp</itemNumber>
                <feature>Does the device implement receiving the OnWithTimedOff command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.S.F00">M</status>
                <support>true</support>
            </picsItem>
        </commandsReceived>
        <commandsGenerated/>
        <Events/>
        <features>
            <picsItem>
                <itemNumber>OO.S.F00</itemNumber>
                <feature>Level Control for Lighting</feature>
                <reference>Matter_App_Clusters_1.5.4.</reference>
                <status>O</status>
                <support>true</support>
            </picsItem>
        </features>
        <manually>
            <picsItem>
                <itemNumber>OO.M.ManuallyControlled</itemNumber>
                <feature>Can the OnOff attribute changed by physical control at the device?</feature>
                <reference/>
                <status>O</status>
                <support>false</support>
            </picsItem>
        </manually>
    </clusterSide>
    <clusterSide type="client">
        <attributes/>
        <commandsReceived/>
        <commandsGenerated>
            <picsItem>
                <itemNumber>OO.C.C00.Tx</itemNumber>
                <feature>Does the device implement sending the Off command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C">M</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.C01.Tx</itemNumber>
                <feature>Does the device implement sending the On command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C">M</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.C02.Tx</itemNumber>
                <feature>Does the device implement sending the Toggle command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C">M</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.C40.Tx</itemNumber>
                <feature>Does the device implement sending the OffWithEffect command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C.F00">M</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.C41.Tx</itemNumber>
                <feature>Does the device implement sending the OnWithRecallGlobalScene command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C.F00">M</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.C42.Tx</itemNumber>
                <feature>Does the device implement sending the OnWithTimedOff command?</feature>
                <reference>Matter_App_Clusters_1.5.7.</reference>
                <status cond="OO.C.F00">M</status>
                <support>false</support>
            </picsItem>
        </commandsGenerated>
        <Events/>
        <features/>
        <manually>
            <picsItem>
                <itemNumber>OO.C.AM-READ</itemNumber>
                <feature>Read all supported mandatory attribute</feature>
                <reference/>
                <status>O</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.AM-WRITE</itemNumber>
                <feature>Write all supported mandatory attribute</feature>
                <reference/>
                <status>O</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.AO-WRITE</itemNumber>
                <feature>Write all supported optional attributes</feature>
                <reference/>
                <status>O</status>
                <support>false</support>
            </picsItem>
            <picsItem>
                <itemNumber>OO.C.AO-READ</itemNumber>
                <feature>Read all supported optional attributes</feature>
                <reference/>
                <status>O</status>
                <support>false</support>
            </picsItem>
        </manually>
    </clusterSide>
</clusterPICS>

### Screenshots

![Screenshot from 2024-02-21 13-10-01](https://github.com/project-chip/certification-tool/assets/33824269/725adc90-c230-4e82-acfd-8429b5cb16ab)

### Environment

TH version: TH Fall2023  Hadware:Raspberrypi 4
OS: Ubuntu 22.04 LTS
DUT FW:nordic Light 

### Additional Information

Project Config
"config": {
    "network": {
      "wifi": {
        "ssid": "testharness",
        "password": "wifi-password"
      },
      "thread": {
        "rcp_serial_path": "/dev/ttyACM0",
        "rcp_baudrate": 115200,
        "on_mesh_prefix": "fd11:22::/64",
        "network_interface": "eth0",
        "dataset": {
          "channel": "15",
          "panid": "0x1234",
          "extpanid": "1111111122222222",
          "networkkey": "00112233445566778899aabbccddeeff",
          "networkname": "DEMO"
        },
        "otbr_docker_image": null
      }
    },
    "dut_config": {
      "discriminator": "3840",
      "setup_code": "20202021",
      "pairing_mode": "ble-thread",
      "chip_tool_timeout": null,
      "chip_tool_use_paa_certs": false
    },
    "test_parameters": {
      "endpoint": 1
    }

**Comment by ccruzagralopes** [comment]
Hi @HirokiOgawa1129, you need to set an Operator in the field indicated by the arrow:
![306498651-725adc90-c230-4e82-acfd-8429b5cb16ab](https://github.com/project-chip/certification-tool/assets/116589288/050d22d0-a630-444c-9e62-4e3e5adc961d)

The first time you write an Operator's name, you'll need to click on it to add it to the database. Then you can continue with your test run.

**Comment by HirokiOgawa1129** [comment]
Thank you for answering.
This was the cause of not being able to click the name entered in the Operator's name edit.
It was an easy mistake.
