### ISSUE TITLE
[TC-CNET-4.9 & 4.10] Test case get fails in UI

### ISSUE THREAD

**Issue by KishokG** [project-chip/certification-tool#192]
### Describe the bug

TC-CNET-4.9 and 4.10 test case is failing in precondition step.

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the Network Commissioning Test Plan(Thread).xml PICS file to select the test cases.
2. Selected the TC-CNET-4.9/4.10 Semi-Automated test case to executed.
3. **For TC-CNET-4.9:** Executed the below mentioned command to put DUT into a commissionable state, ./chip-all-clusters-app --wifi
4. **For TC-CNET-4.10:** Advertise the nRF52840-DK thread board by pressing Button 4.
5. Click the Start button on Test-Harness user interface.

### Expected behavior

TC should execute successfully without error.

### Log files

TC-CNET-4.9: [CNET-4-9_2024_02_22_18_55_37.log](https://github.com/project-chip/certification-tool/files/14374410/CNET-4-9_2024_02_22_18_55_37.log)
TC-CNET-4.10: [UI_Test_Run_2024_02_22_18_20_31.log](https://github.com/project-chip/certification-tool/files/14374105/UI_Test_Run_2024_02_22_18_20_31.log)

### PICS file

[Network Commissioning Test Plan.zip](https://github.com/project-chip/certification-tool/files/14374400/Network.Commissioning.Test.Plan.zip)

### Screenshots

![CNET-4 10](https://github.com/project-chip/certification-tool/assets/133193761/3057b8f1-fe37-4382-8aad-185730fc0a2e)

### Environment

Version: 2.10-beta3+spring2024
Sha: 1fd1429

**Comment by rquidute** [comment]
Hi @manjunath-grl could you please check this?

**Comment by KishokG** [comment]
Still issue not resolved in TH Version: 2.10+spring2024 Sha: 5f28838

**Screenshot:**

![image_2024_04_19T05_26_29_234Z](https://github.com/project-chip/certification-tool/assets/133193761/8e41b1f8-5316-46cc-8a20-23664d65157e)

**Logs:** 
[UI_Test_Run_2024_04_19_05_10_19.log](https://github.com/project-chip/certification-tool/files/15033576/UI_Test_Run_2024_04_19_05_10_19.log)

**Comment by fabiowmm** [comment]
Closing as this is a script issue and there is already a script issue filled for it.

**Comment by mlsg** [comment]
Any updates on this?
Do you have any suggestions on how to execute this test?
