### ISSUE TITLE
Python test gets hangs once after the successfull commissioning in UI

### ISSUE THREAD

**Issue by KishokG** [project-chip/certification-tool#195]
### Describe the bug

When we ran the below mentioned Python test in TH image, the test gets stucked(It's just loading for a long time) once after the successful commissioning and even not able to abort it.

- TC-ACE-2.1
- TC-ACE-2.2
- TC-RVCRUNM-2.1
- TC-RVCRUNM-2.2
- TC-RVCCLEANM-2.1
- TC-RVCCLEANM-2.2

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the PICS file to select the test cases.
2. Selected the python test case in python section to executed.
3. Click the Start button on Test-Harness user interface.

### Expected behavior

TC should execute successfully without error.

### Sample Log files

[ACE_2-2_Python_2024_02_22_17_11_35.log](https://github.com/project-chip/certification-tool/files/14381738/ACE_2-2_Python_2024_02_22_17_11_35.log)
[ACE_2-1_Python_2024_02_22_17_00_10.log](https://github.com/project-chip/certification-tool/files/14381740/ACE_2-1_Python_2024_02_22_17_00_10.log)

### Screenshots

![ACE](https://github.com/project-chip/certification-tool/assets/133193761/8e467962-6aff-4894-98e6-537e2c9bb1e1)

### Environment

Version: 2.10-beta3+spring2024
Sha: 1fd1429

### Additional Information

We suspect this could be a issue these is a  `Final result: PASS !` in middle of the test log which is suspicious
![image](https://github.com/project-chip/certification-tool/assets/133193761/ec4afe99-f324-4af6-bd01-dad76cb79a60)

**Comment by KishokG** [comment]
@survensa FYI

**Comment by rquidute** [comment]
Hi @KishokG, there is an update in the release branch. Could you check if the changes works for you?
Could you please follow the steps bellow in order to update the release branch and test again?

./scripts/stop.sh
cd certification-tool
git fetch
git checkout v2.10-beta3+spring2024
git submodule update --init --recursive
./scripts/start.sh

**Comment by Ashwinigrl** [comment]
Hi @rquidute, Tried with latest Image` Version: 2.10+spring2024 Sha: 5f28838` still facing the same issues for below test cases

- TC-RVCRUNM-2.1
- TC-RVCRUNM-2.2
- TC-RVCCLEANM-2.1
- TC-RVCCLEANM-2.2

**Screenshots:**
![image](https://github.com/project-chip/certification-tool/assets/98016634/83ad27ab-c0ce-463a-9c65-379d328d36f5)

**Sample Log file for TC-RVCCLEANM-2.2:**
[TC-RVCCLEANM-2.2.txt](https://github.com/project-chip/certification-tool/files/15041254/TC-RVCCLEANM-2.2.txt)

**Comment by rquidute** [comment]
Hi @Ashwinigrl could you please attach the PICS file used?

**Comment by Ashwinigrl** [comment]
**PICS File used :**
[RVC Clean Mode Cluster Test Plan.zip](https://github.com/project-chip/certification-tool/files/15042088/RVC.Clean.Mode.Cluster.Test.Plan.zip)
[RVC Run Mode Cluster Test Plan (1).zip](https://github.com/project-chip/certification-tool/files/15042089/RVC.Run.Mode.Cluster.Test.Plan.1.zip)

**Comment by Ashwinigrl** [comment]
**Test parameters configuration used in above test cases:**
**TC-RVCCLEANM-2.1**
"int-arg": "PIXIT_ENDPOINT:1 PIXIT.RVCCLEANM.MODE_CHANGE_OK:2 PIXIT.RVCCLEANM.MODE_CHANGE_FAIL:0",
"endpoint":"1"
**TC-RVCCLEANM-2.2**
"endpoint":"1"
**TC-RVCRUNM-2.1**
"int-arg": "PIXIT_ENDPOINT:1 PIXIT.RVCRUNM.MODE_CHANGE_OK:2 PIXIT.RVCRUNM.MODE_CHANGE_FAIL:0",
"endpoint":"1"
**TC-RVCRUNM-2.2**
"int-arg": "PIXIT.RVCRUNM.MODE_A:1 PIXIT.RVCRUNM.MODE_B:2",
"endpoint":"1"

**Comment by rquidute** [comment]
Hi @Ashwinigrl, could you please test using the final spring version (`v2.10+spring2024`) following the steps bellow?

1 - sudo rm -rf certification-tool
2 - git clone -b v2.10+spring2024 https://github.com/project-chip/certification-tool.git
3 - cd certification-tool
4 - git submodule update --init --recursive
5 - ./scripts/pi-setup/auto-install.sh 
5.1 - At the end of the script, select option 1 to restart the RaspberryPi
6 - Wait about 10 minutes to launch the TH user interface on the user's system using the browser

**Comment by KishokG** [comment]
Issue fixed in,

TH version: v2.11-beta2+fall2024
Sha: bbeda31
