### ISSUE TITLE
[Bug] UI-python testcases with the --tests arguments are failed to show results

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#196]
### Describe the bug

The Python testcases which uses the --tests arguments gets hanged in the UI and fails to populate the result but we could see the test case is being executed properly through the DUT log flow. The runner doest ends and shows the result even the whole test case gets completed.

**For eg:** TC-SM-1.1 testcase is started its execution. but even after completion of the execution still it is in execution state. i.e instead of updating the result the script is waiting for the results, this cause the UI to be in the execution state

### Steps to reproduce the behavior

Step-1. Update the config and pics file of the respective project for testcase which needs to be executed accordingly.
Step-2. Open the project and Run the testcase by selecting the testcase in the add test.

### Expected behavior

UI should be updated with the result of the python testcase

### Log files

DUt log:  [loading.txt](https://github.com/project-chip/certification-tool/files/14384931/loading.txt)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/104007654/83d45d18-0808-4dbd-a6b5-a7d6b4f68781)

### Environment

TH version : `Version: 2.10-beta3+spring2024
Sha: 1fd1429`

### Additional Information

The list of testcase affected by this issue:

- [ ] TC-ACE-2.1
- [ ] TC-ACE-2.2
- [ ] TC-DESC-2.2
- [ ] TC-DT-1.1
- [ ] TC-IDM-10.1
- [ ] TC-IDM-10.2
- [ ] TC-IDM-10.3
- [ ] TC-IDM-10.4
- [ ] TC-IDM-11.1
- [ ] TC-PS-3.1
- [ ] TC-SM-1.1
- [ ] TC-SM-1.2

**Comment by rquidute** [comment]
This issue seems to be related to: https://github.com/project-chip/certification-tool/issues/163

**Comment by rquidute** [comment]
Hi @Saravana-kr22, there is an update in the release branch. Could you check if the changes works for you?
Could you please follow the steps bellow in order to update the release branch and test again?

./scripts/stop.sh
cd certification-tool
git fetch
git checkout v2.10-beta3+spring2024
git submodule update --init --recursive
./scripts/start.sh

**Comment by saravanap-erumal** [comment]
This issue is resolve in latest Th image

**Comment by Saravana-kr22** [comment]
This issue is resolved in latest TH image.
