### ISSUE TITLE
[1.1] Have a way to externally inject a python script

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#20]
From chip-certification-tool created by [raju-apple](https://github.com/raju-apple): CHIP-Specifications/chip-certification-tool#587  

For some semi-automated test cases where we have a user-prompt for a reboot test case with the text "Reboot your DUT"
We should allow the vendor / ATL to write a reboot.py script and that script should be able to provide the "Y" or whatever the TH is waiting for once it's done to continue further . So this in short can convert a few of the semi-automated tests into fully automated ones.

**Comment by raju-apple** [comment]
This is a very generic ask but something that we have been putting off for a while , could you start looking into this and see if you have any ideas on this use case ?

**Comment by fabiowmm** [comment]
Was assigned to @raul-marquez-csa in the old repo.

**Comment by fabiowmm** [comment]
On further analysis we dropped this feature.
