### ISSUE TITLE
[TC-CGEN-2.4]  Python test gets hangs once after the successfull commissioning in UI 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/certification-tool#200]
### Describe the bug

When we ran the below mentioned Python test in TH image, the test gets stucked(It's just loading for a long time) once after the successful commissioning and even not able to abort it.

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the PICS file to select the test cases.
2. Selected the python test case in python section to executed.
3. Click the Start button on Test-Harness user interface.

 ### Expected behavior

TC should execute successfully without error.

### Log files

[TC-CGEN-2.4.txt](https://github.com/project-chip/certification-tool/files/14417423/TC-CGEN-2.4.txt)
[UI_Test_Run_2024_02_27_14_55_29(1).log](https://github.com/project-chip/certification-tool/files/14417425/UI_Test_Run_2024_02_27_14_55_29.1.log)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/95841834/3914f744-95db-4ee4-8ca5-206a335f6423)

### Environment

Version: 2.10-beta3+spring2024
Sha: 1fd1429

**Comment by rquidute** [comment]
This issue seems to be related to: https://github.com/project-chip/certification-tool/issues/163

**Comment by rquidute** [comment]
Hi @Rajashreekalmane, there is an update in the release branch. Could you check if the changes works for you?
Could you please follow the steps bellow in order to update the release branch and test again?

./scripts/stop.sh
cd certification-tool
git fetch
git checkout v2.10-beta3+spring2024
git submodule update --init --recursive
./scripts/start.sh

**Comment by Rajashreekalmane** [comment]
@rquidute I followed the procedure to update the image and validated the TC-CGEN-2.4 test case with the updated image. It worked as expected. Thank you.

**PFA Screenshot :** 
![image](https://github.com/project-chip/certification-tool/assets/95841834/800e8f7d-7f4e-419b-870a-796667203ba7)

**PFA log :** 
[UI_Test_Run_2024_03_15_11_56_56.log](https://github.com/project-chip/certification-tool/files/14611747/UI_Test_Run_2024_03_15_11_56_56.log)
