### ISSUE TITLE
[Bug] TC-S-2.2 setting command 0x4 of clusterID 0xfff1fc05

### ISSUE THREAD

**Issue by pankore** [project-chip/certification-tool#206]
### Describe the bug

TC-S-2.2 does the following step:
```
Executing Test Step: Arithmetic operation to get the maxScenes - 1
CHIP:TOO Command: unittesting test-add-arguments 15 0 0xe59da1c6139d60c8 1
```
is it mandatory to enable unittesting in zap? If DUT disable unit testing, the test fails with 
```
CommandStatusIB =
{
	CommandPathIB =
	{
		EndpointId = 0x1,
		ClusterId = 0xfff1fc05,
		CommandId = 0x4,
	},
	
	StatusIB =
	{
		status = 0xc3 (UNSUPPORTED_CLUSTER),
	},
},
```

### Steps to reproduce the behavior

1. disable unittesting
2. Use TH to run TC-S-2.2 (Semi-Automated)

### Log files

TH logs: [TC-S-2.2.log](https://github.com/project-chip/certification-tool/files/14492634/TC-S-2.2.log)

### Environment

TH version: 2.10-beta3+spring2024 Sha:8f9118a

**Comment by raju-apple** [comment]
@pankore the S.2_2 and S.2_3 tests have been converted during the SVE to use Verification Steps instead . Slack thread about this https://csamembers.slack.com/archives/C06JDQWTU6N/p1709688059094549

**Comment by fabiowmm** [comment]
The originator seems to have lost interest.
