### ISSUE TITLE
[Bug] TC-VALCC-3.1 step 4 and 7 state that CurrentState attribute should be read continuously but it is not.

### ISSUE THREAD

**Issue by CoekaertsJasper** [project-chip/certification-tool#207]
### Describe the bug

CurrentState attribute is only read at open or close but not continuously. 

### Steps to reproduce the behavior

This occurs always when running the Python script. 

### Expected behavior

CurrentState Should also read transitioning state.

**Comment by CoekaertsJasper** [comment]
[TC-VALCC_3-1_2024_03_05_Python_TH.log](https://github.com/project-chip/certification-tool/files/14503454/TC-VALCC_3-1_2024_03_05_Python_TH.log)

**Comment by ReneJosefsen** [comment]
Does the device support transitioning over time? the script keeps reading while the state is transitioning, once it hits Open or Close, depending on the test step it breaks and continues to the next step. So if the DUT go directly to Open or Close state, then it should not read continuously?

**Comment by raju-apple** [comment]
Sounds good , @ReneJosefsen can we close this issue or do we want to get it clarified with the test plan folks ?

**Comment by ReneJosefsen** [comment]
My take is that this is "as designed" and we can close this.
