### ISSUE TITLE
Eliminate DUT Commissioning Prompt for Concurrent Execution of Multiple Python Test Cases

### ISSUE THREAD

**Issue by Survensa** [project-chip/certification-tool#209]
### Feature description

UI should not prompt for DUT commissioning when more than one Python test case is executed concurrently.

![image](https://github.com/project-chip/certification-tool/assets/95559513/355e18f2-833e-43f7-9485-e1f7a3354def)

### Use Cases

During the execution of multiple Python test cases, the UI should refrain from requesting DUT commissioning in between. This is because the first test case is only initiated after a successful commissioning, rendering the prompt unnecessary and illogical.

### Test Cases

Test cases in Python Testing Suite - Legacy

**Comment by fabiowmm** [comment]
This can be solved by adding the proper value for the `is_commissioning` variable in the test script.
