### ISSUE TITLE
[TC-CC-3.2] - Test Case failing due to Cutrrent Hue attribute value mismatch 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#21]
From chip-certification-tool created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-certification-tool#649  

**Description**
[TC-CC-3.2] - Test Case failing due to Cutrrent Hue attribute value mismatch at step 2d

**Additional Info :**
TestHarness:
Version: v2.7Beta2
Sha: 1aff1e6

![image](https://user-images.githubusercontent.com/95841834/215465742-0d96b844-ad37-4820-a4f6-7636b5f9da07.png)

PFA log below
[CC.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/10535338/CC.log)

**Comment by raju-apple** [comment]
Issue resolved in latest Image .
Additional Info:
Version: v2.7.1-official-TE
Sha: e22d9d6

**Comment by raju-apple** [comment]
> @Rajashreekalmane @raju-apple , this is still happening on v2.8.1

Verified with `TH Version: v2.8.1-officialSha: 1446f09` TC-CC-3.2 works as expected and ends with PASS.

- DUT : All-clusters-app
- Endpoint : 1 
- PICS used : [TC_CC_PICS.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/11551099/TC_CC_PICS.zip)

### Snapt Shot of the particular step :
![Screenshot from 2023-05-23 12-44-48](https://github.com/CHIP-Specifications/chip-certification-tool/assets/95559513/aadf5bfb-06ca-4f7f-9b69-5ee70d2de50d)

### References :

- Execution Log : [UI_Test_Run_2023_05_23_12_38_32.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11551118/UI_Test_Run_2023_05_23_12_38_32.log)

- Execution Report : [Test Report.pdf](https://github.com/CHIP-Specifications/chip-certification-tool/files/11551120/Test.Report.pdf)

Please cross verify the log that I have attched also please attch your so that we will be able to RC the issue.

**Comment by raju-apple** [comment]
@Survensa thanks for checking this. I added timestamp to my DUT logs, please have a look at it. At line 2768, the DUT starts to transition downwards from 60 at a rate of 5steps/second. At line 2885 the read request comes in.

Time between start transition and read request is 10.6 seconds.
10.6 * 5 = 53
So the CurrentHue read will be 60 - 53 = 7, causing my DUT to fail.

I think when running this with the linux all-clusters-app on the same host as TH, the communication delay between the TH and all-clusters-app is smaller as compared to real products, that's why you are not able to reproduce it. I believe some other platforms are facing this issue as well.

DUT log: [cc-3-2.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/11765835/cc-3-2.txt)

Related issues:
https://github.com/CHIP-Specifications/chip-test-plans/issues/2332
https://github.com/CHIP-Specifications/chip-certification-tool/issues/590

**Comment by raju-apple** [comment]
I just wanted to add our logs. We've seen that the TestHarness 2.8.1 is failing consistently for us, while running the same test case from ChipTool on a PC it is consistently passing. The difference appears to be the timing of sending the message after the 10 second delay. It seems the TestHarness is around 500ms slower.

[TestHarness Log CC_3-2_2023_07_12_11_49_08.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12245849/TestHarness.Log.CC_3-2_2023_07_12_11_49_08.log)

Here is an excerpt from the logs for our Test Harness. The message is sent at `1689126611.442990` and then the second message is sent at `1689126622.077342` which is a 10.634 second gap. (So, going from 60 hue to 7 hue over 10.634 seconds is the correct value).
```
CHIPTOOL   | 2023-07-12 01:50:11.632652 | [1689126611.442067][24:32] CHIP:TOO:  ***** Test Step 17 : TH sends MoveHue command to DUT with MoveMode=0x03 (down) and Rate=5 (units/s)
...
CHIPTOOL   | 2023-07-12 01:50:11.660656 | [1689126611.442990][24:32] CHIP:IN: (S) Sending msg 143287555 on secure session with LSID: 19050

CHIPTOOL   | 2023-07-12 01:50:22.112156 | [1689126622.076481][24:32] CHIP:TOO:  ***** Test Step 19 : TH reads CurrentHue attribute from DUT
...
CHIPTOOL   | 2023-07-12 01:50:22.526851 | [1689126622.077342][24:32] CHIP:DMG: SendReadRequest ReadClient[0xffff78016390]: Sending Read Request
```

Compared to the CHIP Tool on the PC. This takes 10.134 seconds to send the message. There I've seen between 8-10 which is within the tolerance.
```
[1689296342073] [68576:8663090] [TOO]  ***** Test Step 17 : TH sends MoveHue command to DUT with MoveMode=0x03 (down) and Rate=5 (units/s)
[1689296342074] [68576:8663090] [IN] (S) Sending msg 18120214 on secure session with LSID: 44065
[1689296352207] [68576:8663209] [TOO]  ***** Test Step 19 : TH reads CurrentHue attribute from DUT
[1689296352208] [68576:8663209] [IN] (S) Sending msg 18120216 on secure session with LSID: 44065
```

**Comment by raju-apple** [comment]
thanks for providing details. Root cause is a wrong interpretation of tolerance rules in the script - one example of https://github.com/CHIP-Specifications/chip-test-plans/issues/2332 .
While it would be good to speed up the TH, or compensate for the extra delay (if this is fixed, we can compensate and make the wait time 9.5 s instead of 10 s)
But the resolution for this particular issue is fixing the tolerances, see https://github.com/CHIP-Specifications/chip-test-plans/issues/2332#issuecomment-1635497808 for details

**Comment by raju-apple** [comment]
This issue has been addressed in this PR https://github.com/project-chip/connectedhomeip/pull/28159 (commit 98781285915b198b4f01b32ba36c88a96983b2c4). The accepted range was expanded from 8-12 to 4-16. Not sure when that will make it's way into the Test Harness, but just wanted to share that the Test Case itself has been updated.

**Comment by raju-apple** [comment]
@raju-apple We've tested Test Harness beta (`TH_fall2023_beta3`) and found that the problem discussed appears to be worse in this version (when compared with 2.8.1). We're now seeing steps 2c, 2d, 2f, 2g and 3c all fail. Looking at the logs it appears the Test Harness is taking longer to send messages so steps that were previously passing are now exceeding the tolerance. 

For example, step 2c starts at hue 200 and uses MoveHue to go up, it waits 10 seconds and expects a hue of 250. However, the tolerance is 215-255, which means there's only an effective 1 second tolerance (250-255). Testing on a Raspberry Pi 4 on an isolated network (we cooled the Pi down to ensure thermal throttling wasn't playing a role), the logs show it took 1.41 seconds for the Pi to send the message. So, if you consider starting at 200 hue and going up at 5 hue per second, then after 11.41 seconds a value of 1 seems correct. 

From our testing, it looks like the Test Harness was taking around 500ms to send a message in 2.8.1 but is now taking over a second in the newest beta.

_CC-3.2 Step 2c Failure_
```
INFO       | 2023-08-08 08:11:38.921846 | Executing Test Step: Step 2b: TH sends MoveHue command to DUT with MoveMode=0x01 (up) and Rate=5 (units/s)
CHIPTOOL   | 2023-08-08 08:11:39.399382 | CHIP:TOO Command: colorcontrol move-hue 1 5 0 0 0x1950474687ba6a9e 1 
CHIPTOOL   | 2023-08-08 08:11:39.400909 | CHIP:TOO Sending command to node 0x1950474687ba6a9e
...
CHIPTOOL   | 2023-08-08 08:11:50.811706 | CHIP:EM <<< [E:45782i S:30820 M:35146545] (S) Msg TX to 1:1950474687BA6A9E [10A2] --- Type 0001:02 (IM:ReadRequest)
CHIPTOOL   | 2023-08-08 08:11:50.812566 | CHIP:IN (S) Sending msg 35146545 on secure session with LSID: 30820
...
CHIPTOOL   | 2023-08-08 08:11:50.879119 | CHIP:TOO Endpoint: 1 Cluster: 0x0000_0300 Attribute 0x0000_0000 DataVersion: 1636690129
CHIPTOOL   | 2023-08-08 08:11:50.879982 | CHIP:TOO   CurrentHue: 1
WARNING    | 2023-08-08 08:11:50.881543 | Test Failure: The response value (1) should be greater or equal to the constraint but 1 < 215.
INFO       | 2023-08-08 08:11:50.895509 | Test Step Completed [FAILED]: Step 2c: TH reads CurrentHue attribute from DUT
```

_CC-3.2 Step 3c Failure_
```
INFO       | 2023-08-08 08:12:19.368673 | Executing Test Step: Step 3b: TH sends MoveHue command to DUT with MoveMode=0x03 (down) and Rate=5 (units/s)
CHIPTOOL   | 2023-08-08 08:12:20.205705 | CHIP:TOO Command: colorcontrol move-hue 3 5 0 0 0x1950474687ba6a9e 1 
CHIPTOOL   | 2023-08-08 08:12:20.207495 | CHIP:TOO Sending command to node 0x1950474687ba6a9e
...
INFO       | 2023-08-08 08:12:30.658668 | Executing Test Step: Step 3c: TH reads CurrentHue attribute from DUT
CHIPTOOL   | 2023-08-08 08:12:31.313677 | CHIP:TOO Command: colorcontrol read current-hue 0x1950474687ba6a9e 1 
CHIPTOOL   | 2023-08-08 08:12:31.316085 | CHIP:TOO Sending command to node 0x1950474687ba6a9e
```


_Here are logs from two separate test runs_
[m141_fab_CC_3-2_th-fall-beta3_2023_08_08_18_11_03.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12297013/m141_fab_CC_3-2_th-fall-beta3_2023_08_08_18_11_03.log)
[m141_fab_CC_3-2_th-fall-beta3_2023_08_08_18_07_06.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12297011/m141_fab_CC_3-2_th-fall-beta3_2023_08_08_18_07_06.log)

**Comment by raju-apple** [comment]
@fabiowmm can you please take a look at this issue ?

**Comment by raju-apple** [comment]
Verified with TH `Version: TH Fall2023 , Sha: 22538eb7` TC-CC-3.2 test case is still failing in step 2c, 2d with Cutrrent Hue attribute value mismatch.

- **DUT** : All-clusters-app
- **Endpoint** : 1
- **PICS used** : [Color Control Cluster Test Plan.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12545250/Color.Control.Cluster.Test.Plan.zip)

**Snapt Shot of the particular steps :**
![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/98016634/a3b56cc8-7e94-462c-b516-f897b1852e68)

**References :**
 Execution Log :  [TC-CC-3.2.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12545292/TC-CC-3.2.log)

**Comment by raju-apple** [comment]
quoting from @stonehouse  message above:

> For example, step 2c starts at hue 200 and uses MoveHue to go up, it waits 10 seconds and expects a hue of 250. However, the tolerance is 215-255, which means there's only an effective 1 second tolerance (250-255). 

This tolerance range is wrong!!
The tolerance should be symmetric around the expected value (250) *and* take into account that hue valiues will `wraparound`
So if a tolerance range of 35 is allowed (example)...
- the minimum allowed value is 250-35 = 215
- and the maximum allowed value is 250+35 = 285 which wraps around to 285-256=29

So the script should accept values in range 215..255 *and* 0..29 in this case.
(note that I'm using example value, please do the math for all applicable cases and update script and VS

fyi @raju-apple  @Ashwinigrl  @fabiowmm @Survensa  @akrithika27

**Comment by Ashwinigrl** [comment]
@manjunath-grl  Verified with **TH Version:** Version: main - dev  **Sha:** f17efc4 TC-CC-3.2 test case is  failing in step 2d, 2f and 2g with Cutrrent Hue attribute value mismatch.

**DUT** : All-clusters-app
**Endpoint** : 1
**PICS used** :
[Color Control Cluster Test Plan .txt](https://github.com/project-chip/certification-tool/files/13660359/Color.Control.Cluster.Test.Plan.txt)
[On-Off Cluster Test Plan .txt](https://github.com/project-chip/certification-tool/files/13660360/On-Off.Cluster.Test.Plan.txt)
**Screen Shot of the particular steps :**
![image](https://github.com/project-chip/certification-tool/assets/98016634/51498f43-4ac4-4d6a-ba3a-01722545f181)
**References :**
Execution Log : 
[TC-CC-3.2.log](https://github.com/project-chip/certification-tool/files/13660373/TC-CC-3.2.log)

**Comment by manjunath-grl** [comment]
@Ashwinigrl Used fixed in PR [30951](https://github.com/project-chip/connectedhomeip/pull/30951) please verify and close the ticket.

**Comment by rquidute** [comment]
Hi @Ashwinigrl is this issue still valid?
