### ISSUE TITLE
Reduce Execution Time for Python Test Cases via UI

### ISSUE THREAD

**Issue by Survensa** [project-chip/certification-tool#210]
### Feature description

Executing Python test cases through the UI takes longer; for instance, completing a test case with three steps via UI requires approximately 3 minutes. This duration exceeds the time taken for manual execution or running the same test case through a Python script within the SDK Docker container.

## Test initiated Time :
![image](https://github.com/project-chip/certification-tool/assets/95559513/5e004b57-fde8-4c82-a38c-0084a7f680b7)

## Execution Completed Time :
![image](https://github.com/project-chip/certification-tool/assets/95559513/037e0c80-370c-4531-8c7b-c4d6e45207d5)

### Use Cases

Completing the python test execution using UI faster than manual execution.

### Test Cases

All python test case available in TH UI

**Comment by fabiowmm** [comment]
@antonio-amjr I believe this was fixed by you in another issue? If yes, please close this one.

**Comment by antonio-amjr** [comment]
@fabiowmm that's correct, a change was merged addressing this long delay issue, but it's only available in the spring2025 release.

@Survensa I'll close this out but feel free to test this whenever possible and open a new issue if the problem persists.
