### ISSUE TITLE
[Bug] TC-DGGEN-2.3 PIXIT.DGGEN.ENABLEKEY is not used by the TH

### ISSUE THREAD

**Issue by CoekaertsJasper** [project-chip/certification-tool#213]
### Describe the bug

Running TC-DGGEN-2.3 using the TH yaml script, the script does not use the PIXIT.DGGEN.ENABLEKEY value. Instead the script uses the default value, leading to a constraint issue.

### Steps to reproduce the behavior

Run TC-DGGEN-2.3 using the yaml script. 

### Expected behavior

The script uses the  PIXIT.DGGEN.ENABLEKEY value and not the default value.

### Log files

[TC-DGGEN_2-3_2024_03_06_08_55_48.log](https://github.com/project-chip/certification-tool/files/14513545/TC-DGGEN_2-3_2024_03_06_08_55_48.log)

### Environment

2.10-beta3+spring2024

**Comment by David-Luooo** [comment]
You can add     "PIXIT.DGGEN.ENABLEKEY":"hex:xxxxxxxxxx..."     to  " test parameters "

**Comment by raju-apple** [comment]
@CoekaertsJasper Did adding the PIXIT value to test parameters help resolve the issue ?

**Comment by raju-apple** [comment]
@CoekaertsJasper any update ?

**Comment by fabiowmm** [comment]
Closing as the originator seems to have lost interest.
