### ISSUE TITLE
[Bug] TC-VALCC-2.1 The "TestPlanVerificationSteps" no validation step of TC-VALCC-2.1 ,TC-VALCC-2.1 tests scop in this SVE-1.3.

### ISSUE THREAD

**Issue by zhishan67** [project-chip/certification-tool#215]
### Describe the bug

The "TestPlanVerificationSteps" no validation step of TC-VALCC-2.1 ,TC-VALCC-2.1 tests scop in this SVE-1.3.And except for TC-VALCC-1.1, there is no verification step for other cases

### Expected behavior

There are verification steps for these cases

### Screenshots

![TC-VALCC-1 1](https://github.com/project-chip/certification-tool/assets/85116265/64ee031e-d79e-4c68-ac8d-9c2ffc55fcb5)

### Environment

TH Version: 2.10-beta3+spring2024

**Comment by ReneJosefsen** [comment]
These tests are scripted, so I'm of the impression that there should not be any verifications steps for these? @raju-apple is that not correct?

**Comment by CoekaertsJasper** [comment]
The script steps are available here: https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/valve_configuration_and_control.adoc

**Comment by raju-apple** [comment]
@zhishan67 yes there will only be VS steps if the test case isn't already an automated one. There is no plan to add VS steps for already automated test cases

**Comment by zhishan67** [comment]
Ok, I see. Thanks for the answer！
