### ISSUE TITLE
[TC-PWRTL-2.1] only shows up under SDK Python Test under `Python Testing Suite - Legacy` but Power Topology is a new 1.3 cluster

### ISSUE THREAD

**Issue by jamesharrow** [project-chip/certification-tool#216]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

## Summary Title: 
    [TC-PWRTL-2.1] only shows up under SDK Python Test under `Python Testing Suite - Legacy` but Power Topology is a new 1.3 cluster

## Description:
    The test script was hard to find since it only shows up under `Python Testing Suite - Legacy` - we were expecting it to show up under `Python Testing Suite`.

## Steps to reproduce:
    1. On the test harness  - click on the SDK Python Tests, In the search box type `PWRTL` 
    2. Observe that the test case is only found if you click on the `Python Testing Suite - Legacy` in the bottom part of the screen

## Logs:
  N/A
  
## Additional Info:
  Note Power Topology Cluster is new cluster in 1.3 -so not expecting this to be under Legacy.

**Comment by rquidute** [comment]
Hi @jamesharrow Legacy suite refers to the test case that are not written in the expected template, even this test being a new one.

**Comment by raju-apple** [comment]
@fabiowmm lets re-word the categories to avoid confusion
