### ISSUE TITLE
[TC-IDM-1.4] After the completion of TC-IDM-1.4 test, Test Haness cannot exit the test state and is always in PENDING state. 

### ISSUE THREAD

**Issue by peck-bv** [project-chip/certification-tool#218]
## Summary Title: 
    [SVE1.3] Test Harness the test step is complete, but the test script cannot exit the test. 

## Description:
    [TC-IDM-1.4] After the completion of TC-IDM-1.4 test, Test Haness cannot exit the test state and is always in PENDING state. 
![Snipaste_2024-03-06_09-52-38](https://github.com/project-chip/matter-test-scripts/assets/128341436/915664ce-eb7f-43c4-9e50-4054e54d46d4)

    Use the docker ps command to view the running docker container, at which point the permitted script container th-sdk has stopped working.
![Snipaste_2024-03-06_09-57-10](https://github.com/project-chip/matter-test-scripts/assets/128341436/ce84925b-e38a-451b-8c8c-bf1ceb3cf875)

## Steps to reproduce:
    Test IDM-1.4 properly on the Test Harness platform

## Logs:
    
[IDM-1-4_2024_03_06_09_49_26.log](https://github.com/project-chip/matter-test-scripts/files/14503590/IDM-1-4_2024_03_06_09_49_26.log)

## Additional Info:
    The "TestPlanVerificationSteps" no validation step of TC-IDM-1.4. TC-IDM-1.4 tests scop in this SVE-1.3.
![image (1)](https://github.com/project-chip/matter-test-scripts/assets/128341436/da17a7e0-087d-4b41-b7ec-e91523f7f3c6)

**Comment by XingyuWu123** [comment]
TC-EPM-2.1 has the same problem
![微信图片_20240309094753](https://github.com/project-chip/certification-tool/assets/162408485/8db99870-86fa-4273-a720-3085ab729e36)
[_TC-EPM-2_1_2024_03_08_11_04_16.log](https://github.com/project-chip/certification-tool/files/14544573/_TC-EPM-2_1_2024_03_08_11_04_16.log)

**Comment by rquidute** [comment]
Hi @peck-bv, there is an update in the release branch. Could you check if the changes works for you?
Could you please follow the steps bellow in order to update the release branch and test again?

- ./scripts/stop.sh
- cd certification-tool
- git fetch
- git checkout v2.10-beta3+spring2024
- git submodule update --init --recursive
- ./scripts/start.sh

**Comment by fabiowmm** [comment]
Originator seems to have lost interest.
