### ISSUE TITLE
Investigate the possibility of switching SDK simulated apps between test steps in the same test case

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#22]
From chip-certification-tool created by [fabiowmm](https://github.com/fabiowmm): CHIP-Specifications/chip-certification-tool#684  

Some test cases specify application nodes with different capabilities at different test steps. Is it possible to have the TH backend to launch different simulated apps at different steps of the test? Can we recommission in the middle of a test case execution? Can we keep the same commissioning state between apps? Do we need SDK changes?

**Comment by fabiowmm** [comment]
@raju-apple I believe this was originally raised by Sachin, but I'm not sure we really want it...
