### ISSUE TITLE
[Bug] TC-IDM-10.2, TC-IDM-10.3 failed on Evse device

### ISSUE THREAD

**Issue by Jerry-ESP** [project-chip/certification-tool#222]
### Describe the bug

The TC-IDM-10.2 and TC-IDM-10.3 cases failed, it seems that the xml file version we used in 1.3 SVE are not fit the data model version in docker, for cluster DeviceEnergyManagement, PowerSource, 

[MatterTest] 03-11 05:21:49.191 INFO 
Problem: ProblemSeverity.ERROR
    test_name: IDM-10.2
    location: 
        Endpoint: 1,
        Cluster:  152 (0x98) DeviceEnergyManagement,
        Attribute:0 (0x00)
    problem: Standard attribute found on device, but not in spec
    spec_location: 

[MatterTest] 03-11 05:21:49.190 INFO 
Problem: ProblemSeverity.ERROR
    test_name: IDM-10.2
    location: 
        Endpoint: 0,
        Cluster:  47 (0x2f) PowerSource,
        Attribute:38 (0x26)
    problem: Attribute 0x26 is required, but is not present on the DUT. Conformance: M, implemented features: WIRED
    spec_location: 

[MatterTest] 03-11 05:31:06.243 INFO 
Problem: ProblemSeverity.ERROR
    test_name: IDM-10.3
    location: 
        Endpoint: 0,
        Cluster:  47 (0x2f) PowerSource,
        Attribute:65533 (0xfffd)
    problem: Revision found on cluster (2) does not match revision listed in the spec (3)
    spec_location: 

### Steps to reproduce the behavior

1. Test on this energy evse example:  https://github.com/project-chip/connectedhomeip/tree/master/examples/energy-management-app/esp32\
2. . testing TC-IDM-10.2 with command:    python3 TC_DeviceConformance.py --discriminator 599 --passcode 25392129 --commissioning-method ble-wifi --wifi-ssid matter1_1 --wifi-passphrase espressif --int-arg use_pase_only:0 --storage-path admin_storage.json --tests test_TC_IDM_10_2 --paa-trust-store-path /credentials/development/paa-root-certs/
3. testing TC-IDM-10.2 with command:   python3 TC_DeviceConformance.py --discriminator 599 --passcode 25392129 --commissioning-method ble-wifi --wifi-ssid matter1_1 --wifi-passphrase espressif --int-arg use_pase_only:0 --storage-path admin_storage.json --tests test_TC_IDM_10_3 --paa-trust-store-path /credentials/development/paa-root-certs/

### Expected behavior

pass

### Log files

[TC-IDM-10.2_fail_311.txt](https://github.com/project-chip/certification-tool/files/14554367/TC-IDM-10.2_fail_311.txt)
[TC_IDM_10.3_fail_0311.txt](https://github.com/project-chip/certification-tool/files/14554370/TC_IDM_10.3_fail_0311.txt)

### PICS file

[PICS.zip](https://github.com/project-chip/certification-tool/files/14554590/PICS.zip)

### Environment

matter1.3 SVE

**Comment by Jerry-ESP** [comment]
I notice that the Network commissioning cluster [issue](https://github.com/project-chip/matter-test-scripts/issues/202) and Power Source cluster [issue](https://github.com/project-chip/matter-test-scripts/issues/194) had been raised, so please just check the DeviceEnergyManagement cluster, tnanks.

**Comment by raju-apple** [comment]
@Jerry-ESP can you check if the resolution in https://github.com/project-chip/matter-test-scripts/issues/202 helped you as well ?

**Comment by Jerry-ESP** [comment]
> @Jerry-ESP can you check if the resolution in [project-chip/matter-test-scripts#202](https://github.com/project-chip/matter-test-scripts/issues/202) helped you as well ?

Thanks for your reply, yes, this [PR](https://github.com/project-chip/connectedhomeip/pull/32305) can resolve the Network commissioning cluster issue,  but not for the DeviceEnergyManagement cluster and PowerSource cluster.

**Comment by fabiowmm** [comment]
@Jerry-ESP are you still facing this issue?
