### ISSUE TITLE
[TC-MWOCTRL-2.2] PICS Tool v2.1.6 does not display test items correctly.

### ISSUE THREAD

**Issue by ZeddChen** [project-chip/certification-tool#224]
### Describe the bug

When MWOCTRL.S==1 && MWOCTRL.S.F00==1 && MWOCTRL.S.F02==0, the test case TC-MWOCTRL-2.2  should be test, but not show test item correctly.
![image](https://github.com/project-chip/certification-tool/assets/109862523/6a921f67-742d-4636-a3a5-48df5255f9b1)
![image](https://github.com/project-chip/certification-tool/assets/109862523/f77a683d-f700-4a6c-bbca-70c5ab3a1a20)

**Comment by raju-apple** [comment]
@raul-marquez-csa Can you please sync up with agustin and ask him to take a look into this issue please ? Somehow i cannot assign issues to Agustin as he is not in this project in github .

**Comment by hiltonlima** [comment]
Hello @ZeddChen,
If you don't have any related problems, could you close the issue?
