### ISSUE TITLE
[Bug] Custom test suites have inconsistent names

### ISSUE THREAD

**Issue by ccruzagralopes** [project-chip/certification-tool#229]
### Describe the bug

The test suites for custom test cases (both from Custom YAML Tests and Custom SDK Python Tests) have inconsistent names. They have a "-custom" suffix during the test execution, but that doesn't appear during the test case selection.

### Steps to reproduce the behavior

1. Create custom YAML and Python test cases
2. Run TH
3. Select the custom test cases
4. Verify that the suites for the custom collections don't have a "-custom" suffix
5. Run test cases
6. Verify that the test execution view shows a "-custom" suffix in the name of the test suites for the custom test cases

### Expected behavior

Expected the suite name to be the same in both views

### Log files

N/A

### PICS file

N/A

### Screenshots

<img width="2049" alt="Screenshot 2024-03-14 at 13 32 02" src="https://github.com/project-chip/certification-tool/assets/116589288/4af15a50-4421-4557-84b4-633a79694f14">
<img width="2048" alt="Screenshot 2024-03-14 at 13 38 26" src="https://github.com/project-chip/certification-tool/assets/116589288/7ecab76d-57c8-4405-be06-c4485a52188d">
<img width="2048" alt="Screenshot 2024-03-14 at 14 09 53" src="https://github.com/project-chip/certification-tool/assets/116589288/1555545d-e79d-432f-8f99-83a0fb2d1a22">
<img width="2048" alt="Screenshot 2024-03-14 at 14 13 00" src="https://github.com/project-chip/certification-tool/assets/116589288/2986c8c5-b8f6-498d-bdee-e9407af46f04">

### Environment

- TH version: `main` branch
- OS: Ubuntu 22.04.3 LTS
- Browser: Safari 16.4

**Comment by fabiowmm** [comment]
@ccruzagralopes is this fixed?
