### ISSUE TITLE
Add SDK SHA also to TH UI

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#23]
From chip-certification-tool created by [raju-apple](https://github.com/raju-apple): CHIP-Specifications/chip-certification-tool#724  

Request to add the SDK SHA also in the TH UI

**Comment by raju-apple** [comment]
@raju-apple,
Currently, the "version" and "SHA" (Backend SHA) version displayed in the UI are obtained from the endpoint `/api/v1/version` , for adding SDK SHA in UI nav bar this backend endpoint needs to be updated to include the same.

**Comment by raju-apple** [comment]
@fabiowmm FYI ^^

**Comment by fabiowmm** [comment]
Duplicate of #233
