### ISSUE TITLE
[Bug] Dependency issue apt-transport-https 2.4.11 on fresh 1.3 TH (beta) fails auto-install script

### ISSUE THREAD

**Issue by sander-gitl** [project-chip/certification-tool#249]
### Describe the bug

Dependency issue apt-transport-https 2.4.11 on fresh 1.3 TH (beta) install.
Error that appears upon running the auto-install.sh script:
_"The following packages have unmet dependencies:
 satisfy:command-line : Depends: apt-transport-https (= 2.4.11)
E: Unable to correct problems, you have held broken packages."_ 
And installation is stopped.

### Steps to reproduce the behavior

* Follow the instructions per https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc r[fe92369](https://github.com/project-chip/certification-tool/commit/fe92369fe5e2fd1d787a82f6e64ae1d8e1672e1c) chapter 4.1
* Run"$./scripts/pi-setup/auto-install.sh" 

### Expected behavior

The installation completes successfully, installing all required packages for Ubuntu Server 22.04-LTS

### Log files

TH script auto-install.sh:
```
$ ./scripts/ubuntu/auto-install.sh
+++ dirname ./scripts/ubuntu/auto-install.sh
++ realpath ./scripts/ubuntu/../..
+ ROOT_DIR=/home/ubuntu/certification-tool
+ SCRIPT_DIR=/home/ubuntu/certification-tool/scripts
+ UBUNTU_SCRIPT_DIR=/home/ubuntu/certification-tool/scripts/ubuntu
+ printf '\n\n**********'


**********+ printf '\n*** Installing Dependencies ***\n'

*** Installing Dependencies ***
+ /home/ubuntu/certification-tool/scripts/ubuntu/1-install-dependendcies.sh
Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# Instaling package: apt-transport-https (=2.4.11)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 satisfy:command-line : Depends: apt-transport-https (= 2.4.11)
E: Unable to correct problems, you have held broken packages.
+ printf '\n\n**********'
```

### Environment

TH version v2.10-beta3+spring2024

### Additional Information

The 2.4.11 apt-transport-https package is no longer available, the latest is 2.4.12. :
$sudo apt-get install  apt-transport-https=2.4.11
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package apt-transport-https is a virtual package provided by:
  apt 2.4.12 (= 2.4.12)
You should explicitly select one to install.

**Comment by hiltonlima** [comment]
This problem has been resolved in the new version. Please update to version: `v2.10+spring2024`

**Comment by sander-gitl** [comment]
https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc still references to Beta, otherwise all good
