### ISSUE TITLE
[1.2 TE1] [TC-G-1.1]Test Harness fails to auto pair with a wifi-ble accessory.

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#25]
From chip-certification-tool created by [mideayanghui](https://github.com/mideayanghui): CHIP-Specifications/chip-certification-tool#865  

## Description:
   Click the Start to test, then fail to pair with accessory

## Steps to reproduce:
   Click the Start to test, then fail to pair with accessory

## Logs:
    Test Harness logs :
[[TC-G-1.1]_[LQGd6XEO]_TH_log.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11685412/TC-G-1.1._.LQGd6XEO._TH_log.log)

    DUT logs:
[[TC-G-1.1]_[LQGd6XEO]_DUT_log.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11685414/TC-G-1.1._.LQGd6XEO._DUT_log.log)

## Additional Info:
  Spec version: 2023 Fall 0.7
  PICS: v1.8
  PICS
[Groups Cluster Test Plan XML.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/11685440/Groups.Cluster.Test.Plan.XML.zip)

https://github.com/CHIP-Specifications/chip-certification-tool.git
commit 68548cb, I have updated TH using cmd.

**Comment by raju-apple** [comment]
If I use interactive mode in cmd, it also fail
Test Harness logs :
[[Test]_[LQGd6XEO]_CHIPTool_log.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11685882/Test._.LQGd6XEO._CHIPTool_log.log)

DUT logs:
[COM7_2023-06-08_16-34-16-DUT.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11685883/COM7_2023-06-08_16-34-16-DUT.log)


But if I use ./chip-tool pairing ble-wifi 0x1 smart-US xxxx 23589077 901 --paa-trust-store-path /var/paa-root-certs/,
commission successfully

**Comment by raju-apple** [comment]
@mideayanghui  Both failures seems to be related to Bluetooth disconnection.

Is this recurrent on sequentially  executing manual interactive chip-tool tests?  

Could you provide  2 or 3 logs of sequential failures (chip-tool manually in interactive mode )

**Comment by raju-apple** [comment]
> @mideayanghui Both failures seems to be related to Bluetooth disconnection.
> 
> Is this recurrent on sequentially executing manual interactive chip-tool tests?
> 
> Could you provide 2 or 3 logs of sequential failures (chip-tool manually in interactive mode )
Yes, I try serveral time, it also fail.   I make sure I have update the TH to the latest version using command.
cd ~/chip-certification-tool
git pull
git checkout release/2.9-TE1
git submodule update --init --recursive
./scripts/update.sh
./scripts/ubuntu/update-sample-apps.sh
./scripts/ubuntu/update-paa-certs.sh
./scripts/stop.sh
./scripts/build-no-cache.sh
./scripts/start.sh
[chiptool-interactive-pairing fail.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/11704992/chiptool-interactive-pairing.fail.txt)

**Comment by fabiowmm** [comment]
@gladystonfranca please add here the SDK issue you have opened to fix this.
