### ISSUE TITLE
[Bug] Ble-thread Pairing is failed in automated yaml script.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#250]
### Describe the bug

Ble-Thread pairing is failed  with the below error during the commissioning

> Test Suite Error: Error occurred during setup of test suite.FirstChipToolSuite. Border router does not start properly for nrfconnect/otbr:9185bda

### Steps to reproduce the behavior

1. Edit the pairing_mode to ble-thread in Project config.
2. Select the test case from SDK yaml Tests
3. Advertise the DUT 
4. Run the test-case

### Log files

[dgthread.log](https://github.com/project-chip/certification-tool/files/15025288/dgthread.log)

### PICS file

[Thread Network Diagnostics Cluster Test Plan.zip](https://github.com/project-chip/certification-tool/files/15025301/Thread.Network.Diagnostics.Cluster.Test.Plan.zip)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/104007654/4ccb95dd-16ca-48f4-9e61-3ff4bd79520d)

### Environment

TH version :2.10+spring2024
Sha: 5f28838

**Note:**  Python and Manual way of ble-thread pairing is working fine only issue with  yaml automated script

**Comment by hiltonlima** [comment]
I believe we resolved this issue by rewriting the RCP board firmware. Could you please confirm that you no longer have the problem?
