### ISSUE TITLE
Yaml files location has to be updated in TH user guide

### ISSUE THREAD

**Issue by Survensa** [project-chip/certification-tool#259]
### Describe the bug

The location `~/certification-tool/backend/test_collections/sdk_tests/sdk_checkout/yaml_tests/yaml/sdk/` has to be updated with `~/certification-tool/backend/test_collections/matter/sdk_tests/sdk_checkout/yaml_tests/yaml/sdk` in [Updating Existing Yaml Test Script](https://github.com/project-chip/certification-tool/blob/v2.10%2Bspring2024/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#updating-existing-yaml-test-script) and [Customized Test Scripts (Yaml/Python Tests)](https://github.com/project-chip/certification-tool/blob/v2.10%2Bspring2024/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#customized-test-scripts-yamlpython-tests)

https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#46-customized-test-scripts-yamlpython-tests

**Comment by antonio-amjr** [comment]
Hi @Survensa,

Those location seems updated already in the `fall2024` release branch.
I think It's just matter of merging it into the main later when ready.

Is it ok to wait for the release or should we push right away this change to `main`?
