### ISSUE TITLE
[Bug] - TH user guide links to CSG area iso all-members

### ISSUE THREAD

**Issue by sander-gitl** [project-chip/certification-tool#264]
### Describe the bug

Member reported that in the TH user guide the links are to the CSG instead of the all-members area, which makes some resources not accessible to all members (folder https://groups.csa-iot.org/wg/members-all/document/folder/3661 for Matter 1.3 etc.)

Example link to the PICS files : https://groups.csa-iot.org/wg/matter-csg/document/26122 instead of https://groups.csa-iot.org/wg/members-all/document/31907 

### Expected behavior

All links in the TH User Guide must refer to links that are accessible to as wide a user audience as possible based on the availability of the resource (XML files are accessible to all members -> link to the Causeway area etc.)

**Comment by antonio-amjr** [comment]
The `fall2024` with the mentioned change above was merged into the `main` branch.
Since all the process is done I'll close this up now.

Feel free to open again if another details or link from the User Guide need to be updated.
