### ISSUE TITLE
[TC-OO-3.2] How to run Simulated Test?

### ISSUE THREAD

**Issue by Yinxq** [project-chip/certification-tool#267]
### Describe the bug

I'm testing the switch app. In Simulated Test TC-OO-3.2, you need to commssion the DUT to TH, and then issue a command like on/off to pass the test. However, the parameters required for commissioning are not given in the step, and there is no bind operation for DUT and other device, so I don't know who to send the onoff command to.

May I ask if the Simulated Test is just a reference for us and we don't need to actually test it with TH?

### Screenshots

![OO_3 2](https://github.com/project-chip/certification-tool/assets/56418025/9bac49b0-94bc-43b6-b1c8-f0b6af6d13ce)

### Environment

TH Fall2023

**Comment by antonio-amjr** [comment]
Hi @Yinxq,

It's possible to run the simulated tests, so I'll provide you here a step by step for `TC-OO-3.2` to clarify an execution in practice.

So, first thing is to start two ubuntu terminals:
1. In the **Terminal1** you may start a app of your choice, like the `chip-all-clusters-app` for example
2. In the **Terminal2** we will issue DUT commands using the `chip-tool`, available in the **~/apps/chip-tool**

So, in the Terminal2 for the `TC-OO-3.2`, we'll have the steps:
- ./chip-tool pairing code 1 MT:-24J0AFN00KA0648G00
- ./chip-tool onoff off 1 1
- ./chip-tool onoff on 1 1
- ./chip-tool onoff toggle 1 1
- ./chip-tool onoff off-with-effect 1 0 1 1
- ./chip-tool onoff on-with-recall-global-scene 1 1
- ./chip-tool onoff on-with-timed-off 0 120 5 1 1
- ./chip-tool pairing unpair 1
Just a reminder that every step will need to be manually verified if it was a success or not.

Let me know if this helps.

**Comment by ccruzagralopes** [comment]
There has been no answer in a while, so closing the issue. If the problem persists, please feel free to reopen it or create a new one
