### ISSUE TITLE
[Bug] TC_IDM_1_2 and TC_OPCRED_3_1 failing when TH is connected over wlan

### ISSUE THREAD

**Issue by chirag-silabs** [project-chip/certification-tool#271]
### Describe the bug

The docker test cases TC_IDM_1_2 and TC_OPCREDS_3_1 fails when the TH is connected over WLAN but passes when the device is connected over Ethernet LAN. 

Failure when connected over WLAN
[TC_IDM_1_2-different-ap.log](https://github.com/project-chip/certification-tool/files/15500743/TC_IDM_1_2-different-ap.log)
[write_default_logs_DUT.txt](https://github.com/project-chip/certification-tool/files/15500746/write_default_logs_DUT.txt)

Passed when connected over Ethernet
[tc_idm_1_2_ethernet.txt](https://github.com/project-chip/certification-tool/files/15500800/tc_idm_1_2_ethernet.txt)

### Steps to reproduce the behavior

Just running TC_IDM_1_2 in docker while TH connected over wlan

### Expected behavior

Pass on the docker automation case

**Comment by antonio-amjr** [comment]
Hey @cecille,

Can you help with this issue? It's a DNS-SD resolution timeout.
Since it's calling the TC_IDM_1_2 script directly, maybe it's something from the SDK's side.

**Comment by cecille** [comment]
DNS-SD resolution timeout when connected over a different interface sounds like a genuine failure, possibly related to networking.

**Comment by chirag-silabs** [comment]
@fabiowmm we have tested it on 2 setups, seen the same behavior. 
connecting the pi over ethernet works fine always but seeing a issue when it is connected on WLAN. Could be related to docker networking? 
I can share the details of my setup if needed

**Comment by antonio-amjr** [comment]
Hi @chirag-silabs,

Please do share more details of the setup and any additional information, like the project configuration.
Also, share as well the output of the following:
- `$ ./certification-tool/scripts/th/th-doctor.sh --complete`
- `$ docker ps`
- `$ docker images`
- `$ docker network inspect chip-default`
- `$ docker network inspect certification-tool_traefik-public`

We'll see if we spot anything.

**Comment by chirag-silabs** [comment]
Here you go with the output of the  above commanders

[th_docker_issue.txt](https://github.com/user-attachments/files/15799040/th_docker_issue.txt)

**Comment by cecille** [comment]
Any chance you could grab a packet capture? It looks like the TH is attempting a connection, but not seeing a response from the dut. There are a number of wifi related issues that could cause this. These tests expect that all addresses advertised are reachable.

**Comment by chirag-silabs** [comment]
Sure let me capture the packets and share

**Comment by hiltonlima** [comment]
Please test with branch `v2.11-beta3.1+fall2024`.

Please re-open this issue if needed.
