### ISSUE TITLE
 [Bug] Follow Matter_TH_User_Guide.adoc when I run ./scripts/start.sh it show service "backend" is not running

### ISSUE THREAD

**Issue by xiaojianjian92** [project-chip/certification-tool#274]
### Describe the bug

I follow Matter_TH_User_Guide.adoc Install TH environment,when everything is done, run ./scripts/start.sh, it say service "backend" is not running
Even if start the container manually, it will automatically exit after a period of time.
![image](https://github.com/project-chip/certification-tool/assets/92834656/56bb670d-6828-4f8d-aa0d-eec36d7447aa)

### Steps to reproduce the behavior

docker ps -a

./scripts/start.sh

docker ps -a

### Expected behavior

backend run succeed and Web can access

### Log files

[backend not running.log](https://github.com/user-attachments/files/15545329/backend.not.running.log)
whole log is here
[matter_th_backend_exit.log](https://github.com/user-attachments/files/15577240/matter_th_backend_exit.log)

**Comment by antonio-amjr** [comment]
Hi @xiaojianjian92,

It seems you're trying to install the `main` branch, as I noticed by the logs you've shared.
Can you try to install the current stable release?

You may clone directly in the branch as:
`$ git clone -b v2.10+spring2024 https://github.com/project-chip/certification-tool.git`
Or just checkout to the `v2.10+spring2024`.

Then the rest is similar:
- `$ git pull`
- `$ git submodule update --init --recursive`
- `$ ./scripts/pi-setup/auto-install.sh`

Let me know if that helps.

**Comment by xiaojianjian92** [comment]
It works when I checkcout to v2.10+spring2024. But I'm still confused as to why the main branch failed. It seems like missing dependencies when installing

**Comment by antonio-amjr** [comment]
> It works when I checkcout to v2.10+spring2024. But I'm still confused as to why the main branch failed. It seems like missing dependencies when installing

Great that the v2.10+spring2024 worked out. 

About the `main` branch, it has indeed some known issues with dependencies and more but they were addressed already and it'll be upgraded really soon. The [PR#278](https://github.com/project-chip/certification-tool/pull/278) should enter this week still.

**Comment by JonathanHahn** [comment]
@antonio-amjr I'm seeing the same issue with the backend not running when I'm using the branch that points to the latest release. (`v2.10.1+spring2024`)

**Comment by antonio-amjr** [comment]
Hi @JonathanHahn 

That's odd, let's see your case as well.
Is your case a clean install? Flashing a brand new `Ubuntu server 22.04.4` and then cloning the `v2.10.1+spring2024`?

Please share all information relevant about your installation as well:
- `$ ./scripts/th/th-doctor.sh --complete`
- All the execution logs/ Shell logs

**Comment by antonio-amjr** [comment]
There's some time without feedback then I'll close this issue up.

This is an issues that happens when the TH version is upgraded and should not happen in a clean install.
Also, in the case a fix is needed without reinstalling, we may easily address the problem with the help of some logs currently.
