### ISSUE TITLE
[Bug] Error during "auto-install.sh". "Cannot install sniffio, idna and exceptiongroup"

### ISSUE THREAD

**Issue by OlivierGre** [project-chip/certification-tool#279]
### Describe the bug

I'm installing Test Harness environment for the first time.

I'm following the Test Harness user manual. 
I'm using a Raspberry Pi4 and I have installed a Ubuntu Server 22.04 LTS (64 bits) and followed the instructions. 
I have cloned this version:
 git clone -b v2.10+spring2024 https://github.com/project-chip/certification-tool.git

The "auto-install.sh" script is failing with errors:
"cannot install sniffio",
"cannot install idna",
"cannot install exceptiongroup"...

I have installed the missing modules with:
```
pip3 install sniffio
pip3 install idna
pip3 install exceptiongroup
```
but I'm still getting the same errors :(

Would you have some advices?

### Steps to reproduce the behavior

git clone -b v2.10+spring2024 https://github.com/project-chip/certification-tool.git

Goto to TH folder: cd certification-tool

Initialize the submodules: git submodule update --init --recursive

Install/configure the TH dependencies: ./scripts/pi-setup/auto-install.sh

### Screenshots

![matter_TH_error](https://github.com/project-chip/certification-tool/assets/34505085/732bde98-9eb3-49ac-9add-63e6c8d08292)

### Environment

v2.10+spring2024

**Comment by hiltonlima** [comment]
Hello @OlivierGre , Thanks for your feedback. 

Could you please close this issue?
