### ISSUE TITLE
Manual test case enhancement (Frontend)

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#28]
From chip-certification-tool created by [krypton36](https://github.com/krypton36): CHIP-Specifications/chip-certification-tool#869  

## Manual test case enhancement: 
    Update the frontend to support chip-tool commands.

## Description:
    - Add REST Api to backend that hooks into chip-tool.py and allows for execution of chip-tool command.
    - Use `send_websocket_command` in chip-tool.py to forward the command execution in the chip-tool binary
    - Add Frontend interface for the user to be able to execute the chip-tool command and calling the REST API.

## Additional Notes:
- [Phase2 Branch ](https://github.com/CHIP-Specifications/chip-certification-tool-backend/compare/Phase2_WebSocket_ChipTool_Integration_Test)where the [API](https://github.com/CHIP-Specifications/chip-certification-tool-backend/compare/Phase2_WebSocket_ChipTool_Integration_Test#diff-b1f100ed391fdd98d67c96e9b0d772b8249a20a34ca092327c97377bddfd2cf3R441) is available. 

## Example Command
```python
from app.chip_tool.chip_tool import ChipTool
import asyncio
import json

async def run_chip_tool_cmd():
    chip_tool = ChipTool()
    await chip_tool.start_container()
    chip_tool_command = "onoff read on-off 1234 1"
    response = await chip_tool.send_websocket_command(chip_tool_command)
    json_payload = json.loads(response)

asyncio.run(run_chip_tool_cmd())
```

**Comment by raju-apple** [comment]
Yes @gvargas-csa

**Comment by fabiowmm** [comment]
Deprioritized.
