### ISSUE TITLE
[Bug] ETH0 not found

### ISSUE THREAD

**Issue by OlivierGre** [project-chip/certification-tool#281]
### Describe the bug

I'm following the Test Harness user manual.

I'm using a Raspberry Pi4 and I have installed a Ubuntu Server 22.04 LTS (64 bits). I have cloned this version:
git clone -b v2.10+spring2024 https://github.com/project-chip/certification-tool.git

Yesterday I have successfully run the auto-install script (I was using a Wifi connection to my smarphone). 
Then I have rebooted.

I cannot put the raspberry pi and my laptop on the same network so I have setup a direct Ethernet connection between the raspberry Pi and my laptop.

The problem is that, when I do "ifconfig", I see lot of interfaces but not ETH0 interface. How can I know which one to use?

Here are the interface shown (I'm replacing the hex numbers by XXX)
- br-XXXXX
- br-XXXXX
- docker0
- lo
- vethXXXX
- vethXXXX
- vethXXXX
- vethXXXX
- wlan0

**Comment by OlivierGre** [comment]
`ifconfig eth0`
gives the MAC address of this interface but doesn't contain ip addresses.

**Comment by OlivierGre** [comment]
Fixed with 

`sudo ifconfig eth0 up`

**Comment by OlivierGre** [comment]
Closed

**Comment by OlivierGre** [comment]
After a reboot, eth0 is down again :(
What am I doing wrong?
Thanks

**Comment by samryanuofl** [comment]
Is there an entry for eth0 in the config file in /etc/netplan?

**Comment by OlivierGre** [comment]
No, it only contains a file called "50-cloud-init.yaml"

**Comment by samryanuofl** [comment]
If you open that file it should have an entry for eth0, if not you will need to add it. The netplan docs have instructions for setting that up:

https://netplan.readthedocs.io/en/stable/examples/#

**Comment by OlivierGre** [comment]
Thank you Sam.
Finally, I'm able to access to TH Project Menu thanks to the WIFI connection so, right now, I don't need to continue the effort to get eth0 up and running.

**Comment by hiltonlima** [comment]
HELLO @OlivierGre ,

If you don't have any related problems, could you close the issue?

**Comment by OlivierGre** [comment]
No more needed. Closing
