### ISSUE TITLE
[Bug] After a fresh install of TH `v2.11-beta1+fall2024`, backend has an install failure and fails

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/certification-tool#285]
### Describe the bug

After running the install steps from Matter TH manual, TH backend has a start failure and TH frontend shows internal errors.

![image](https://github.com/project-chip/certification-tool/assets/1313847/b7829a13-66b6-4f6d-860e-03cb911b06ab)

### Steps to reproduce the behavior

- Fresh-installed a raspi4 on 22.04LTS server
- Cloned TH repos per instructions at tag `v2.11-beta1+fall2024`
- Ran `./scripts/pi-setup/auto-install.sh` to install everything

First time device failed to download some pieces and rebooted:

![image](https://github.com/project-chip/certification-tool/assets/1313847/b96c2619-3e16-4817-a27e-42f70692e602)

Then I re-ran `./scripts/pi-setup/auto-install.sh` on next boot, and it succeeded to do everything right, and I selected "1)" to reboot.

After reboot, the TH is still not working

### Expected behavior

- Running `./scripts/pi-setup/auto-install.sh` on the correct check-out against a fresh Ubuntu 22.04LTS install results in a working TH.

### Log files

- [th_doctor_logs_tennessee.txt](https://github.com/user-attachments/files/15872794/th_doctor_logs_tennessee.txt)
- [th_frontend_logs.txt](https://github.com/user-attachments/files/15872795/th_frontend_logs.txt)
- [th_backend_logs.txt](https://github.com/user-attachments/files/15872796/th_backend_logs.txt)

### Environment

- Firefox
- TH v2.11-beta1+fall2024
- Raspi 4 4GB, Ubuntu 22.04LTS Server

**Comment by hiltonlima** [comment]
Hello @tcarmelveilleux, Thanks for the feedback.

We agree with the script's suggestion. We will make it available as soon as possible.

**Comment by ccruzagralopes** [comment]
This issue seems to be resolved and another issue has been opened to track the enhancement suggestion.
