### ISSUE TITLE
[Bug] Logs are truncated in the test run view

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/certification-tool#287]
### Describe the bug

- Logs during runs are missing timestamps
- Logs during runs have all the left space padding lost (left-trimmed) which destroys the ability to look at the decoded structured data which uses indentations
- A proportional font is used with low contrast, which makes the logs very hard to read

### Steps to reproduce the behavior

1. Run a test in TH
2. Observe the logs format in the logs pane

### Expected behavior

- Log lines all have a timestamp at least <UNIX time seconds.millis> or ISO8601 time with millis
- Indentiation of original logs is maintained by not removing left padding spaces
- A monospace font is used with a good contrast between the font and background.
  - Suggest white font on black background in dark theme
  - Suggest black font on white background in light theme
  - Suggest using Roboto Mono or a similar font, and fall back to courier only if nothing else. Do not use a proportional font.

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/1313847/09a2d130-1b6c-4984-b505-c9932f60d01b)

### Environment

- TH Version: v2.11-beta1+fall2024
  - SHA: a299a9d

**Comment by tcarmelveilleux** [comment]
The dark theme has better contrast, but it still could be more contrasty.

I also noticed SOME logs have the correct format, and some others don't:

![image](https://github.com/project-chip/certification-tool/assets/1313847/9285f10d-b49a-4d5a-abf4-b0b4af92a418)

It may be based on whether it's the chip-tool runner or something else?

**Comment by hiltonlima** [comment]
Hello @tcarmelveilleux ,

Could you tell me what tests you ran to check the truncated logs?

**Comment by hiltonlima** [comment]
Logs during runs are missing timestamps
https://github.com/project-chip/connectedhomeip/issues/34017

**Comment by hiltonlima** [comment]
Logs during runs have all the left space padding lost (left-trimmed) which destroys the ability to look at the decoded structured data which uses indentations
https://github.com/project-chip/certification-tool-frontend/issues/19

**Comment by hiltonlima** [comment]
A proportional font is used with low contrast, which makes the logs very hard to read
https://github.com/project-chip/certification-tool-frontend/issues/20

**Comment by fabiowmm** [comment]
Closing as it is being tracked on the FE and SDK repos.
