### ISSUE TITLE
How to modify the default startup configuration parameters of the th-sdk container？

### ISSUE THREAD

**Issue by xiaojianjian92** [project-chip/certification-tool#289]
### Describe the bug

When I start SDK Python Tests, TH set up SDK container by default configuration just like below. But my Raspberry Pi username is not ubuntu. It can not start with correct file path like test_harness_client.py. How and where I can change configuration of th-sdk container
![image](https://github.com/project-chip/certification-tool/assets/92834656/aa8b6e3f-1c2e-4da6-b551-8027dd4c7329)

![image](https://github.com/project-chip/certification-tool/assets/92834656/399c402a-6fa4-4878-a631-9c8989823e73)

### Environment

Version: 2.10+spring2024
Sha: 5f28838

**Comment by xiaojianjian92** [comment]
I modify the sdk_container.py file and then Sending command to SDK container: python3 /root/python_testing/scripts/sdk/test_harness_client.py commission --trace-to json:log --discriminator 3840 --passcode 20202021 --commissioning-method ble-wifi --paa-trust-store-path /var/paa-root-certs/ --storage-path admin_storage.json
It show error:
error: missing --wifi-ssid for --commissioning-method ble-wifi!
![image](https://github.com/project-chip/certification-tool/assets/92834656/b0a73ae6-c546-497f-ad3c-5f6a0d5ef3de)


But I had set up network param  in project config. Pls help me find out there is something that I miss

**Comment by Kshitijjain21** [comment]
The way that I am currently doing is to update the test parameter option in the project config. No sure if there is alternate method to do this.
```
 "test_parameters": {
      "wifi-ssid": "MY-SSID",
      "wifi-passphrase": "MY-PASSWORD",
    }
```

**Comment by hiltonlima** [comment]
Hello @xiaojianjian92 ,

Thanks for your feedback.

About the username: It is mandatory that the username is ubuntu. We will make this clearer in the documentation.
About the Wifi parameters, we need to make a correction so that they can be sent.

Your solution proposed by @Kshitijjain21 can be used until the correction is made available.
