### ISSUE TITLE
[Bug] v2.10+spring2024 branch was moved to the releases folder, TH User Guide mismatch

### ISSUE THREAD

**Issue by raul-marquez-csa** [project-chip/certification-tool#291]
### Describe the bug

[Bug] v2.10+spring2024 branch was moved to the releases folder, TH User Guide mismatch

The TH user guide specifies the fdsfds branch as the one to clone, if used in the clone command it returns an error, but if releases/ is prepended it works.

The TH user guide doesn't specify the releases folder.

TH User Guide
https://github.com/project-chip/certification-tool/blob/releases/v2.10%2Bspring2024/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc

Current branches
https://github.com/project-chip/certification-tool/branches

**Comment by hiltonlima** [comment]
Thanks for the feedback.

The branch name has now been restored.

**Comment by ccruzagralopes** [comment]
@raul-marquez-csa can this be closed?
