### ISSUE TITLE
[Bug] Whether the test can be executed or not depends on the xml file.

### ISSUE THREAD

**Issue by HirokiOgawa1129** [project-chip/certification-tool#299]
### Describe the bug

Test plans created with XML of XML_version Master-V_24_SVE_1.2 cannot be tested, but test plans created with XML_version Master-V13 can be tested.
I used on-off cluster.xml.

### Log files

TH Fail Logs
[UI_Test_Run_2024_06_21_12_26_56.log](https://github.com/user-attachments/files/15922566/UI_Test_Run_2024_06_21_12_26_56.log)

### PICS file

[On-Off Cluster Test Plan_version_master_-v13.txt](https://github.com/user-attachments/files/15922503/On-Off.Cluster.Test.Plan_version_master_-v13.txt)
[On-Off Cluster Test Plan_XML_version master V_24_SVE_1.2.txt](https://github.com/user-attachments/files/15922504/On-Off.Cluster.Test.Plan_XML_version.master.V_24_SVE_1.2.txt)

I changed the extension to txt for uploading.

### Environment

TH version: TH Fall2023 Hadware:Raspberrypi 4
OS: Ubuntu 22.04 LTS
DUT FW:nordic Light

### Additional Information

Project Config
"config": {
"network": {
"wifi": {
"ssid": "testharness",
"password": "wifi-password"
},
"thread": {
"rcp_serial_path": "/dev/ttyACM0",
"rcp_baudrate": 115200,
"on_mesh_prefix": "fd11:22::/64",
"network_interface": "eth0",
"dataset": {
"channel": "15",
"panid": "0x1234",
"extpanid": "1111111122222222",
"networkkey": "00112233445566778899aabbccddeeff",
"networkname": "DEMO"
},
"otbr_docker_image": null
}
},
"dut_config": {
"discriminator": "3840",
"setup_code": "20202021",
"pairing_mode": "ble-thread",
"chip_tool_timeout": null,
"chip_tool_use_paa_certs": false
},
"test_parameters": {
"endpoint": 1
}

**Comment by hiltonlima** [comment]
Hello, @HirokiOgawa1129.

Thanks for the feedback. Looking at the log I noticed that you are using an old version of TH. Could you update to version `v2.10+spring2024` and check if the problem still occurs?

**Comment by hiltonlima** [comment]
User guide: https://github.com/project-chip/certification-tool/blob/main/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#fresh_install

**Comment by hiltonlima** [comment]
Current XML: https://groups.csa-iot.org/document/31907

**Comment by HirokiOgawa1129** [comment]
[UI_Test_Run_2024_06_24_05_39_28.log](https://github.com/user-attachments/files/15951211/UI_Test_Run_2024_06_24_05_39_28.log)
I updated it but could not commission it.

**Comment by HirokiOgawa1129** [comment]
sorry.
This was a configuration error in this project. xml files are not involved. It's just that the pairing mode was not set properly.
solved.
