### ISSUE TITLE
[TC-CC-6-x] Failing when we set OnOffTransitionTime to non-zero

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#30]
From chip-certification-tool created by [pankore](https://github.com/pankore): CHIP-Specifications/chip-certification-tool#871  

TC-CC-6.1, TC-CC-6.2 usually pass when we set OnOffTransitionTime to zero.
However, some devices might set this attribute to non-zero, which will cause it to fail at the last part.

Last part: 
- Set off command, but DUT delays due to non-zero OnOffTransitionTime
- TH reads OnOff value, sees that it is still on => fail
- After OnOffTransitionTime pass, DUT set to off

How should we handle this in this scenario?

**Comment by raju-apple** [comment]
Add a delay step after the set OFF command? The problem is this delay would be fixed, not configurable. Not sure if PIXIT will solve that.

**Comment by raju-apple** [comment]
@pankore @fabiowmm Added a delay step with configurable wait seconds in PR [27521](https://github.com/project-chip/connectedhomeip/pull/27521) please verify it and let me know your comments.

**Comment by fabiowmm** [comment]
@pankore apparently is not in the organization.
