### ISSUE TITLE
[Feature] [Frontend] TH UI Support to certification mode

### ISSUE THREAD

**Issue by rquidute** [project-chip/certification-tool#302]
### Goal
Allow TH to perform the test run execution in a new mode called `certification`. The user must be able to choose in TH UI	 if the test run execution is a certification or not. 
The execution in certification mode, the user is NOT able to select the test cases. All applicable test cases retuned by GET `api/v1/projects/{id}/applicable_test_cases` must be executed.

### Endpoint Update
**POST** `/api/v1/test_run_executions/`  has now a new optional parameter called `certification_mode` which default value is False. This endpoint will return the testcase in the correct order of the execution and this must be reflected in the UI.
For instance, if the user wants to start a new test run execution, the endpoint call should look like this: **POST** `api/v1/test_run_executions/?certification_mode=true`. 
In addition, it would be good to highlight the certification runs in the test run UI screen.

### Use Cases

[UC1] User want to perform a new certification mode, so it would be possible to check in the UI that the execution will performed in certification mode.

[UC2] In the test run execution, after user select the project, the user should be able to see all execution and the certification mode execution should be highlighted

**Comment by raul-marquez-csa** [comment]
If I select a PICS file the endpoint `api/v1/projects/{id}/applicable_test_cases` will return a list of test cases, if no PICS selected, it return an empty list.

Is this what is meant by this statement?

> All applicable test cases retuned by GET api/v1/projects/{id}/applicable_test_cases must be executed.

Or is the TH meant to provide some mandatory test cases regardless of PICS selection?
