### ISSUE TITLE
[Feature] Support for test step names lazy evaluation 

### ISSUE THREAD

**Issue by hiltonlima** [project-chip/certification-tool#306]
### Feature description

The processing of step names in a Python SDK test can only be evaluated when starting the test. Therefore, we need the Frontend to dynamically update the information on the test execution screen.

Backend PR: https://github.com/project-chip/certification-tool-backend/pull/106

0 - Go to `certification-tool` folder and stop the TH execution `./scripts/stop.sh`;
1 - Checkout branch `fall2024` on `certification-tool` repo;
2 - Go to `backend` folder and checkout the `lazy_evaluation_test_step_names` branch;
3 - Go to `certification-tool` folder;
4 - Start the TH execution for backend development `./scripts/start.sh -b`;
5 - Try to run any SDK python test.

### Use Cases

Any SDK Python test

**Comment by fabiowmm** [comment]
This is no longer needed.
