### ISSUE TITLE
[Bug] DUT failed to perform commissioning step 24 

### ISSUE THREAD

**Issue by dylanrrmcguire119** [project-chip/certification-tool#316]
### Describe the bug

Recently updated my test harness to use the v2.10.1+spring2024 branch of the project. Since then have been unable to connect to my DUT utilizing the chip tool commands, always fail with the error:

` Error on commissioning step 'ThreadNetworkSetup': 'src/controller/CHIPDeviceController.cpp:2448: CHIP Error 0x000000AC: Internal error'`

### Steps to reproduce the behavior

Run the command:

`./chip-tool pairing ble-thread 1 hex:0e08000000000001000035060004001fffe00708fd0a2c2e3157f522041051a184f7cd8a9df2cfe847b51e6f1d2c0c0402a0f7f8000300001901025b3502085b35dead5b35beef030435623335051000112233445566778899aabbccddeeff 97833935 2449 --trace_decode 1 --paa-trust-store-path /var/paa-root-certs/`

### Log files

Full log output.
[Cant_commision_bug.txt](https://github.com/user-attachments/files/16338821/Cant_commision_bug.txt)

### Environment

Rasperry Pi 4 running Ubuntu Server 22.04 LTS (64-bit) 
v2.10.1+spring2024 branch of the certification tool project
nRF52840 dongle connected to the raspberry pi

DUT is a custom PCB utilizing the nRF52840 SOC 

### Additional Information

This is probably a duplicate of [this issue](https://github.com/project-chip/certification-tool/issues/304) but am not certain so adding in more information. 

Previously, I had been able to connect to my PCB via the chip tool commands with no issue, only started having this problem when I updated to the latest released branch of the project. 

An interesting tidbit of information is that a co-worker is able to commission the same device without issue. The difference with his setup is that he upgraded earlier than I did and so his certification tool folder is on commit [1788152d3fada9e45f525c0e4c4fd715c3500ff4](https://github.com/project-chip/certification-tool/commit/1788152d3fada9e45f525c0e4c4fd715c3500ff4) which lists as the HEAD -> v1.3-TE1, origin/v1.3-TE1 branch when he runs `git show`. 

I attempted to checkout that specific commit by: 

1. Cloning the certification tool repository with `git clone https://github.com/project-chip/certification-tool.git`
2. `git checkout 1788152d3fada9e45f525c0e4c4fd715c3500ff4`
3. Running the auto install script `./certification-tool/scripts/pi-setup/auto-install.sh` 

Doing that failed to grab the necessary apps folder so I ultimately wasn't able to attempt to run the chiptool script.

**Comment by hiltonlima** [comment]
Hello @dylanrrmcguire119,

Are you able to run this script? 
`./scripts/OTBR/otbr_start.sh`

If you can start successfully, try commissioning using the command.
If possible, collect logs of the steps you take.

The result of this script may also help in the investigation:
`./scripts/th/th-doctor.sh --complete`

**Comment by dylanrrmcguire119** [comment]
After rebooting my raspberry pi, running the command `docker ps` outputs:

![image](https://github.com/user-attachments/assets/bd33ca5c-9119-42e6-a5dc-8c035b2e4581)

So the front and back end containers appear to be starting up without issue. Running the otbr start script similarly seems to have no issues. 

![image](https://github.com/user-attachments/assets/47c0d155-bb35-4a74-9fd3-f08d13882e03)

Now running the command:

`./chip-tool pairing ble-thread 1 hex:0e08000000000001000035060004001fffe00708fddda80951f995c20410acd26331883dda5b361e20cc0da3a1c00c0402a0f7f8000300001901025b3502085b35dead5b35beef030435623335051000112233445566778899aabbccddeeff 97833935 2449 --trace_decode 1 --paa-trust-store-path /var/paa-root-certs/`

Produces the following output (which matches the logs in my original comment). 

[second_try.txt](https://github.com/user-attachments/files/16352388/second_try.txt)

Running the th doctor script produces the following output: 

[test_harness_doctor.txt](https://github.com/user-attachments/files/16352477/test_harness_doctor.txt)

Maybe some interesting things of note from that output: The certification tool cli, backend, and frontend commit SHA's match what I see listed on v2.10.1+spring2024 branch of the certification tool project so that seems correct to me. The eth0 interface is down (my raspberry pi is connected directly to my router) but the wlan0 interface is up. Not sure if that is an issue but is something I noticed, for clarity I am SSH'd into this raspberry pi. 

Attempting to re-run the chip tool pairing command after running the test harness doctor script resulted in the same failure as all the other attempts. 

A final interesting thing. When I ran the test harness doctor script I also noticed that the DUT section of the output does not match what is configured via the test harness tool itself. 

![image](https://github.com/user-attachments/assets/80608104-4c3c-465f-918b-ffb47eacc08f)

![image](https://github.com/user-attachments/assets/9c827971-9a07-4d69-a005-07dc6487b36c)

I feel like this shouldn't matter since I am using the chip tool commands and not the test harness itself but thought I should point that out.

**Comment by dylanrrmcguire119** [comment]
@hiltonlima @antonio-amjr 

I had my co-worker clone his raspberry pi image and the chiptool commands now work for me as expected. Ran the test harness doctor script and received the following output. 

You can see the commits for the cert tool, frontend, backend, and cli submodules so definitely seems like some bug between then and now. 

Let me know if there is any other information you need me to capture. 

[Working version.docx](https://github.com/user-attachments/files/16457964/Working.version.docx)

**Comment by hiltonlima** [comment]
@dylanrrmcguire119 sorry for this late response. 

Can you try with the latest branch? `v2.11-beta3.1+fall2024`
This version require `Ubuntu Server 24.04`. Please do a fresh install on the sd card before install the TH from this branch.

**Comment by fabiowmm** [comment]
Seems originator has lost interest. Please reopen if you are still facing the problem.
