### ISSUE TITLE
[Feature] [Frontend] Add symbol for `NOT_APPLICABLE` test case state 

### ISSUE THREAD

**Issue by ccruzagralopes** [project-chip/certification-tool#317]
### Feature description

With the upcoming PICS v2 feature, python tests that are not applicable for the DUT will start being executed by the TH and then the SDK will inform the TH that it's not applicable. In that case, the UI is not displaying any symbol by the test case side. It would be nice to have a symbol for the tests that have been skipped because they are not applicable.

I'm not sure if there's currently a symbol for not applicable test steps. If there is, it could be reused. If there isn't, the new one can also be used for steps.

ps: It would be nice to have that for test suites and collections as well.

### Use Cases

Once the PICS v2 feature is integrated:

Use `chip-lighting-app` as DUT and run the test cases `TC-IDM-12.1` and `TC-TIMESYNC-2.1`.
The test case `TC-TIMESYNC-2.1` should be skipped because it is not applicable and the UI should reflect that.

### Test Cases

Mentioned in the topic above.

### Additional Information

Screenshot for a test run in dev mode, using backend's branch `feature/290_pics_v2_not_applicable_support` and SDK changes from this PR: https://github.com/project-chip/connectedhomeip/pull/34384:
<img width="1519" alt="Screenshot 2024-07-22 at 17 19 43" src="https://github.com/user-attachments/assets/2952ded7-ec6f-4b74-a637-994177433a1a">

The screenshot shows that the test case and test suite complete with state `NOT_APPLICABLE`, but there's no icon by the their names to indicate that.

Also, the test collection shows a failure icon, which is incorrect.

One more detail I'd like to mention is the color associated with each state, which would also be nice to have one for not applicable.

**Comment by raul-marquez-csa** [comment]
For this issue I will take care of the missing test case symbol and the test collection X symbol, we can open other issues for test steps/suites each.

**Comment by ccruzagralopes** [comment]
> For this issue I will take care of the missing skipped test case symbol and the test collection symbol that is currently incorrectly implying that it failed, we can open other issues for test steps/suites each.

Agreed!

**Comment by raul-marquez-csa** [comment]
The logic for test steps/cases/collections/suites is in the same place, so all were ultimately addressed.
PR
[Adds not-applicable/skipped symbol to test steps/cases/collections/suites #22
](https://github.com/project-chip/certification-tool-frontend/pull/22)

**Comment by raul-marquez-csa** [comment]
PR merged
https://github.com/project-chip/certification-tool-frontend/pull/22
