### ISSUE TITLE
PICS Tool validation issue for TSTAT.S.F00 and/or TSTAT.S.F01

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#32]
From chip-certification-tool created by [paulux15](https://github.com/paulux15): CHIP-Specifications/chip-certification-tool#875  

## Summary Title: PICS Tool validation issue for TSTAT.S.F00 and/or TSTAT.S.F01
    There is a problem with the validation of PICS TSTAT.S, especially with the 2 items: TSTAT.S.F00 and TSTAT.S.F01
    You cannot define you Thermostat as a Heating or a Cooler device only, as specified in the Specs.

## Description:
    If you select TSTAT.S.F00 (=true) and unselect TSTAT.S.F01 (=false), you get 2 errors after validation!
Normally you should be able to choose either F00 (Heating only), F01 (Cooling only) or both (Heating and Cooling).
I have the impression that there is a dependency issue somewhere.
With PICS Tool v1.6.4, 'Validate All' gives you 2 errors (F00 and F01), but  you get the list of TCs to run.
While with the latest PICS Tool v1.6.8, you get these 2 errors without the display of the list of TCs.

## Steps to reproduce:
    Validate your Thermostat Cluster Test Plan.xml with TSTAT.S.F00 (=true) and TSTAT.S.F01 (=false), or the opposite.
    You systematically will get 2 errors. TSTAT.S.F05 (Auto mode) can be unset (=false).

## Logs:
    
![MY-CONFIG-PICS-Thermostat_server](https://github.com/CHIP-Specifications/chip-certification-tool/assets/109607916/cacec0dd-39a3-4d67-b954-6f88a857163b)

## Additional Info:
    The versions of Tools used:  'XML_PICS Version Master - Ver -17' and PICS Tool v1.6.8 and v1.6.4

**Comment by fabiowmm** [comment]
This was assigned to @aperez-csa
