### ISSUE TITLE
[Bug] Unable to start certification-tool-backend-1 properly

### ISSUE THREAD

**Issue by yf-fan-org** [project-chip/certification-tool#322]
### Describe the bug

Unable to start certification-tool-backend-1 properly，log is:
INFO     | 2024-07-30 08:16:09.797 | app.log:__configure_notifier_handler:111 | Exception notifier not enabled
INFO     | 2024-07-30 08:16:11.116 | __main__:main:50 | Initializing service
INFO     | 2024-07-30 08:16:11.118 | tenacity.before:log_it:27 | Starting call to '__main__.init', this is the 1st time calling it.
INFO     | 2024-07-30 08:16:11.236 | __main__:main:52 | Service finished initializing
INFO     | 2024-07-30 08:16:17.761 | app.log:__configure_notifier_handler:111 | Exception notifier not enabled
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.util.messaging] Can't locate revision identified by '9df8004ad9bb'
FAILED: Can't locate revision identified by '9df8004ad9bb'

### Log files

INFO     | 2024-07-30 08:16:09.797 | app.log:__configure_notifier_handler:111 | Exception notifier not enabled
INFO     | 2024-07-30 08:16:11.116 | __main__:main:50 | Initializing service
INFO     | 2024-07-30 08:16:11.118 | tenacity.before:log_it:27 | Starting call to '__main__.init', this is the 1st time calling it.
INFO     | 2024-07-30 08:16:11.236 | __main__:main:52 | Service finished initializing
INFO     | 2024-07-30 08:16:17.761 | app.log:__configure_notifier_handler:111 | Exception notifier not enabled
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.util.messaging] Can't locate revision identified by '9df8004ad9bb'
FAILED: Can't locate revision identified by '9df8004ad9bb'

### Environment

v2.10.1+spring2024

**Comment by yf-fan-org** [comment]
@ccruzagralopes pls help

**Comment by yf-fan-org** [comment]
I think it's a bug, I ended up fixing it by switching to commit cafa417fcfd47f859faa976e9193607aed0bfc2d and then building a new docker!

**Comment by fabiowmm** [comment]
Seems originator has lost interest. Please reopen if you are still facing the problem.
