### ISSUE TITLE
[Bug] TC-ACE-1.3 "error: missing --wifi-ssid for --commissioning-method ble-wifi!"

### ISSUE THREAD

**Issue by slidesoon** [project-chip/certification-tool#331]
### Describe the bug

Exec TC-ACE-1.3 met  error: missing --wifi-ssid for --commissioning-method ble-wifi!

In fact, wifi ssid and password were set in project config. 

### Log files

[UI_Test_Run_Python_2024_08_05_11_23_42.log](https://github.com/user-attachments/files/16494960/UI_Test_Run_Python_2024_08_05_11_23_42.log)

**Comment by slidesoon** [comment]
my project config 
{
  "config": {
    "network": {
      "wifi": {
        "ssid": "R**720",
        "password": "h**lth720"
      },
      "thread": {
        "rcp_serial_path": "/dev/ttyACM0",
        "rcp_baudrate": 115200,
        "on_mesh_prefix": "fd11:22::/64",
        "network_interface": "eth0",
        "dataset": {
          "channel": "15",
          "panid": "0x1234",
          "extpanid": "1111111122222222",
          "networkkey": "00112233445566778899aabbccddeeff",
          "networkname": "DEMO"
        },
        "otbr_docker_image": null
      }
    },
    "dut_config": {
      "discriminator": "3840",
      "setup_code": "20202021",
      "pairing_mode": "ble-wifi",
      "chip_timeout": null,
      "chip_use_paa_certs": false,
      "trace_log": true
    },
    "test_parameters": null
  }

**Comment by ccruzagralopes** [comment]
This is indeed an issue on TH's logic.

@slidesoon as a workaround, I believe that if you add `"wifi-ssid": <your ssid>` and any other required arguments to the `test_parameters` section in you project config, you'll be able to run the test case.

**Comment by slidesoon** [comment]
> "wifi-ssid":

My trouble will be resolved by adding "wifi-ssid" and "wifi-passphrase" to test_parameters section in project config, but if the script could read these from project config network section will be better I think.
