### ISSUE TITLE
[Bug] TH User Guide for Fall 2024 does not update upgrade scenario

### ISSUE THREAD

**Issue by sander-gitl** [project-chip/certification-tool#335]
### Describe the bug

Users wanting to upgrade from a previous test harness (e.g. 1.3) release may miss the instruction to start from scratch and instead follow the "upgrade instructions" in Chapter 4.4. They find it will fail when going from e.g. Matter 1.3 TH (Ubuntu 22.04) to Matter 1.4 / Fall 2024 (Ubuntu 24.04) since it assume a different Ubuntu version.
Impact: a lot of support questions will be done for this since this constitutes a major change.

### Expected behavior

Expectation: add an instruction how to e.g. do a "do-release-upgrade" e.g. for Ubuntu 22.04 on TH 1.3 if you want to move to Matter 1.4 in chapter 4.4. Or provide a text like "If coming from TH 1.0-1.3: perform a clean install."

**Comment by hiltonlima** [comment]
Please check the updated user guide on this link: https://github.com/project-chip/certification-tool/blob/v2.11-beta2%2Bfall2024/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc

**Comment by sander-gitl** [comment]
This looks good thanks. 
Considering that this document will be read by people that want to use an earlier SDK version, it might still be worth to add the Ubuntu version to the table in *Test-Harness Links* on lines 45-51 in the comment section as well ? For now I will close the comment, and leave that for your consideration.
