### ISSUE TITLE
Received "Failed to perform commissioning step 20" error

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#34]
From chip-certification-tool created by [njames-11](https://github.com/njames-11): CHIP-Specifications/chip-certification-tool#925  

### Describe the bug

Setup details:
- Rpi4 with THv2.8.1
- DUT is a Matter over **Thread** device

The issue occurs when running any auto test cases using Test Harness.
Please note that:
a.  If using "chip-tool" command, then commissioning passes.
b. If DUT is a Matter over **Wifi** device, then commissioning passes

Configuration on TH:
=======
{
  "config": {
    "network": {
      "wifi": {
        "ssid": "testharness",
        "password": "wifi-password"
      },
      "thread": {
        "rcp_serial_path": "/dev/ttyACM0",
        "rcp_baudrate": 115200,
        "on_mesh_prefix": "fd11:22::/64",
        "network_interface": "wlan0",
        "dataset": {
          "channel": "15",
          "panid": "0x1234",
          "extpanid": "1111111122222222",
          "networkkey": "00112233445566778899aabbccddeeff",
          "networkname": "Matter-Thread"
        },
        "otbr_docker_image": null
      }
    },
    "dut_config": {
      "discriminator": "2580",
      "setup_code": "16016",
      "pairing_mode": "ble-thread",
      "chip_tool_timeout": null
    },
    "test_parameters": {
      "endpoint": 0
    }
  }
=======

### Steps to reproduce the behavior

1.  Start TH
2.  Load PICS
3.  Set configuration as above
4.  Select TC-ACL-1.1
5.  Power cycle on DUT
6.  Start test

### Log files

PFA for:
-  TH log
-  DUT log
-  Rpi4 manual pairing log
-  DUT manual paring log

[UI_Test_Run_2023_08_05_17_23_02.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12268505/UI_Test_Run_2023_08_05_17_23_02.log)
[UI_Test_Run_2023_08_05_17_23_02-DUT.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12268506/UI_Test_Run_2023_08_05_17_23_02-DUT.log)
[Manual-Commissioning-Rpi4.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12268508/Manual-Commissioning-Rpi4.log)
[Manual-Commissioning-DUT.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12268509/Manual-Commissioning-DUT.log)

### Environment

- TH v1.8.1
- Patch applied

**Comment by raju-apple** [comment]
Hi,
Just want to update:
The issue is actually a result from TH logs, showing wrong location of PAA cert file.
Pairing cmd (From TH log) is:

./chip-tool pairing ble-thread 0xf0852d7c815675eb hex:0e080000000000010000000300000f35060004001fffe0020811111111222222220708fd0428a258235750051000112233445566778899aabbccddeeff03055448322d38010212340410044a146deb843235ea719bf5eff5506e0c0402a0f7f8 16016 2580 --trace_file "/logs/trace_log_2023-08-08_01.06.59_0xf0852d7c815675eb_PAIRING_ble-thread.log" --trace_decode 1 --paa-trust-store-path /paa-root-certs

Note:  it shows that it is expecting the PAA cert to be at:  "/paa-root-certs/"

But in reality it is looking to find the file at:   "/var/paa-root-certs/".
When moving the file to "/var/paa-root-certs/", the issue is no longer observed.

**Comment by raju-apple** [comment]
Hi @njames-11  This log information on test harness is the command line the was executed on the docker container hosting the sdk binaries (chip-tool / chip-all-cluster-apps / etc).
There is a volume mapping: raspberry:/var/paa-root-certs -> docker_container:/paa-root-certs
 
The chip-tool binary is actually looking for certs on /paa-root-certs folder, but it  happens that this folder is mapping to the content of /var/paa-root-certs folder on the host machine.

**Comment by fabiowmm** [comment]
The originator apparently is not in this organization.
