### ISSUE TITLE
[Bug] Group `ubuntu` does not exist, causing a boot-time startup to not work

### ISSUE THREAD

**Issue by andy31415** [project-chip/certification-tool#341]
### Describe the bug

Startup fails with `matter-th.service: Failed to determine group credentials: No such process` (when checked via `systemctl status matter-th.service`)

### Steps to reproduce the behavior

- Install on a fresh RPI5 with ubuntu 24.04.
- service does not start after boot

Service can be manually started

### Expected behavior

Boot time startup

### Log files

```
$ systemctl status matter-th.service
Warning: The unit file, source configuration file or drop-ins of matter-th.service changed on disk. Run 'systemctl daemon-reload' to reload units.
× matter-th.service - Matter Test Harness
     Loaded: loaded (/etc/systemd/system/matter-th.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-08-09 19:03:49 UTC; 31min ago
   Main PID: 841 (code=exited, status=216/GROUP)
        CPU: 9ms

Aug 09 19:03:49 harnesspi systemd[1]: Starting matter-th.service - Matter Test Harness...
Aug 09 19:03:49 harnesspi (start.sh)[841]: matter-th.service: Failed to determine group credentials: No such process
Aug 09 19:03:49 harnesspi systemd[1]: matter-th.service: Main process exited, code=exited, status=216/GROUP
Aug 09 19:03:49 harnesspi systemd[1]: matter-th.service: Failed with result 'exit-code'.
Aug 09 19:03:49 harnesspi systemd[1]: Failed to start matter-th.service - Matter Test Harness.
```

**Comment by andy31415** [comment]
Underlying reason seems to be that I used a different username than `ubuntu` when I customized my image (when I selected a wifi connection option).

The test harness seems to assume this user (and and as a result this group) exists. Further issues like #342 also result if you use a different user from ubuntu.

**Comment by hiltonlima** [comment]
@andy31415 Thank you for your feedback.

The user name must be UBUNTU for the system to work correctly.

With this in mind, we will make the installation instructions clearer so that they are not changed.

**Comment by hiltonlima** [comment]
@andy31415  Please take a look and if everything is ok, could you close the issue?

User guide link:
https://github.com/project-chip/certification-tool/blob/fall2024/docs/Matter_TH_User_Guide/Matter_TH_User_Guide.adoc#th-installation-on-raspberry-pi

**Comment by hiltonlima** [comment]
PR with script to verify the current user is 'ubuntu': https://github.com/project-chip/certification-tool/pull/346

**Comment by hiltonlima** [comment]
PR with script to verify the current user is 'ubuntu': https://github.com/project-chip/certification-tool/pull/346
Feel free to reopen this issue if needed.
