### ISSUE TITLE
[Bug] frequently encounter errors at the step 'Wait for the commissioned device to be retrieved' in many different test cases

### ISSUE THREAD

**Issue by ray24c** [project-chip/certification-tool#343]
### Describe the bug

Hi there,
When performing auto tests, I frequently encounter errors at the step **Wait for the commissioned device to be retrieved** in many different test cases (usually at step 1). In some test cases, as shown in the attached image, only this step fails while all other steps pass. What could be the possible reason for this? How can it be resolved?

### Steps to reproduce the behavior

run a FirstChipToolSuite (auto and semi-auto) test case.

### Log files

[4nd_Test_Run_2024_08_08_14_53_46.log](https://github.com/user-attachments/files/16578121/4nd_Test_Run_2024_08_08_14_53_46.log)
[4nd_Test_Run_2024_08_08_14_53_46-18.json](https://github.com/user-attachments/files/16578122/4nd_Test_Run_2024_08_08_14_53_46-18.json)
[Test Report.pdf](https://github.com/user-attachments/files/16578123/Test.Report.pdf)

### PICS file

[PICS.zip](https://github.com/user-attachments/files/16578133/PICS.zip)

### Screenshots

<img width="727" alt="image" src="https://github.com/user-attachments/assets/f26e9ebb-a5fb-45d4-9080-ba44a426e2c8">

<img width="472" alt="image" src="https://github.com/user-attachments/assets/0efc8380-e07a-48ee-b97c-321949111aff">

### Environment

TH Version: TH Fall2023 Sha: 3f84bff5
OS: Ubuntu: 22.04.3 LTS
Browser: Chrome

**Comment by rquidute** [comment]
Hi @ray24c, according to the logs, a failure has been report at commissioning step, it seems the device is already commissioned at the moment the test was performed.
Could you please double check the DUT is not commissioned before starting the test execution?

**Comment by ray24c** [comment]
Hi @rquidute, 
In my test steps, I ensure the DUT is commissioned before starting the automated test cases. I also attempted to commission the DUT during the start of the automated test, but encountered the same issue. I've attached the log for reference.

![1](https://github.com/user-attachments/assets/537291e4-3f0d-4f03-92af-c07dadc1f0ea)
![2](https://github.com/user-attachments/assets/51bcc135-8088-4ae4-96d2-8a865247aea0)
![3](https://github.com/user-attachments/assets/19ca6fba-4567-456b-809d-1b8a8a71c3ff)
![4](https://github.com/user-attachments/assets/dcafbbea-6b7d-4cfc-9db2-4a66c26941d3)
![5](https://github.com/user-attachments/assets/57ebdb92-38ad-4ecc-9cbd-75a3f26a1c12)

[Identify_Cluster_Project_Config.txt](https://github.com/user-attachments/files/16596032/Identify_Cluster_Project_Config.txt)

**Comment by rquidute** [comment]
Hi @ray24c Thanks for your feedback. 
Could you please try starting the test run execution with the DUT not commissioned and don't commission the DUT while the test is running? The test itself should commission the DUT.

**Comment by ray24c** [comment]
Hi @rquidute 
I apologize for the confusion. Just to clarify, the DUT commissions itself during the test run. No manual commands are issued.
But encountered the same issue. 
Thank you for your response.

**Comment by Silabs-Hieu** [comment]
Hi @ray24c, this issue has been discussed in https://community.silabs.com/s/question/0D5Vm000001JiA0KAK/got-the-fail-with-icd-for-executing-test-step-step-1-wait-for-the-commissioned-device-to-be-retrieved and you can realize that the main cause is the ICD device sleeps right after it finishes the commissioning process.
To make it wakes more a little bit, you can setup the ICD configuration to make your device is in active mode long enough to pass that step.

Regards,

**Comment by ray24c** [comment]
Hi @Silabs-Hieu, thank you, we will try your advice to verify it.

**Comment by ray24c** [comment]
Hi @Silabs-Hieu it works
Thank you for your great support, @rquidute and @Silabs-Hieu
