### ISSUE TITLE
[Bug] [TC-SC-7.1] Not able to commission with QR-Code from TH.

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/certification-tool#348]
### Describe the bug

TC-SC-7.1: I’m able to run from Python Docker but UI-Python is failing. From UI-Python I’m getting this error:
Didn't find any CertificateAuthorities in storage -- creating a new CertificateAuthority + FabricAdmin...
from Docker I use --bool-arg post_cert_test:true  --qr-code MT:0MZJ1KQS02-10648G00 to the command.
from UI: I have these test parameters
```
    "test_parameters": {
      "timeout": 10000,
      "thread-dataset-hex": "000300001902085b35dead5b35beef051000112233445566778899aabbccddeeff01025b35",
      "bool-arg": "post_cert_test:true",
      "qr-code": "MT:0MZJ1KQS02-10648G00"
    }
```
Test works when running direction from Python Docker, fail in UI-Python.
[TC-SC-7.1-UI-Python.log](https://github.com/user-attachments/files/16592194/TC-SC-7.1-UI-Python.log)
[TC_SC_7_1-PythonDocker.log](https://github.com/user-attachments/files/16592195/TC_SC_7_1-PythonDocker.log)

TH only supports pairing method of `onnetwork, ble-thread, and ble-wifi` and this test will require support for `code, code-thread, and code-wifi`

### Environment

TH Version: v2.11-beta2+fall2024

**Comment by raju-apple** [comment]
@yinyihu-silabs can you help validating the fix to check to see if this fixes your issue ? @rquidute will provide the branch details to try it out. Thanks !

**Comment by rquidute** [comment]
Hi @yinyihu-silabs could you please update your code by using the command bellow at `certification-tool` folder? 
- ./scripts/ubuntu/auto-update.sh qr_code_fix
- ./scripts/start.sh

Please let us know if this fixes the issue.
