### ISSUE TITLE
Read the global attribute: FeatureMap all  Failed

### ISSUE THREAD

**Issue by MaplestoryAlen** [project-chip/certification-tool#352]
### Describe the bug

 Why do all the cluster featuremaps I read out fail. But using the chip tool to read can read the value of the Feature Map. May I ask where I did wrong?

### Steps to reproduce the behavior

[UI_Test_Run_2024_08_13_15_56_38-26.json](https://github.com/user-attachments/files/16596431/UI_Test_Run_2024_08_13_15_56_38-26.json)

### Environment

I don't know where to check the TH version, which corresponds to matte 1.2 img and matte th-fall2023 shrunk.img

**Comment by rquidute** [comment]
@raju-apple This issue was found at matter 1.2 version

**Comment by fabiowmm** [comment]
Seems originator has lost interest. Please reopen if you are still facing the problem.
