### ISSUE TITLE
[Bug] [TC-ICDM-2.1] test hangs on skipping step 8

### ISSUE THREAD

**Issue by adamb-q** [project-chip/certification-tool#355]
### Describe the bug

The test is hanging on UI and failing when executed from docker, always on step 8 which should be skipped according to PICS.
[[TC-ICDM-2.1]_[eWg0ZwBp]_TH_log.log](https://github.com/user-attachments/files/16598724/TC-ICDM-2.1._.eWg0ZwBp._TH_log.log)

**Comment by rquidute** [comment]
Waiting SDK issue be fixed: https://github.com/project-chip/connectedhomeip/issues/35015
