### ISSUE TITLE
[Bug] Documentation of the exact semantics and usage of `test_parameters` config section missing

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/certification-tool#357]
### Describe the bug

`test_parameters` is critical to python scripts but is not explained in detail in the manual.

It is covered by weak examples in sections:

> 9.5.2. Run Tests on the TH User Interface
>
> To configure specific/custom parameters, please edit the project configuration to include the
parameters in the session (test_parameters).

and 

![image](https://github.com/user-attachments/assets/8938c3cb-8bbe-4920-bf2a-72f53f954221)

This is completely insufficient to understand the rules/usage, and does not offer any guidance for how to deal with large numbers of tests that have different parameters.

For example, different tests may require different arguments but the config is global and all arguments are given to all tests.

Furthermore, there is no validation that some tests need particular arguments (MANDATORY) to run (e.g. TC-IDM-10.2 needs --qr-code or --manal-code) and some tests require PIXIT.xxxx. The format of the parameters is also not validated. This makes running large numbers of automated Python tests error-prone.

### Steps to reproduce the behavior

Read the docs as explained above

### Expected behavior

- Each field of `test_parameters` is documented for what it does, what format is legal, and how it works.
- `dut_config` that are unambiguous are automatically used in the `test_parameters`  without needing to copy them under a different name (e.g. thread-dataset-hex)
- Handling of test arguments is validated by TH

**Comment by andy31415** [comment]
A UI that simplifies/completes the json config would be great.
