### ISSUE TITLE
[Bug] TH manual does not include Python TC parameters documentation

### ISSUE THREAD

**Issue by sander-gitl** [project-chip/certification-tool#362]
### Describe the bug

When executing a Python test, some of the TC expect specific parameters or errors occur. E.g. TC-DA-1.2 expects "cd_cert_dir" argument. These parameters _are_ contained in the VS document ("Python Script Command")
In the TH user guide, a generic section is missing to let the user know the location of these parameters.

### Expected behavior

Add a generic section/chapter to the TH user guide - e.g. to chapter 9.1 - describing:
* what the user must do for each test case (Python/Yaml), including PICS/PIXIT configuration
* how the user can find the correct list of parameters for each test case (e.g. for Python : get the list of parameters from VS - Python Script Command)
* where the log files for the test case are stored (in case this is different than usual)
* where to get any other specific information for the test case
In most instances, the answer to the above is the VS document.

**Comment by tcarmelveilleux** [comment]
@sander-gitl The Survival Guide should also include some of these top-level details, beyond the manual.

**Comment by hiltonlima** [comment]
https://github.com/project-chip/certification-tool/issues/361
