### ISSUE TITLE
[Bug] TH manual has screenshots instead of text for all config samples. This prevents searching for text

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/certification-tool#368]
### Describe the bug

TH manual has screenshots instead of text for all config samples. This prevents searching for text

![image](https://github.com/user-attachments/assets/2845530c-894b-4b5d-b194-fc247a96467a)

### Steps to reproduce the behavior

Read the manual

### Expected behavior

All config samples should use pre-formatted asciidoc "code blocks" rather than screen shots.

This would not only make  reading/search the manual easier, but would also make editing the manual easier.

**Comment by hiltonlima** [comment]
User guide updated: https://github.com/project-chip/certification-tool/pull/398
Please fell free to reopen the issue if needed.
