### ISSUE TITLE
[Bug] UI for manual steps has truncated text

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/certification-tool#372]
### Describe the bug

Whenever a test with prompts is run (including manual tests), if the prompt text is not very limited, we hit usability issues immediately:

- Doesn't show the prompt fully yet doesn't have an easy way to tell I am missing text (i.e. that scrollbars could be navigated to help)
- Scrollbars are very hidden until hovered (needless styling) and are very tiny targets by default which makes them very hard to operate
- Scrolling is required in two directions to deal with any non-trivial text (see video)

### Steps to reproduce the behavior

Run TC-BINFO-3.1, try to follow steps

### Expected behavior

- Much larger default text area to show the manual step prompt
  - Avoids horizontal/vertical scrollbars most of the time
- Auto-wrapping of text to avoid horizontal scrollbars 99% of the time
- Scrollbars for prompt ALWAYS visible
- Scrollbars for prompt larger

### Screenshots

[Completely Broken UI for manual steps.webm](https://github.com/user-attachments/assets/24f73b51-5715-459a-8c88-767a3edcd03a)

**Comment by gvargas-csa** [comment]
The following tasks have been completed:

- [x] Scrollbar is now always visible.
- [x] The scrollbar for the prompt is twice as large.
- [x] The default text area for the manual step prompt is 3.5 times larger.
- [x] Auto-wrapping of text has been implemented.

However, there are still two scrollbars appearing: one horizontal scrollbar for the overflow text and one vertical scrollbar for the entire prompt window.
