### ISSUE TITLE
[Bug] TC-TBRM-2.1 Test Step Error: Failed Parsing with error: Unknown attribute

### ISSUE THREAD

**Issue by DejinChen** [project-chip/certification-tool#373]
### Describe the bug

Test step error in TC-TBRM-2.1

### Steps to reproduce the behavior

Run TC-TBRM-2.1 in TestHarness v2.11-beta2+fall2024.

### Expected behavior

Test Step Error: Failed Parsing with error: Unknown attribute

### Screenshots

![unknown_attribute](https://github.com/user-attachments/assets/709d9319-5454-44ba-b334-81699d996d78)

### Environment

TH version: [v2.11-beta2+fall2024]
OS: Ubuntu 24 on RaspberryPi
Browser: chrome

**Comment by DejinChen** [comment]
Maybe [SDK_DOCKER_IMAGE](https://github.com/project-chip/certification-tool-backend/blob/e3e01e90a206893ebc593e1f740b223a0edaa8c8/test_collections/matter/config.py#L25C30-L25C60) should be updated.

**Comment by raju-apple** [comment]
Can you please try with a newer version of TH and check please ? If the issue still exists please reopen the ticket : 

```
TH v2.11-beta3+fall2024is available
Installation steps for TH v2.11-beta3+fall2024
Fresh installation:
git clone -b v2.11-beta3+fall2024 https://github.com/project-chip/certification-tool.git --recurse-submodules
cd ~/certification-tool
./scripts/pi-setup/auto-install.sh

At the end of the script, select option 1 to restart the RaspberryPi.
Wait about 10 minutes. 

Update from v2.11-beta2+fall2024:
cd ~/certification-tool
./scripts/ubuntu/auto-update.sh v2.11-beta3+fall2024
./scripts/start.sh
```

**Comment by DejinChen** [comment]
It works.
