### ISSUE TITLE
[Bug] IDM-10.4 fails on PICS_SDK_CI_ONLY

### ISSUE THREAD

**Issue by adamb-q** [project-chip/certification-tool#379]
### Describe the bug

The test is failing always 
![image](https://github.com/user-attachments/assets/cc199fb3-aa0f-4c2c-a97f-f8bb3e96b768)
 the PICS_SDK_CI_ONLY is set https://github.com/project-chip/connectedhomeip/blame/master/src/python_testing/test_testing/test_IDM_10_4.py#L116

**Comment by rquidute** [comment]
Hi @adamb-q could you please share your `project config` and `execution logs`?

**Comment by adamb-q** [comment]
Logs: [[TC-IDM-10.4]_[xfJLZJrv]_TH_log.log](https://github.com/user-attachments/files/16657699/TC-IDM-10.4._.xfJLZJrv._TH_log.log)
Config: [config.json](https://github.com/user-attachments/files/16657768/config.json)

**Comment by adamb-q** [comment]
OK - I think I should check each endpoint separately, for now I just loaded all the PICS - the UI error message was misleading. I think it can be closed

**Comment by abu-matterize** [comment]
hello @rquidute - i've specified the endpoints as,
```json
{
  "config": {
    "test_parameters": {
      "bool-arg": "allow_provisional:True",
      "endpoint": "0 1"
    }
  }
}
```
but it's only showing checking against the endpoint 0 and produces the `PICS_SDK_CI_ONLY` error.

Log file attached.

[tc-idm-10-4_2025_08_25_12_55_55.log](https://github.com/user-attachments/files/21963919/tc-idm-10-4_2025_08_25_12_55_55.log)

**Comment by rquidute** [comment]
Hi @abu-matterize Could you try running the test using an individual endpoint configuration? It should have the correct PICS based on the DUT's implementation for that endpoint.
To be honest, we've never run tests with a multiple-endpoint configuration. We're looking into it right now.
