### ISSUE TITLE
[Bug] manual verification test steps will not appear if a PICs file is not loaded previously

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#38]
From chip-certification-tool created by [gvargas-csa](https://github.com/gvargas-csa): CHIP-Specifications/chip-certification-tool#939  

### Describe the bug

I have been using the version: TH Fall 2023 - beta3 and I realized that if a PICs file is not loaded previously, the dialogs in the frontend to help the user with what manual verification test steps (commands) they have to send will not appear. But if you use a PICs file it doesn't matter if it doesn't match the tests you run, the dialogs appear again.

In my case I have been using a test plan for the DoorLock and the test that I ran it was `TC-FAN-1.1` (Semi-Automated)

### Steps to reproduce the behavior

1. Create a new project in the Test Harness Frontend
2. Setup the project with your values
3. When is created the project, Go to edit the project and verify it does not have a PICs File loaded.
4. Now go to test-run in the project
5. Create a New Test Run
6. Add a new operator name
7. Please select a test case `TC-FAN-1.1 (Semi-Automated)` there is under the SDK YAML Tests -> FirstChipToolSuite
8. Run in your terminal or raspberry pi the `./chip-all-cluster-app` this depends on your setup.
9. Now go to start

### Expected behavior

The manual verification tests steps must be appears in a dialog for help to the user to know what kind of commands should be use to send to the `chip-tool` to continues with the test. 

### PICS file

[Door lock Test Plan.xml.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12315433/Door.lock.Test.Plan.xml.zip)

### Screenshots

https://github.com/CHIP-Specifications/chip-certification-tool/assets/131407127/026eedf1-c50e-4731-a98b-275541bde560

https://github.com/CHIP-Specifications/chip-certification-tool/assets/131407127/7c5313c4-85d8-4cb3-bcfd-2d5b5da93357

### Environment

- TH Version: TH Fall 2023 - Beta3
- OS: macOS 13.4.1 (c) 
- Browser: Safari 16.5.2

### Additional Information

https://csamembers.slack.com/archives/C03MA7WR7Q8/p1691639376979739

**Comment by raju-apple** [comment]
@gvargas-csa For certification is there an use case where a participant would try to run a test without any PICS file ?

**Comment by raju-apple** [comment]
@raju-apple In my case was a testing purpose I mean I was working on debugging it, but there is not use case to the members so they shouldn't be doing this in that way.

**Comment by raju-apple** [comment]
In the last meetings we agreed to put a message/alert when users did not upload a PICs File and they are going to run some test. Just to keep this updated I have working on it so I will assign to myself.

**Comment by fabiowmm** [comment]
Was self-assigned to @gvargas-csa in the old repo.
