### ISSUE TITLE
[Bug] network-manager-app - Missing Reference Apps in UI

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/certification-tool#399]
### Describe the bug

The` network-manager-app`  app is not available in the UI and need to be added
![image](https://github.com/user-attachments/assets/b7ccd11c-2289-4279-9f5a-fdf42bfe5418)

**Environment**
Version: v2.11-beta2+fall2024
Sha: bbeda31

**Comment by rquidute** [comment]
Hi @Rajashreekalmane this app was in added in Dockerfile in this PR: https://github.com/project-chip/connectedhomeip/pull/35207.
Also, a small change is required at `test_collections/matter/scripts/update-sample-apps.sh` backend script
This PR will fix this: https://github.com/project-chip/certification-tool-backend/pull/132/files

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest Image
