### ISSUE TITLE
[Bug] Setup failed with ec0a8abbea5

### ISSUE THREAD

**Issue by ksperling-apple** [project-chip/certification-tool#406]
### Describe the bug

Running `./scripts/pi-setup/auto-install.sh` on a fresh Ubuntu 22.04.1 install fails:

```
********************************************************************************
setup.sh: Instaling package: libdbus-1-dev (=1.14.10-4ubuntu4)
********************************************************************************
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 satisfy:command-line : Depends: libdbus-1-dev (= 1.14.10-4ubuntu4) but 1.14.10-4ubuntu4.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Full log below.

### Log files

[th-install-log.txt](https://github.com/user-attachments/files/16883217/th-install-log.txt)

### Environment

TH version: ec0a8abbea5

**Comment by ksperling-apple** [comment]
The TH install script completes successfully after removing the `-updates` and `-backports` suites from `/etc/apt/sources.list.d/ubuntu.sources`.

**Comment by hiltonlima** [comment]
Hello @ksperling-apple,

Please try the latest version on branch `v2.11-beta3+fall2024`

**Comment by fabiowmm** [comment]
Seems originator has lost interest. Please reopen if you are still facing the problem.
