### ISSUE TITLE
[BUG] [Matter1.4 TE#2] TC-OPSTATE-2.5 test failure with python script in step 2

### ISSUE THREAD

**Issue by OliverFan1** [project-chip/certification-tool#408]
### Reproduction steps

For TC-OPSTATE-2.5, UI-python test seems not work right, and if I run test in Python inside docker mode, test failed quite early at step2. 
Test commands and parameters are as follows (found from _Matter_V_1_4_TestPlanVerification_ document in _Python Script Command_ sheet): 
python3 TC_OPSTATE_2_5.py --commissioning-method ble-wifi --wifi-ssid ORBI32 --wifi-passphrase slowballoon575 --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json --PICS /var/tmp/ --int-arg PIXIT_ENDPOINT:1 PIXIT.WAITTIME.REBOOT:100 --paa-trust-store-path /credentials/development/paa-root-certs/

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

304df86c9300ecfdfb1e6424565867d9dc6ad359

### Platform

freeRTOS, other

### Anything else?

This issue was found during Matter 1.4 TE#2, see attached the test log
[failed-TC-OPSTATE-2.5.log](https://github.com/user-attachments/files/16654760/failed-TC-OPSTATE-2.5.log)

**Comment by fabiowmm** [comment]
@antonio-amjr please take a look.

**Comment by antonio-amjr** [comment]
> @antonio-amjr please take a look.
I'll see what I can do here

**Comment by antonio-amjr** [comment]
Hi @OliverFan1,

I was investigating this issue and I'm a bit confused here with your results.
Let me know if I'm following correctly.

According to your manual logs, three events are received in sequence and one of them would trigger the error you mentioned above: `The total operation time shall be at least 30.0`.

When analyzing the TH UI log as well, there are two events, the first one being:
`[MatterTest] 08-29 21:54:54.964 INFO Got subscription report for event 1 on cluster 96: OperationalState.Events.OperationCompletion(completionErrorCode=0, totalOperationalTime=0, pausedTime=0)`
So I believe that the test is resulting in that error for an operation event not correct or expected.

Can you verify those details? Let me know if I misunderstood anything or if I can help with any test.

------

**PS:** There are some step logs in the latest version of TH that may help like the below I ran here:
```
[MatterTest] 12-26 14:01:06.609 INFO Got subscription report for event 1 on cluster 96: OperationalState.Events.OperationCompletion(completionErrorCode=0, totalOperationalTime=30, pausedTime=0)
[MatterTest] 12-26 14:01:06.610 INFO ***** Test Step 10 : TH reads from the DUT the OperationalState attribute
```

**Comment by OliverFan1** [comment]
Hi @antonio-amjr,
Thanks for investigating this issue, and sorry for the late response.
This issue was originally found during TE#2, and then in the 1.4 SVE, this TC was PASS on my dut, so I think we can close this since issue is gone.
Thank you.

**Comment by antonio-amjr** [comment]
Hi @OliverFan1,

No problem at all and that's great news. Thanks for the quick response.
I'll close this up. Thanks.
