### ISSUE TITLE
[Bug] [TC-LVL-2.3] Test Harness UI Displays "UNABLE TO PARSE TEST STEP NAME" During Test Execution

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/certification-tool#409]
### Describe the bug

During the execution [TC-LVL-2.3] of test case in the Test Harness,  the UI displays "UNABLE TO PARSE TEST STEP NAME" instead of showing the actual test step name. This issue occurs during the execution of [Test Case Name], affecting the readability and understanding of the test steps.

### Steps to reproduce the behavior

1. Open the UI
2. Upload the PICS
3. Ensure the TC-LVL-2.3 test case is selected
4. Executed the below mentioned command to put DUT into a commissionable state, ./chip-all-clusters-app
5. Click the Start button on Test-Harness user interface.

### Expected behavior

Expected Behavior: The UI should display the correct test step names as defined in the test script.
Observed Behavior: The UI shows "UNABLE TO PARSE TEST STEP NAME".

### Log files

[TC-LVL-2.3.log](https://github.com/user-attachments/files/16926231/TC-LVL-2.3.log)

### PICS file

[On-Off Cluster Test Plan (1).zip](https://github.com/user-attachments/files/16926262/On-Off.Cluster.Test.Plan.1.zip)
[Level Control Cluster Test Plan.zip](https://github.com/user-attachments/files/16926266/Level.Control.Cluster.Test.Plan.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/87baf2e9-d879-4135-a84d-f9d65badca48)

### Environment

Version: v2.11-beta3+fall2024
Sha: f52d40a

**Python Script Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_LVL_2_3.py

**Comment by Ashwinigrl** [comment]
The same issue was observed in the **TC-SWTCH-2.2, 2.3, 2.4, 2.5, and 2.6** test cases.

**Screenshots**
![image](https://github.com/user-attachments/assets/3c097d4f-51d8-4f89-992c-595e62f81558)

**Log files**
[TC-SWCH-2.2.log](https://github.com/user-attachments/files/16989779/TC-SWCH-2.2.log)

**Comment by rquidute** [comment]
This is under investigation. 
Related issue: #306
