### ISSUE TITLE
[SMOKECO] Fails in TH waits for a report from DUT with a timeout of 300 seconds

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#41]
From chip-certification-tool created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-certification-tool#951  

### Describe the bug

UI test runner fails at all "TH waits for a report from DUT with a timeout of 300 seconds" by throwing below error 

> Test Failure: The test expects no error but the "FAILURE" error occured. Test Failure: The test expects a value but it does not exists in the response."

Test case affected :

- TC-SMOKECO-2.2
- TC-SMOKECO-2.3
- TC-SMOKECO-2.4
- TC-SMOKECO-2.5
- TC-SMOKECO-2.6

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the Smoke CO Alarm Cluster Test Plan (1).xml and General Diagnostics Cluster Test Plan.xml PICS file to select the test cases.
2. Selected the `SMOKECO` Automated and Semi Automated test case to executed.
3. Executed the below mentioned command to put DUT into a commissionable state, `./chip-all-clusters-app --enable-key 00112233445566778899aabbccddeeff`
4. Click the Start button on Test-Harness user interface.

### Expected behavior

TC should execute successfully without error

### Log files

[SMOKE_2023_08_29_18_44_15.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12465096/SMOKE_2023_08_29_18_44_15.log)

### PICS file

[SMOKE_PICS.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12465126/SMOKE_PICS.zip)

### Screenshots

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/133193761/efe545aa-a3c5-4e1e-94e7-5ccb3cc9bc1c)

### Environment

**Version:** TH Fall2023
**Sha:** 58a51bef

**Comment by raju-apple** [comment]
From the log we can find the following:
WARNING    | 2023-08-29 13:20:05.100144 | Test Failure: The test expects a value, but it does not exists in the response."

I think It's been a problem at waitForReport since 2022... The response has been given, but TH is slow, so it missed the response.
Referencing Issue https://github.com/project-chip/connectedhomeip/issues/19861

The countering PR for the Smoke CO has been given, but after talking about it, I revoked my work-around. https://github.com/project-chip/connectedhomeip/pull/28044

To solve the issue now, we may need the PR from Vivien at https://github.com/project-chip/connectedhomeip/pull/28257
@cjandhyala 

Update - Changed WaitForReport at script to manual step, make sure we don't block the test...Once this issue is resolved at TH, will revoke the YMAL steps.

**Comment by raju-apple** [comment]
@ericzijian1994 looks like the YAML has the waitforReport step as manual for now , so the test should not be blocked right now , is there any other issue with these set of scripts ?

**Comment by raju-apple** [comment]
> @ericzijian1994 looks like the YAML has the waitforReport step as manual for now , so the test should not be blocked right now , is there any other issue with these set of scripts ?

As far as I know... I don't think the script has running issues with the waitForReport after this turned to manual, but again, I wish waitForReport implementation could be fixed (Improved) so people can have those manual steps turn to automated.

**Comment by ericzijian1994** [comment]
> @ericzijian1994 looks like the YAML has the waitforReport step as manual for now , so the test should not be blocked right now , is there any other issue with these set of scripts ?

From practice, I don't see the current approach to the script having issues will block people...

**Comment by fabiowmm** [comment]
Awaiting https://github.com/project-chip/connectedhomeip/pull/28257

**Comment by fabiowmm** [comment]
SDK issue now fixed.
