### ISSUE TITLE
service "backend" is not running

### ISSUE THREAD

**Issue by song7788** [project-chip/certification-tool#412]
### Describe the bug

![image](https://github.com/user-attachments/assets/1c0d5b86-1196-4c70-bcdb-3d9cdc385f69)

This problem occurs when I execute the start script. How do I fix it?I tried upgrading and clearing, and then restarting the script, but it didn't work.

### Steps to reproduce the behavior

1、Clone the TH repository
2、Goto to TH folder
3、Install/configure the TH dependencies
./scripts/pi-setup/auto-install.sh

**Comment by song7788** [comment]
The Raspberry PI system version is Ubuntu 24.04.1 LTS
The branch is commit f52d40a16def63edecdabbc8edcb14eb76b12ba6

**Comment by hiltonlima** [comment]
It appears that the installation steps are incomplete:
Please try these:
```
cd ~/certification-tool
./scripts/stop.sh
cd ..
rm -rf certification-tool
git clone -b v2.11-beta3.1+fall2024 https://github.com/project-chip/certification-tool.git --recurse-submodules
cd ~/certification-tool
./scripts/pi-setup/auto-install.sh
```

**Comment by song7788** [comment]
Problem solved. Thank you for your help @fabiowmm @hiltonlima

**Comment by alicelcf** [comment]
Hi @song7788，
I meet the same issue, How did you solve it?
