### ISSUE TITLE
[Bug] Thread commissioning is failing when using v2.10.1+spring2024 Test Harness environment

### ISSUE THREAD

**Issue by OlivierGre** [project-chip/certification-tool#419]
### Describe the bug

This ticket is a follow up of a discussion started in Slack:
https://csamembers.slack.com/archives/C03MA7WR7Q8/p1726672659694019
Hilton Lima advised me to open this ticket.

Here is a summary of the problem:
I have installed the TH environment v2.10.1+spring2024.
The RPi is connected to a nordic RCP dongle.

When using the TH environment (in a web browser), the commissioning of a Thread device is failing. The 1st commissioning phase is successful. The problem happens when the device tries to join the Operational network. It doesn't succeed to join.

During my investigations, I have seen the following:

If I start the OTBR manually (with "./certification-tool/scripts/OTBR/otbr_start.sh") and then launch the command
`./apps/chip-tool pairing ble-thread 1 hex:$DataSet 20202021 3840`
the commissioning is successful. This proves that the RCP is OK.

If I start the OTBR manually (with "./certification-tool/scripts/OTBR/otbr_start.sh"), copy the dataset in hex format, then, in TH's project configuration I set the field "operational_dataset_hex" with the dataset that I have copied. In that case, the test doesn't have to create the OTBR itself and the commissioning is successful.
So there is a problem when the test creates the OTBR.

I have then tried to change the Mesh local prefix in the project config. On the RPi, I have a script which displays the OTBR settings used by the BR container. I call this script when the test is running. I have noticed that it doesn't use the Mesh local prefix that I have indicated in the project config, which is suspicious. I have entered "fde5:2503:736c:305f::/64" and I get "fd95:b5e2:1a89:2f3::/64".
Here is the script that I use on the RPi to see the OTBR configuration:

```
#!/bin/bash

export container_name=$(docker ps | grep nrfconnect/otbr:9185bda | awk '{print $NF}')
echo $container_name
echo ""

docker exec -t $container_name ot-ctl dataset active

echo ""
docker exec -t $container_name ot-ctl dataset active -x
```

This is the first time that I use the TH environment so I may have done something wrong somewhere...

Thanks for your help

**Comment by OlivierGre** [comment]
Here is the project config:

```
{
  "config": {
    "network": {
      "wifi": {
        "ssid": "testharness",
        "password": "wifi-password"
      },
      "thread": {
        "rcp_serial_path": "/dev/ttyACM0",
        "rcp_baudrate": 115200,
        "on_mesh_prefix": "fde5:2503:736c:305f::/64",
        "network_interface": "eth0",
        "dataset": {
          "channel": "15",
          "panid": "0x1234",
          "extpanid": "1111111122222222",
          "networkkey": "00112233445566778899aabbccddeeff",
          "networkname": "DEMO"
        },
        "otbr_docker_image": null
      }
    },
    "dut_config": {
      "discriminator": "3840",
      "setup_code": "20202021",
      "pairing_mode": "ble-thread",
      "chip_timeout": null,
      "chip_use_paa_certs": false,
      "trace_log": true
    },
    "test_parameters": {
      "endpoint": 0
    }
  },
  "pics": {
    "clusters": {}
  }
}
```

NB: In my first project config, I had set the PICS. In the new project config, where I have changed the Mesh Local Prefix, I have forgotten to set the PICS.

**Comment by OlivierGre** [comment]
This morning, I have started the TH environment and tried to relaunch the commissioning (with the project config using "on_mesh_prefix": "fde5:2503:736c:305f::/64").

The test was always failing to start. On the RPi, I can see that the BR container was created but I was failing to display the OTBR settings. 
I have done that a few times and I had always this problem.

Then I have created the BR manually with
./certification-tool/scripts/OTBR/otbr_start.sh".
Then I have stopped this OTBR. (by calling otbr_stop.sh).

Then I have tried to launch a test from TH env. This time the test was launched and lead to a commissioning failure. I'm attaching the logs:
- there is the Zip downloaded from TH env
- there is the backend log

On the device, I can see that it has receives the dataset
0E08000000000001000035060004001FFFE00708FD5A560F8CDA87B90410D6709582E9E4AF1DE7AC6C13FB4AB97F0C0402A0F7F8000300000F0102123402081111111122222222051000112233445566778899AABBCCDDEEFF030444454D4F
which is the dataset corresponding to the TH's Project config.

That's very strange that I couldn't launch the test before starting the BR manually. I really have a problem with OTBR creation from TH env.

[backend_log.txt](https://github.com/user-attachments/files/17073163/backend_log.txt)
[UI_Test_Run_2024_09_20_09_12_47.zip](https://github.com/user-attachments/files/17073165/UI_Test_Run_2024_09_20_09_12_47.zip)

**Comment by OlivierGre** [comment]
The problem indicated in my previous message is reproducible:

I have power cycled the RPi and restarted the TH environment (via start.sh). I'm then using the TH environment to relaunch the test that I was using this morning. The test is failing at the beginning (so commissioning is not launched). Here are the traces.
[backend_nok.txt](https://github.com/user-attachments/files/17075190/backend_nok.txt)
[UI_Test_Run_2024_09_20_12_13_15.zip](https://github.com/user-attachments/files/17075191/UI_Test_Run_2024_09_20_12_13_15.zip)

**Comment by OlivierGre** [comment]
Does it help if I provide the other logs (frontend, db, proxy)?

**Comment by OlivierGre** [comment]
My few cents:
I was comparing the backend log for the 2 cases: The case where the test is starting (but failing when the device tries to join the operational network) and the case where the test is not starting.

Both are in fact containing:
"app.otbr_manager.otbr_manager:start_device:146 | Border router does not start properly for nrfconnect/otbr:9185bda"
so in my opinion I have something wrong in my setup which prevents the launch of the OTBR.

So my guess is:
When I call "otbr_start.sh" manually, this creates the meshcop_udp service. Thanks to that, the test believes that the OTBR is up and running (which is not true) so the test is run and I got a failure when the device tries to join the operational network (since it doesn't exist).
If "otbr_start.sh" was not started manually, I don't have the meshcop_udp service and the test refuses to go further.

That's just a guess...

**Comment by OlivierGre** [comment]
My explanation looks not correct.
When the TH successfully launches the test, I can see that the meshcop._udp service contains the networkname "DEMO" which is indeed coming from TH project config.

**Comment by OlivierGre** [comment]
Where can I see the exact command called by the backend to launch the OTBR?

In the backend log there it:
```
            Border Router started: nice_kare
            with configuration: {'privileged': True, 'detach': True, 'network': 'host', 'environment': ['NAT64=1', 'DNS64=0', 'WEB_GUI=0'], 'volumes': {'/dev/ttyACM0': {'bind': '/dev/radio'}, PosixPath('/home/ubuntu/certification-tool/backend/otbr_manager/avahi'): {'bind': '/etc/avahi'}}, 'command': '--radio-url spinel+hdlc+uart:///dev/radio?uart-baudrate=115200 -B eth0'}
```
but that doesn't show the command.

**Comment by OlivierGre** [comment]
@hiltonlima Hi Hilton,
Do you have an idea how to progress on this issue? 
Since it works when doing the things manually, my idea is still to find what command is called by the backend to launch the OTBR.
Thanks for your help

**Comment by hiltonlima** [comment]
> @hiltonlima Hi Hilton, Do you have an idea how to progress on this issue?
> 
> I'm starting looking at https://github.com/project-chip/certification-tool-backend/blob/f52d40a16def63edecdabbc8edcb14eb76b12ba6/test_collections/matter/sdk_tests/support/otbr_manager/otbr_manager.py#L133 How can I call this otbr_manager script manually to see if the OTBR is created correcly and is working?
> 
> Thanks for your help

Hi,

We haven't been able to analyze the issue yet. We will update the status as soon as possible.



About the OTBR script, you can find it here:
`certification-tool/backend/test_collections/matter/scripts/OTBR/otbr_start.sh`

**Comment by OlivierGre** [comment]
I have now upgraded my RPi to Ubuntu 24.04 and installed the version "v2.11-beta3.1+fall2024".

For the moment, I don't succeed to get the OTBR working even in manual mode (so I don't try yet with the TH environment):
The end device doesn't succeed to attach to the OTBR. 

The OTBR has been started with :
`./certification-tool/backend/test_collections/matter/scripts/OTBR/otbr_start.sh`

I'm attaching the log obtained when calling "docker logs otbr-chip". I can see an error when starting the avahi-daemon:
```
 * Starting Avahi mDNS/DNS-SD Daemon avahi-daemon
Failed to open file '/etc/avahi/avahi-daemon.conf': No such file or directory
   ...fail!
```
and some "Failed to write CLI output: Broken pipe"

Do you have an idea why I have this avahi-daemon error?
Thanks

[otbr_logs.txt](https://github.com/user-attachments/files/17112283/otbr_logs.txt)

**Comment by OlivierGre** [comment]
According to this message on Slack (https://csamembers.slack.com/archives/C03MA7WR7Q8/p1668433913997599?thread_ts=1668432778.252049&cid=C03MA7WR7Q8) Avahi should not run at all in OTBR docker. This is mDNSResponder which is used instead. So it is maybe normal to have this error.

**Comment by OlivierGre** [comment]
This issue has been opened for a problem on v2.10.1+spring2024. I'm now on v2.11-beta3.1+fall2024 so I'm closing this issue and I will open a new one for v2.11-beta3.1+fall2024.
