### ISSUE TITLE
[Bug] Test case gets failed by throwing an error

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#42]
From chip-certification-tool created by [KishokG](https://github.com/KishokG): CHIP-Specifications/chip-certification-tool#957  

### Describe the bug

While executing more number of test cases combinedly, the test case gets fail after completion of some test case by throwing below error
> -Test Step Error: Error occurred during execution of test case TC-OZCONC-1.1. sent 1011 (unexpected error) keepalive ping timeout; no close frame received

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the PICS xml file to select the test cases.
2. Selected all the Concentration measurement test case to executed.
3. Executed the below mentioned command to put DUT into a commissionable state, `./chip-all-clusters-app`
4. Click the Start button on Test-Harness user interface.

### Expected behavior

TC should execute successfully without error

### Log files

Execution Logs: [CONCENTRATION_MEASUREMENT.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12548388/CONCENTRATION_MEASUREMENT.log)
Back-end Log: [Backend log.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/12537398/Backend.log.txt)

### PICS file

[Concentration measurement PICS.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12537391/Concentration.measurement.PICS.zip)

### Screenshots

![UI timeout](https://github.com/CHIP-Specifications/chip-certification-tool/assets/133193761/4d7ac8e9-3084-477c-b40e-2682b840e463)

### Environment

**Version:** TH Fall2023
**Sha:** 58a51bef

**Comment by raju-apple** [comment]
@KishokG is the issue only happening if this test case TC-OZCONC-1.1 is part of the list ?

**Comment by raju-apple** [comment]
@raju-apple If we run the UI test runner by selecting any one to two test case there is no issue but when it comes to selecting test more more that 5 or two test case with more number test steps the test runner end with the mentioned error " sent 1011 (unexpected error) keepalive ping timeout; no close frame received"

**Comment by raju-apple** [comment]
SDK Issue open: https://github.com/project-chip/connectedhomeip/issues/29194

**Comment by fabiowmm** [comment]
SDK issue now fixed.
