### ISSUE TITLE
[Bug] DNS Fails on Certification Tool Install 

### ISSUE THREAD

**Issue by sanjaysubbarao** [project-chip/certification-tool#424]
### Describe the bug

DNS Failure causing issues in completing the Certification Tool Download and Front End/Backend Bring Up
Post Installation it gets stuck at bringing up both front end and backend.

### Steps to reproduce the behavior

1. Run the script auto-install.sh under: 
/home/ubuntu/certification-tool/scripts/pi-setup

### Expected behavior

The Script should complete the installation

### Log files

********************************************************************************
update-paa-certs.sh: Checkout SDK sparsely
********************************************************************************
Cloning into 'sdk-sparse'...
fatal: unable to access 'https://github.com/project-chip/connectedhomeip.git/': Could not resolve host: github.com

[TH-Fail.txt](https://github.com/user-attachments/files/17118107/TH-Fail.txt)

DNS resolution fails:

ubuntu@ubuntu:~$ resolvectl status
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub

Link 2 (eth0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlan0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (docker0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Working Case:
ubuntu@ubuntu:~$ resolvectl status
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub

Link 2 (eth0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlan0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: 8.8.4.4 8.8.8.8

Link 4 (docker0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

### Environment

- TH version v2.11-beta3.1+fall2024
- Raspberry Pi Linux ubuntu 6.8.0-1011-raspi 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

- 24.04.1 Server Configured with U: ubuntu  P: raspberrypi

**Comment by fabiowmm** [comment]
@sanjaysubbarao It's probably a network issue. Which site is this?
