### ISSUE TITLE
[Bug] Silent failure to download results file

### ISSUE THREAD

**Issue by cecille** [project-chip/certification-tool#426]
### Describe the bug

When I go to download one specific file, it silently fails to download. I can download it to a different location, and I have no problems downloading other files to this location, but this one file just silently fails. 

### Steps to reproduce the behavior

see video

### Expected behavior

file download.

**Comment by rquidute** [comment]
Hi @cecille It seems the file was not attached to this issue.

**Comment by cecille** [comment]
vid: https://photos.app.goo.gl/22WYwqnuY2Mc8tGT6

results file attached.
[multidevice_ep3_IDM_10_4_PICS_v35.zip](https://github.com/user-attachments/files/17155935/multidevice_ep3_IDM_10_4_PICS_v35.zip)

**Comment by rquidute** [comment]
Thanks @cecille, could you please share your project config and also export your test run execution so we can try to reproduce in our setup?
![Screenshot 2024-09-26 at 19 37 25](https://github.com/user-attachments/assets/ab889c0b-d24d-4e5f-8232-c5608448ab6c)

**Comment by cecille** [comment]
[test_parameters_ep3_failed_to_download_log.txt](https://github.com/user-attachments/files/17170401/test_parameters_ep3_failed_to_download_log.txt)
[Uploading failed_to_download_file.json…]()

**Comment by rquidute** [comment]
Hi @cecille the Test run execution was not attached.

**Comment by fabiowmm** [comment]
Closed due to inactivity.
