### ISSUE TITLE
[Bug] Error while parsing YAML Files

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#43]
From chip-certification-tool created by [rquidute](https://github.com/rquidute): CHIP-Specifications/chip-certification-tool#959  

### Describe the bug

The following test cases are not being displayed in TH because they are falling when parsing the test case.

- Test_TC_SC_4_2
- Test_TC_SC_4_3
- Test_TC_SC_4_4
- Test_TC_SC_4_6

In all YAML script files, the `disabled` property has and extra `.` at the end of the line, ex:  `disabled: true.`

### Steps to reproduce the behavior

1- Launch TH
2-In logs for each test case the following line is printed in backend log:
`ERROR    | 2023-09-06 18:50:23.055 | test_collections.yaml_tests.sdk_yaml_tests:_parse_all_sdk_yaml:82 | Error while parsing YAML File: /app/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_SC_4_2.yaml`

### Expected behavior

TH launches with no parsing errors.

### Log files

```
ERROR    | 2023-09-06 21:12:06.363 | test_collections.yaml_tests.models.yaml_test_parser:parse_yaml_test:57 | 1 validation error for YamlTest
tests -> 0 -> disabled
  value could not be parsed to a boolean (type=type_error.bool)
ERROR    | 2023-09-06 21:12:06.366 | test_collections.yaml_tests.sdk_yaml_tests:_parse_all_sdk_yaml:82 | Error while parsing YAML File: /app/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_SC_4_6.yaml
ERROR    | 2023-09-06 21:12:26.433 | test_collections.yaml_tests.models.yaml_test_parser:parse_yaml_test:57 | 1 validation error for YamlTest
tests -> 0 -> disabled
  value could not be parsed to a boolean (type=type_error.bool)
ERROR    | 2023-09-06 21:12:26.435 | test_collections.yaml_tests.sdk_yaml_tests:_parse_all_sdk_yaml:82 | Error while parsing YAML File: /app/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_SC_4_4.yaml
ERROR    | 2023-09-06 21:12:31.285 | test_collections.yaml_tests.models.yaml_test_parser:parse_yaml_test:57 | 1 validation error for YamlTest
tests -> 0 -> disabled
  value could not be parsed to a boolean (type=type_error.bool)
ERROR    | 2023-09-06 21:12:31.287 | test_collections.yaml_tests.sdk_yaml_tests:_parse_all_sdk_yaml:82 | Error while parsing YAML File: /app/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_SC_4_3.yaml
ERROR    | 2023-09-06 21:12:35.889 | test_collections.yaml_tests.models.yaml_test_parser:parse_yaml_test:57 | 1 validation error for YamlTest
tests -> 0 -> disabled
  value could not be parsed to a boolean (type=type_error.bool)
ERROR    | 2023-09-06 21:12:35.891 | test_collections.yaml_tests.sdk_yaml_tests:_parse_all_sdk_yaml:82 | Error while parsing YAML File: /app/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_SC_4_2.yaml
```

### PICS file

N/A

### Screenshots

N/A

### Environment

- Test Engine version is TH Fall2023
- Test Engine SHA is 22538eb7
- Test Engine SDK SHA is 5ccb774

**Comment by rquidute** [comment]
There was a workaround in code to by pass the parsing error and it was already reverted in this PR: https://github.com/CHIP-Specifications/chip-certification-tool-backend/pull/598, since the YAML scripts was fixed.
