### ISSUE TITLE
[Python script re-run does not check configuration change]  [SVE-1.4]

### ISSUE THREAD

**Issue by SamCullen-Element** [project-chip/certification-tool#432]
### Describe the bug

When running a python script through the UI if you click the "repeat" button the engine does not check the config file it looks like. Between attempts an additional PIXIT item was added and using the "repeat" for a created test run resulted in continued failure while recreating the run of the affected case passes fine.

### Steps to reproduce the behavior

Create a test run of a test that requires a PIXIT
Run the test and let it error and finish
Edit the config to include the PIXIT item
click the "repeat" button on the failed test run

### Expected behavior

project configuration is checked at runtime

**Comment by rquidute** [comment]
Hi @SamCullen-Element Could please provide the project config before and after the changes?
Also could you attach the execution log?

**Comment by SamCullen-Element** [comment]
[Config before.txt](https://github.com/user-attachments/files/17160866/Config.before.txt)
[TC-ICDM-3-4_WaI2fOmQ_2024_09_26_17_14_53.log](https://github.com/user-attachments/files/17160867/TC-ICDM-3-4_WaI2fOmQ_2024_09_26_17_14_53.log)
[Config after.txt](https://github.com/user-attachments/files/17160868/Config.after.txt)

**Comment by rquidute** [comment]
Hi @SamCullen-Element according to the logs, it seems the `PIXIT.WAITTIME.REBOOT` attribute was set like this: 

>  ...
>  "test_parameters": {
>       ...
>       "PIXIT.WAITTIME.REBOOT":"5"
>     }
>     ...

So, it was not same way you sent in the `Config.after.txt` file.

This is how the commissioning command looks like, according to your logs: `Sending command to SDK container: python3 /root/python_testing/scripts/sdk/test_harness_client.py commission --trace-to json:log --commissioning-method ble-thread --thread-dataset-hex 0e08000000000001000035060004001fffe00708fd7d36cb3919b15c0410b33c6002c978b0648962d5b0996733950c0402a0f7f8000300000f0102123402081111111122222222051000112233445566778899aabbccddeeff030444454d4f --discriminator 1278 --passcode 21992716 --endpoint 0 --PIXIT.WAITTIME.REBOOT 15`

In my setup, the log printed looks like this: `Sending command to SDK container: python3 /root/python_testing/scripts/sdk/test_harness_client.py commission --trace-to json:log --commissioning-method ble-thread --thread-dataset-hex 0e08000000000001000035060004001fffe00708fd7d36cb3919b15c0410b33c6002c978b0648962d5b0996733950c0402a0f7f8000300000f0102123402081111111122222222051000112233445566778899aabbccddeeff030444454d4f --discriminator 1278 --passcode 21992716 --endpoint 0 --int-arg PIXIT.WAITTIME.REBOOT:5`


The `int-arg` is missing (`--int-arg PIXIT.WAITTIME.REBOOT:5`). 
Could you please double check the project config and try again?
The project config should look like this:
>  ...
>  "test_parameters": {
>       ...
>       "int-arg": "PIXIT.WAITTIME.REBOOT:5"
>     }
>     ...

**Comment by SamCullen-Element** [comment]
Hi @rquidute, I confirm the test parameter was entered as you suggested at run time, I had another attendee review the config when I was looking into why the script was erroring and neither of us could see an issue with how the PIXIT was entered.
This may be part of another issues I experienced with the test harness image, as it did not install all components correctly but informed that it had and we are resolving this in another issue chain.

**Comment by rquidute** [comment]
Hi @SamCullen-Element This issue can be closed then? Do you have any other concern regarding this issue?

**Comment by SamCullen-Element** [comment]
@rquidute that was my only concern on this topic. If I note it again I will re-open, cheers.
