### ISSUE TITLE
[Matter v1.4 SVE] TC_SWTCH_2_6 Fails on 7b: Not Applicable for My Device

### ISSUE THREAD

**Issue by VaishaliAvhale** [project-chip/certification-tool#433]
### Describe the bug

I have executed TC_SWTCH_2_6 . 4a, 5a and 6a step passed. step from 7a isn't applicable for esp_generic_switch because we are not supporting MSL feature. So it is expected that the TC should pass but it is failing.please find the failure logs.

### Steps to reproduce the behavior

commission generic switch and execute TC_SWTCH_2_6

### Expected behavior

It should pass because steps from 7a NA for my DUT

### Log files

[TC-SWTCH-2-6-sep-27-count3-esp32c3.log](https://github.com/user-attachments/files/17160284/TC-SWTCH-2-6-sep-27-count3-esp32c3.log)
[TC-SWTCH-2-6-sep-27-count3-TH.log](https://github.com/user-attachments/files/17160286/TC-SWTCH-2-6-sep-27-count3-TH.log)

### Screenshots

![Screenshot from 2024-09-27 12-09-55](https://github.com/user-attachments/assets/a0480c07-5dff-405e-bfba-ce85376beb5b)

**Comment by hiltonlima** [comment]
@raul-marquez-csa , could you take a look on this?
