### ISSUE TITLE
[Bug] [Matter 1.4 SVE] [v2.11beta3.1+fall2024] [TC-IDM-10.5] PIXIT.IDM.ALLOW_EXTRA_CLUSTERS_ON_ENDPOINT:true is not passed to the script

### ISSUE THREAD

**Issue by SirRu24** [project-chip/certification-tool#435]
### Describe the bug

All clusters app tested with the argument PIXIT.IDM.ALLOW_EXTRA_CLUSTERS_ON_ENDPOINT:true returned FAILED

### Steps to reproduce the behavior

Test parameter:
    "test_parameters": {
      "timeout": "100000000",
      "bool-arg": "allow_provisional:true PIXIT.IDM.ALLOW_EXTRA_CLUSTERS_ON_ENDPOINT:true"
    }

Run the UI Python of TC-IDM-10.5

### Expected behavior

It should have return PASS because all clusters app run multiple device clusters and it can only have one device type.

### Log files

[TC-IDM-10-5_2024_09_27_08_25_20.log](https://github.com/user-attachments/files/17161962/TC-IDM-10-5_2024_09_27_08_25_20.log)

### Environment

TH version: v2.11beta3.1+fall2024

**Comment by fabiowmm** [comment]
Originator seems to have lost interest. Please reopen if still facing the issue.
