### ISSUE TITLE
[Bug] TC-CADMIN-1.24 Test-steps are skipped in UI.

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#44]
From chip-certification-tool created by [Saravana-kr22](https://github.com/Saravana-kr22): CHIP-Specifications/chip-certification-tool#960  

### Describe the bug

While executing the TC-CADMIN-1.24 in UI test-step 6 is skiped and step is not executed in UI . The test case ended with the below message:

> INFO       | 2023-09-07 06:38:30.852489 | Stopping chip-tool container
INFO       | 2023-09-07 06:38:31.395283 | Test Suite Completed [PENDING]: FirstChipToolSuite
INFO       | 2023-09-07 06:38:31.404772 | Test Run Completed [PENDING]

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the PICS xml file to select the test cases.
2. Select TC-cadmin-1.24 test case to executed.
3. Advertise the Dut using the command `./chip-all-clusters-app`
4. Click the Start button on Test-Harness user interface.

### Expected behavior

All the test step should be executed as the Pics used.

### Log files

UI-log:  [cadmin-1-24.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12545910/casdmin-1-24.log)
UI-report - [cadmin-1-24.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12545915/cadmin-1-24.zip)

### PICS file

[cadmin-pics.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12545923/cadmin-pics.zip)

### Screenshots

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/104007654/56c0f996-d394-4c37-85f5-43c8ba5a66f0)

### Environment

TH Version:TH Fall2023
OS: Ubuntu
Browser: Chrome

**Comment by raju-apple** [comment]
@gladystonfranca It seems that there is a issue with the Test Harness. When execute certification testing for product, can the test be performed manually?

**Comment by raju-apple** [comment]
This issue is not resolved in `TH-Fall2023_bug_fixes`

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/104007654/6e839ffd-dc64-4bb9-8a7f-db251f3e78c2)

**Comment by fabiowmm** [comment]
Seems to have been fixed. No new reports.
