### ISSUE TITLE
[Bug] PICS tool bug - PICS tool does not complain about blank base.xml

### ISSUE THREAD

**Issue by cecille** [project-chip/certification-tool#449]
### Describe the bug

If you either omit or put a blank base.xml, nothing will stop you. That seems dangerous

**Comment by sander-gitl** [comment]
This would apply to all PICS that you load and for which no selection is made imho: all of them are optional, and as you load them you would assume you select at least 1 item. Might suffice to produce a generic warning/error if you do try to do this with any PICS.

**Comment by sander-gitl** [comment]
Fixed in latest 2.1.19 release.
