### ISSUE TITLE
[Bug] Test case gets failed by throwing an error

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#45]
From chip-certification-tool created by [Saravana-kr22](https://github.com/Saravana-kr22): CHIP-Specifications/chip-certification-tool#961  

### Describe the bug

While running the TC-CADMIN-1.21 and 1.22 test case in Step 4: TH_CR1 reads the window status to verify the DUT_CE window is closed test case is failed with the error: 

> Test Step Error: Error occurred during execution of test case TC-CADMIN-1.21. no close frame received or sent

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the PICS xml file to select the test cases.
2. Select TC-CADMIN-1.21 or TC-CADMIN-1.22 test case to executed.
3. Advertise the Dut using the command `./chip-all-clusters-app`
4. Click the Start button on Test-Harness user interface.

### Expected behavior

Test case should executed without any error.

### Log files

UI-log:  [cadmin-log.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12547667/cadmin-log.zip)
UI-reports:  [cadmin-report.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12547686/cadmin-report.zip)

### PICS file

[cadmin-pics.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12547690/cadmin-pics.zip)

### Screenshots

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/104007654/877cb436-b73d-4032-a6e5-e191fa4f306f)

### Environment

TH Version:TH Fall2023
OS: Ubuntu
Browser: Chrome

**Comment by raju-apple** [comment]
This issue is not resolved in `TH-Fall2023_bug_fixes ` 

 ![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/104007654/fd940800-343b-47ad-9751-8f1348e0d181)

**Comment by fabiowmm** [comment]
SDK issue fixed.
