### ISSUE TITLE
[Bug] PICS tool bugs - PICS tool allows double-loading PICS files

### ISSUE THREAD

**Issue by cecille** [project-chip/certification-tool#454]
### Describe the bug

If you load the same file twice, the PICS tool doesn't complain, so it's possible to make changes to and save the incorrect file.

### Steps to reproduce the behavior

load same file twice. It just appears twice. When you do save all files, weird stuff happens.

### Expected behavior

Reject opening XML files that are already loaded in the tool.

**Comment by sander-gitl** [comment]
Fixed in latest 2.1.19 release.
