### ISSUE TITLE
[Bug] Test step markers do not appear in the test logs from the TH

### ISSUE THREAD

**Issue by cecille** [project-chip/certification-tool#458]
### Describe the bug

The prints don't appear in the logs. I thought the TH was going to handle this, but apparently not. I will fix this in the test framework.

### Steps to reproduce the behavior

Look at logs - there are no test step markers in the TH when run from the GUI.

### Expected behavior

Test step markers appear

**Comment by fabiowmm** [comment]
@rquidute can you check with Cecile what's happening here?

**Comment by rquidute** [comment]
@cecille I created this PR, could you review? https://github.com/project-chip/connectedhomeip/pull/36070

**Comment by rquidute** [comment]
Once this PR https://github.com/project-chip/connectedhomeip/pull/36070 was merged, TH is now presenting the test step markers:

<img width="1293" alt="Screenshot 2024-10-23 at 14 17 41" src="https://github.com/user-attachments/assets/a88becff-6d3d-4562-b20c-e51363d2ca2c">
