### ISSUE TITLE
[TC-WNCV-4.2] The test case is failing due to an OperationalStatus attribute value mismatch when executed along with other Window Covering Test cases

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#46]
From chip-certification-tool created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-certification-tool#962  

### Describe the bug

[TC-WNCV-4.2] The test case is failing due to an OperationalStatus attribute value mismatch when executed along with other Window Covering Test cases but It passes when executed individually

**PFA Screenshot of individual Run**
![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/95841834/de5ae149-65fd-43a1-b846-d1fe23393bae)

**PFA Screenshot when TC executed  along with other Window Covering Test cases**
![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/95841834/d6716cb8-12b5-47d9-a3e4-56e3e0368f97)

### Log files

**PFA log of individual Run**

[UI_Test_Run_2023_09_07_16_08_40(1).log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12547737/UI_Test_Run_2023_09_07_16_08_40.1.log)

**PFA log when TC executed  along with other Window Covering Test cases**
[UI_Test_Run_2023_09_07_16_06_07.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12547754/UI_Test_Run_2023_09_07_16_06_07.log)

### PICS file

[Window Covering Cluster Test Plan.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/12548343/Window.Covering.Cluster.Test.Plan.txt)

Additional Info:
Version: TH Fall2023
Sha: 58a51bef

**Comment by raju-apple** [comment]
During my analysis, I noticed that if steps `1a` and `1b` are commented in `TC-WNCV-4.2` YAML script, the test case passes individually and also along with other test case. Does it make sense to remove the steps from test plan?

- `TC-WNCV-4.2` individual run
![Screenshot 2023-09-14 at 15 43 51](https://github.com/CHIP-Specifications/chip-certification-tool/assets/116586593/f7a77647-62db-410e-8213-76a947097bd6)

- `TC-WNCV-4.2` along with other test case
![Screenshot 2023-09-14 at 15 44 11](https://github.com/CHIP-Specifications/chip-certification-tool/assets/116586593/150e8b80-b387-4885-af62-5495c08caf8d)

**Comment by rquidute** [comment]
Hi @Rajashreekalmane in the related step (3b) it is asked: `Motion should be over with OperationalStatus Value of bits 0..5 must be xx000000b` but in the YAML file shows:
```
### Check for END OF MOVEMENTs
    - label: "Step 3b: TH reads OperationalStatus attribute from DUT"
      command: "readAttribute"
      attribute: "OperationalStatus"
      PICS: WNCV.S.A000a
      response:
          value: 0
```
So I performed a test by changing `value: 0` to `value: 0x0000000`, and it keeps failing for the same reason as before: `Test Failure: The test expectation "value (10) == 0" is false`

In another scenario, just for testing (Not sure if it make sense), I commented out the init step and the test execution was successfully when this test is running alone and running after `TC-WNCV-4.1`. I commented the init step in both `TC-WNCV-4.1` and  `TC-WNCV-4.2`.

The related step that I commented out during my test.
```
    - label:
          "Step 1a: TH sends DownOrClose command to preposition the DUT in the
          opposite direction"
      command: "DownOrClose"
      PICS: WNCV.S.C01.Rsp
```

CC @cecille

**Comment by fabiowmm** [comment]
SDK issue fixed.
