### ISSUE TITLE
[Bug] [v2.10+spring2024-tag] V1.3 TH installation is failing due to the linux-modules-extra-raspi.

### ISSUE THREAD

**Issue by NNAA0917** [project-chip/certification-tool#490]
### Describe the bug

While running ./scripts/pi-setup/auto-install.sh getting below error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 satisfy:command-line : Depends: linux-modules-extra-raspi (>= 5.15.0.1046.44) but it is not installable
E: Unable to correct problems, you have held broken packages.
### Steps to reproduce the behavior

1. Install the Ubuntu Server 22.04.1 LTS (64-bit) in the SD card.
2. After the SD card has been flashed, place it in the Raspberry Pi’s memory card slot.
3. Power on the Raspberry Pi and ensure that the local area network, display monitor and keyboard are connected.
4. git clone -b v2.10.2+spring2024 https://github.com/project-chip/certification-tool.git
5. cd certification-tool
6. git submodule update --init --recursive
7. ./scripts/pi-setup/auto-install.sh

### Expected behavior

Th should be installed without an issues.

### Environment

TH version: v2.10.2+spring2024
OS:ubuntu Server 22.04.1 LTS (64-bit)

**Comment by NNAA0917** [comment]
This no longer occurs due to the following

1.git clone https://github.com/project-chip/certification-tool.git
2.cd certification-tool
3./scripts/pi-setup/auto-install.sh
4.git checkout tags/v1.0.0

**Comment by NNAA0917** [comment]
Sorry, still
git clone -b v2.10.2+spring2024 https://github.com/project-chip/certification-tool.git
After running . /scripts/pi-setup/auto-install.sh
I get the following error



Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
satisfy:command-line : Depends: linux-modules-extra-raspi (>= 5.15.0.1046.44) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by NNAA0917** [comment]
This problem no longer occurs on ubuntu 22.04.5.

**Comment by LookAtThisTree** [comment]
According to:
https://answers.launchpad.net/ubuntu/+source/linux-raspi/+question/817506
this packet is no longer needed, I removed it (and after solving much more issues related to the newer available packet versions compared to required) it seems to work fine.

**Comment by st-mediola** [comment]
Probably a good idea to state the actual OS requirement in the TH doc on master branch, there's a reference to the fact that older TH versions may need a different Ubuntu version but e.g. the table you look at for the tag doesn't mention anything

**Comment by fabiowmm** [comment]
@rquidute please confirm this is solved.

**Comment by rquidute** [comment]
This issue does not happen using OS: ubuntu Server 24.04 LTS (64-bit)

**Comment by fabiowmm** [comment]
@rquidute what about the UG? I know we recently added something to this effect.

**Comment by rquidute** [comment]
UG section 4 states: **The TH runs on the official Ubuntu Server 24.04 LTS (64-bit) version**
