### ISSUE TITLE
[Bug] Typo in readme file

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#51]
From chip-certification-tool created by [hicklin](https://github.com/hicklin): CHIP-Specifications/chip-certification-tool#973  

### Describe the bug

The readme file indicates that the `start.sh` script is in the root folder. This is not correct as it is in the `scripts` folder.

### Steps to reproduce the behavior

1. Read the readme
2. look for the file

### Expected behavior

The file is where the readme says it is.

**Comment by raju-apple** [comment]
Hi @hicklin, Could you please refer to `Matter User Guide` at docs folder? The modifications in Readme is under analysis.

**Comment by raju-apple** [comment]
@hicklin please use the Matter User Guide , @fabiowmm please update the readme accordingly

**Comment by fabiowmm** [comment]
Fixed. Awaiting QA.
