### ISSUE TITLE
[Bug] Typo or missing functionality

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#52]
From chip-certification-tool created by [hicklin](https://github.com/hicklin): CHIP-Specifications/chip-certification-tool#974  

### Describe the bug

The readme suggests that all one needs to do to get the TH running in to execute the `start.sh` file. The readme says that this should install all the TH dependencies. This is not quite correct as the script fails due to missing docker tools such as docker-compose.

The readme doesn't say that these tools should be installed beforehand. If this is expected, maybe an extra point could be added to note this like the points for setting up ssh.

### Steps to reproduce the behavior

1.  Follow the read me and run the `start.sh` script in a new RPi.
2.  Note that you get an error due to missing dependencies.

**Comment by raju-apple** [comment]
Hi @hicklin, Could you please refer to `Matter User Guide` at docs folder? The modifications in Readme is under analysis.

**Comment by raju-apple** [comment]
@hicklin please use the Matter User Guide , @fabiowmm please update the readme accordingly

**Comment by fabiowmm** [comment]
Fixed. Awaiting QA.
