### ISSUE TITLE
[Bug] Incorrectly configured docker-compose.yaml

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#53]
From chip-certification-tool created by [hicklin](https://github.com/hicklin): CHIP-Specifications/chip-certification-tool#975  

### Describe the bug

After setting up an new RPi with ssh access, cloning this repository on the RPi and install all the required docker tools, I ran the `start.sh` and got the following error.

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name', 'enable_ipv6' were unexpected)
```

It seems that either the readme is incorrect, there is something wrong with the `start.sh` script or there is a misconfiguration in the `docker-compose.yaml`.

### Steps to reproduce the behavior

1. Follow the readme until running the `start.sh` script.
2. Install the docker tools. 
    1. `curl -fsSL https://get.docker.com -o get-docker.sh` and run the script.
    2. `sudo apt install docker-compose`.
4. run the `start.sh` script.

### Expected behavior

The readme gives a code snippet of what is to be expected that after running the `start.sh` script.

**Comment by raju-apple** [comment]
Could you please refer to `Matter User Guide` at docs folder? The modifications in Readme is under analysis.

**Comment by raju-apple** [comment]
@hicklin please use the Matter User Guide , @fabiowmm please update the readme accordingly

**Comment by fabiowmm** [comment]
Fixed. Awaiting QA.
