### ISSUE TITLE
[Bug] TH hangs after closing a prompt from a simulated test

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#55]
From chip-certification-tool created by [ccruzagralopes](https://github.com/ccruzagralopes): CHIP-Specifications/chip-certification-tool#983  

### Describe the bug

The test execution in TH is hanging when the user closes a prompt from a test step in a simulated test case.

### Steps to reproduce the behavior

1. Run a simulated test case in TH (e.g.: `TC-LVL-2.3`)
2. Complete pairing as instructed during test suite setup
3. Close a prompt from a test step

### Expected behavior

I expected the test case to finish with an error, which is what happens for manual test cases and chip-tool test cases

### PICS file

[PICS.zip](https://github.com/CHIP-Specifications/chip-certification-tool/files/12731844/PICS.zip)

### Screenshots

<img width="2160" alt="Screenshot 2023-09-26 at 17 58 10" src="https://github.com/CHIP-Specifications/chip-certification-tool/assets/116589288/38358a77-43e9-49f7-827b-8e4629cb63d1">

### Environment

TH Fall2023

**Comment by raju-apple** [comment]
The team discussed this over slack and decided that handling it only in the TH side is not the best option. First the runner should add a method for aborting the test case and then TH can call this method when a prompt is cancelled.
The runner issue created for this is:
- https://github.com/project-chip/connectedhomeip/issues/29515

**Comment by fabiowmm** [comment]
Deprioritized.
