### ISSUE TITLE
[Bug] UI Error During Multiple Test Case Validation: Code 1011 - Keepalive Ping Timeout and Missing Close Frame in TV-APP

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#57]
From chip-certification-tool created by [Rajashreekalmane](https://github.com/Rajashreekalmane): CHIP-Specifications/chip-certification-tool#986  

### Describe the bug

If we run the UI test runner by selecting one or two test cases, there are no issues. However, when selecting more than five test cases or two test cases with a larger number of test steps, the test runner ends with the following error: 'Sent 1011 (unexpected error) keepalive ping timeout; no close frame received.

### Steps to reproduce the behavior

- From the Test-Harness user interface loaded the PICS xml file to select the test cases.
- Selected all the Concentration measurement test case to executed.
- Executed the below mentioned command to put DUT into a commissionable state, ./chip-tv-app 
- Click the Start button on Test-Harness user interface.

### Log files

[automated_2023_10_05_11_24_49.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12812886/automated_2023_10_05_11_24_49.log)

### PICS file

[Media Cluster Test Plan.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/12812873/Media.Cluster.Test.Plan.txt)

### Screenshots

![image](https://github.com/CHIP-Specifications/chip-certification-tool/assets/95841834/fce3aad0-d448-4a95-bd1e-64ec250ffb6b)

### Environment

Version : TH Fall2023
Sha : 3f84bff5
DUT : tv-app

**Comment by raju-apple** [comment]
I couldn't identify why this is happening, but I found that the error is happening in the `_run` function from `TestRunner` in [runner.py](https://github.com/project-chip/connectedhomeip/blob/master/scripts/py_matter_yamltests/matter_yamltests/runner.py). There's a big `try:except:` there, not sure where exactly the exception is being fired though.

**Comment by raju-apple** [comment]
There's an open issue in the SDK repo for this error: https://github.com/project-chip/connectedhomeip/issues/29194

**Comment by fabiowmm** [comment]
Deprioritized.
