### ISSUE TITLE
[Bug] TC-CADMIN-1.6 consistently failed during clean up.

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#59]
From chip-certification-tool created by [yinyihu-silabs](https://github.com/yinyihu-silabs): CHIP-Specifications/chip-certification-tool#995  

### Describe the bug

While running TC-CADMIN-1.6, after Step 12, during `unpairing chip_tool_from device`, test ran into error
```
INFO       | 2023-10-19 17:37:34.887718 | Executing Test Step: Step 12: TH_CR2 starts a commissioning process on DUT_CE
INFO       | 2023-10-19 17:38:05.169099 | Test Step Completed [PASSED]: Step 12: TH_CR2 starts a commissioning process on DUT_CE
INFO       | 2023-10-19 17:38:05.179263 | Executing Test Step: DUT_CE is commissioned by TH_CR2
INFO       | 2023-10-19 17:38:05.184443 | Test Step Completed [PASSED]: DUT_CE is commissioned by TH_CR2
INFO       | 2023-10-19 17:38:05.191108 | Test Case Completed[PENDING]: TC-CADMIN-1.6 (Semi-automated)
INFO       | 2023-10-19 17:38:05.198615 | Unpairing chip_tool from device
ERROR      | 2023-10-19 17:38:15.587297 | Test Suite Error: Error occurred during cleanup of test suite FirstChipToolSuite. Connecting to ws://172.18.0.1:9002 failed.
INFO       | 2023-10-19 17:38:15.602690 | Test Suite Completed [ERROR]: FirstChipToolSuite
INFO       | 2023-10-19 17:38:15.616839 | Test Run Completed [ERROR]
```
Other cadmin tests such as 1.10, 1.16, 1.23 do not experience the same issue

### Log files

[cadmin-1-6_2023_10_19_13_32_32.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/13046116/cadmin-1-6_2023_10_19_13_32_32.log)

### Screenshots

![Screenshot 2023-10-19 at 2 03 09 PM](https://github.com/CHIP-Specifications/chip-certification-tool/assets/83772323/b37b31b0-f74e-4459-987a-57ef5dbc9b4b)

### Environment

![Screenshot 2023-10-19 at 2 03 46 PM](https://github.com/CHIP-Specifications/chip-certification-tool/assets/83772323/87db8438-8210-4c3f-8eb0-0a67ce882134)

**Comment by fabiowmm** [comment]
@ccruzagralopes same?

**Comment by ccruzagralopes** [comment]
> @ccruzagralopes same?

No, this is something else. The other issues were specifically related to simulated tests.

**Comment by rquidute** [comment]
It seems the timeout defined in YAML file for this test case its not enough (300).
@manjunath-grl , maybe the timeout should be increase in YAML test script? 
Another solution, the user may include the  timeout in project configuration as bellow:
```
"test_parameters": {
      "timeout": 600
    }
```

**Comment by rquidute** [comment]
The originator(`yinyihu-silabs`) from the bug in the previous repo is not listed here.

**Comment by fabiowmm** [comment]
Deprioritized.
