### ISSUE TITLE
[Bug] The submit button is not appearing

### ISSUE THREAD

**Issue by hiltonlima** [project-chip/certification-tool#60]
### Describe the bug

The submit button is not appearing in the first step of the Test Case: TC-DD-1.1

### Steps to reproduce the behavior

Run the TH 
Select python_tests suite
Select TC-DD-1.1 
Run

### Expected behavior

The button should appear

### PICS file

Color Control Cluster .xml
On-Off Cluster .xml

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/116589806/379b8255-444e-43b5-9e9a-4202eaa73214)

### Environment

TH environment built from the public repository

**Comment by fabiowmm** [comment]
@raul-marquez-csa this needs to be corrected on the frontend or it will block a number of tests. The backend fix is already merged. For details, ask @hiltonlima

**Comment by rquidute** [comment]
Hi @raul-marquez-csa, the popup for ` upload file` is still not displaying the submit button.

- Popup displayed:
<img width="1157" alt="Screenshot 2023-11-17 at 18 35 54" src="https://github.com/project-chip/certification-tool/assets/116586593/c1834271-8667-4aa0-acc2-f0ec6618cd1e">

- Popup displayed after file is selected:
<img width="1159" alt="Screenshot 2023-11-17 at 18 36 11" src="https://github.com/project-chip/certification-tool/assets/116586593/2ec8442f-c361-49ec-a7f3-20ec36f9ac1c">

**Comment by raul-marquez-csa** [comment]
PRs addressing latest feedback:

Frontend: [Missing submit button #15](https://github.com/project-chip/certification-tool-frontend/pull/15)
Backend: [Prompt request refactor #31](https://github.com/project-chip/certification-tool-backend/pull/31)

**Comment by hiltonlima** [comment]
Fixed in release [v2.10-beta1.1+spring2024](https://github.com/project-chip/certification-tool/releases/tag/v2.10-beta1.1%2Bspring2024)
