### ISSUE TITLE
[Suggestion] Tool unit testcase for stress testing

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#61]
From chip-certification-tool-frontend created by [karthick-grl](https://github.com/karthick-grl): CHIP-Specifications/chip-certification-tool-frontend#133  

Initial testcases proposed,
1. Testcase to populate continues console logs (may be in millions) top check if UI can handle it properly
2. Need a script that populates database with 200+ project entries and 500+ test execution entries so we could check if UI could populate everything in pagination correctly

**Comment by raju-apple** [comment]
@raul-marquez-csa this was more an ask for writing some unit tests in the front-end

**Comment by fabiowmm** [comment]
Deprioritized.
