### ISSUE TITLE
Pop-up doesn't show up after refreshing the page during test execution

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#62]
From chip-certification-tool-frontend created by [du48s03](https://github.com/du48s03): CHIP-Specifications/chip-certification-tool-frontend#169  

The pop-up for the test instructions doesn't show up after refreshing the page during test execution. 
That means one cannot continue the test after, for example, the ip address of the TH has been reassigned. 

The same problem happens if the user has not given a response for too long. The test step will fail, and TH will move on to the next test step. However, the pop-up for the next test step will not show up, preventing the user from giving any further input, and can only abort the entire test run. 

![image](https://user-images.githubusercontent.com/6725378/183993243-8d9a44d3-5cc0-4132-afb6-91a0710dd300.png)

**Comment by raju-apple** [comment]
>The pop-up for the test instructions doesn't show up after refreshing the page during test execution.
That means one cannot continue the test after, for example, the ip address of the TH has been reassigned.

Yes, this is still a case. But, we have a typical way to fix this. UI can have a even listener for `window.onbeforeunload`  which will be triggered while refresh, browser tab exit or browser window exit. We may have end point in backend on this trigger and make the backend to resend the pop-up message again. 

>The same problem happens if the user has not given a response for too long. The test step will fail, and TH will move on to the next test step. However, the pop-up for the next test step will not show up, preventing the user from giving any further input, and can only abort the entire test run.

This should be solved already. I remember we have introduced the timeout for pop-ups.

**Comment by raju-apple** [comment]
> Yes, this is still a case. But, we have a typical way to fix this. UI can have a even listener for `window.onbeforeunload` which will be triggered while refresh, browser tab exit or browser window exit. We may have end point in backend on this trigger and make the backend to resend the pop-up message again.

This is the suggested approach to fix this, correct?

Also, the log window isn't recovered after refresh, see below.

https://github.com/CHIP-Specifications/chip-certification-tool-frontend/assets/130402456/457b1a11-7249-4dec-b7a4-97f5c2b96fab

I'll open a separate issue for the log/refresh.

**Comment by raju-apple** [comment]
>This is the suggested approach to fix this, correct?

Yes that is the suggested approach. Which requires a new backend endpoint support. 

>Also, the log window isn't recovered after refresh, see below.

This is also a case, during refresh the logs in buffer would be cleared and so we would not have any of the previous logs to display. But, if the testcase is still running you should be able to see new logs but the old one. Perhaps, the same approach suggested for pop-up can be adopted here aswell.

**Comment by fabiowmm** [comment]
Deprioritized.
