### ISSUE TITLE
[Feature] Drag and Drop PICS Files

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#63]
From chip-certification-tool-frontend created by [antonio-amjr](https://github.com/antonio-amjr): CHIP-Specifications/chip-certification-tool-frontend#191  

This is a feature request.
Let me know if it's easy/possible as well.

Would be great to be able to drag and drop PICS files directly on the "Project Edit" window.

<img width="1119" alt="Captura de Tela 2023-09-06 às 9 58 49 AM" src="https://github.com/CHIP-Specifications/chip-certification-tool-frontend/assets/116589331/432ce8b1-5058-4ed2-8e58-b93bb0935089">

**Comment by raul-marquez-csa** [comment]
Addressed in this PR: https://github.com/project-chip/certification-tool-frontend/pull/11

**Comment by fabiowmm** [comment]
Complete.
