### ISSUE TITLE
[Phase2] When the test harness prompts the User to decommission, it always fails.

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#65]
From chip-certification-tool-backend created by [krypton36](https://github.com/krypton36): CHIP-Specifications/chip-certification-tool-backend#552  

Summary:
In phase 2, the structure of the backend chip app changed. Since we no longer spawn chip-app1 every test, we need a way to allow for decommissioning of the controller. 

Proposed Solution:
Create a TestStep/TestSuite using the open source runner and inject into config.

**Comment by fabiowmm** [comment]
@ccruzagralopes is this the same as https://github.com/project-chip/certification-tool/issues/40 ?

**Comment by ccruzagralopes** [comment]
> @ccruzagralopes is this the same as #40 ?

Yes

**Comment by ccruzagralopes** [comment]
Closing because it's a duplicate of #40
