### ISSUE TITLE
Test_run_execution class operator variable are lazy loaded from DB

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#67]
From chip-certification-tool-backend created by [sholagi](https://github.com/sholagi): CHIP-Specifications/chip-certification-tool-backend#296  

In #289, we introduced a workaround to ensure operator was explicitly loaded (wasn't before due to lazy loading).

This should be refactored, to use `from_orm` in pydantic directly on the new model, once they allow us to pass additional values for the new model eg. test_run_stats. This will let the schema handle the loading of the operator.
see: https://github.com/samuelcolvin/pydantic/pull/3375

Related PR: https://github.com/CHIP-Specifications/chip-certification-tool-backend/pull/289
Related Issue: https://github.com/CHIP-Specifications/chip-certification-tool-backend/issues/276

**Comment by fabiowmm** [comment]
Deprioritized.
