### ISSUE TITLE
[Bug]  get802154RadioUrl() at system.cpp:100: InvalidArgument

### ISSUE THREAD

**Issue by chuckrui** [project-chip/certification-tool#78]
### Describe the bug

Building the Thread network from the script file failed due to an invalid parameter for the Radio URL, probably because` /dev/radio `could not be found, but` /dev/ttyACM0` is present. 
RCP firmware I burn is a replication `ncs/v2.3.0 / samples/openthread/coprocessor`. But the odd thing is that the failure only exists on the UBuntu PC (x86_64), which means that the same hardware on the Raspberry PI 4B and the same script to build the Thread network are running without any problems.

### Steps to reproduce the behavior

1.flash RCP FW
2.connect to Pc
3.run otbr_start.sh

### Expected behavior

otbr_start.sh can be successfully run on Ubuntu Pc(x86_64) as on Rasberry PI 4B, as shown below.
![image](https://github.com/project-chip/certification-tool/assets/76715008/8f610b65-3453-4d8a-ae40-cf2091d7a23f)

### Log files

Ubuntu PC:
[otbr_start.txt](https://github.com/project-chip/certification-tool/files/13223195/otbr_start.txt)

### Environment

Raspberry Pi 4B:
```
chuckrui@ubuntu:~/matter/certification-tool/scripts/OTBR$ uname -a
Linux ubuntu 5.4.0-1096-raspi #107-Ubuntu SMP PREEMPT Fri Oct 6 10:46:58 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Ubuntu PC:
```
chuck@chuck-rui:/home$ uname -a
Linux chuck-rui 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hiltonlima** [comment]
Thanks for the feedback. Currently Thread support is only for Raspberry Pi.

Please reopen the issue if you feel necessary.
