### ISSUE TITLE
Python tests in TH UI -  Run Python Test on its own SDK Container

### ISSUE THREAD

**Issue by gladystonfranca** [project-chip/certification-tool#79]
### Feature description

This issue is related to executing  Python tests in TH UI.

Provide support on TH  for executing  Python Tests on its own  SDK container 

### Use Cases

[Use Case] Start  container for test execution.

**Comment by rquidute** [comment]
PR for this implementation: https://github.com/project-chip/certification-tool-backend/pull/19
