### ISSUE TITLE
Matter_TH_User_Guide's question about TH installation without a Raspberry Pi

### ISSUE THREAD

**Issue by HirokiOgawa1129** [project-chip/certification-tool#86]
### Describe the bug

Is the following value OK for SDK_DOCKER_TAG described in the document?
![image](https://github.com/project-chip/certification-tool/assets/33824269/727ee6a9-8d60-44a5-b9c0-9d542a60d232)
If there is no problem with the above, will the following build command be like this?
docker buildx build --load --build-arg COMMITHASH=19771ed7101321d68b87d05201d42d00adf5368f --tag connectedhomeip/chip-cert-bins:19771ed7101321d68b87d05201d42d00adf5368f
![image](https://github.com/project-chip/certification-tool/assets/33824269/37d31a1a-0b76-4f63-a7b1-28e32cd194da)
I tried building with the above command, but I get a command error, so if there is a problem with the procedure, please let me know.

**Comment by ccruzagralopes** [comment]
Hi @HirokiOgawa1129, the command is missing the `.` (dot). at the end.
Can you please share the output with the error?

**Comment by HirokiOgawa1129** [comment]
Hi,[ccruzagralopes](https://github.com/ccruzagralopes)
Below is the error result.
![image](https://github.com/project-chip/certification-tool/assets/33824269/c0d90c1d-1864-4deb-9591-d7d3be4fd381)

**Comment by ccruzagralopes** [comment]
Hey @HirokiOgawa1129, I can't tell from the screenshot, but is there a space between the tag and the dot? If there isn't, please add it and try again.

`docker buildx build --load --build-arg COMMITHASH=19771ed7101321d68b87d05201d42d00adf5368f --tag connectedhomeip/chip-cert-bins:19771ed7101321d68b87d05201d42d00adf5368f .`

**Comment by HirokiOgawa1129** [comment]
Hi,[ccruzagralopes](https://github.com/ccruzagralopes)
I'm sorry for replying late.
I solved it by putting a space between the dots.
Thanks for your cooperation.
