### ISSUE TITLE
RasPi image can't be updated following the "4.1 Update Existing TH" instructions in the user guide

### ISSUE THREAD

**Issue by zacwbond** [project-chip/certification-tool#91]
### Describe the bug

It doesn't seem possible to follow the "update existing TH" instructions because the [linked image](https://drive.google.com/drive/folders/1vZbfqRWNrttJOUZbYskKJaGGdOm54ugq?usp=sharing) seems to have been built from some private(?) GitHub repository called `CHIP-Specifications/chip-certification-tool.git`.  Without access to that repo, the `git fetch` command fails.

It would be better to build the image from the current version of the public repo so that the names and documentation match the public version.

**Comment by ccruzagralopes** [comment]
Hi @zacwbond, TH used to be hosted in a private repository that has been recently archived and moved to this repository.

You can run the following commands to update your TH code to the latest version:

```bash
rm -Rf <local_copy_of_the_old_repo>
git clone https://< Personal token Id >@github.com/project-chip/certification-tool.git
git fetch
git checkout v2.10-beta1+Spring2024
git submodule update --init
./scripts/ubuntu/auto-update.sh v2.10-beta1+Spring2024
./scripts/start.sh
```
