### ISSUE TITLE
[Bug] Inconsistency in handling v24 PICS XMLs in PICS TOOL 2.0

### ISSUE THREAD

**Issue by EDTEmadH** [project-chip/certification-tool#96]
### Describe the bug

Online PICS Tool 2.0 does not seem to process the XML files v24 correctly. Number of test cases and description does not seem consistent with PICS 1.6.15 Matter 1.2 Fall release 2023 (rev 24). 

Please see the results using the same set of PICS v24 on both PICS tool releases
<img width="1683" alt="PICS_v1 16 5_SVE1 2" src="https://github.com/project-chip/certification-tool/assets/98744804/8279c01e-0f59-4705-ae6b-7ce132e9ba4f">

<img width="1731" alt="PICS_v2 0_Issue" src="https://github.com/project-chip/certification-tool/assets/98744804/cea699b8-52fc-4bd4-90de-f3c9e010b293">

### Steps to reproduce the behavior

1. Open PICS tool v2.0
2. Upload PICS files v24 (Matter 1.2)

### Expected behavior

Correct files are processed and list of applicable test cases is generated

**Comment by fabiowmm** [comment]
Deprioritized.
